// Code generated by ent, DO NOT EDIT.

package consentsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/auth-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldEQ(FieldUserID, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldEQ(FieldClientID, v))
}

// GrantedScopes applies equality check predicate on the "granted_scopes" field. It's identical to GrantedScopesEQ.
func GrantedScopes(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldEQ(FieldGrantedScopes, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldEQ(FieldExpiresAt, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldEQ(FieldLastUsedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldLTE(FieldUserID, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldContainsFold(FieldClientID, v))
}

// GrantedScopesEQ applies the EQ predicate on the "granted_scopes" field.
func GrantedScopesEQ(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldEQ(FieldGrantedScopes, v))
}

// GrantedScopesNEQ applies the NEQ predicate on the "granted_scopes" field.
func GrantedScopesNEQ(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldNEQ(FieldGrantedScopes, v))
}

// GrantedScopesIn applies the In predicate on the "granted_scopes" field.
func GrantedScopesIn(vs ...string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldIn(FieldGrantedScopes, vs...))
}

// GrantedScopesNotIn applies the NotIn predicate on the "granted_scopes" field.
func GrantedScopesNotIn(vs ...string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldNotIn(FieldGrantedScopes, vs...))
}

// GrantedScopesGT applies the GT predicate on the "granted_scopes" field.
func GrantedScopesGT(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldGT(FieldGrantedScopes, v))
}

// GrantedScopesGTE applies the GTE predicate on the "granted_scopes" field.
func GrantedScopesGTE(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldGTE(FieldGrantedScopes, v))
}

// GrantedScopesLT applies the LT predicate on the "granted_scopes" field.
func GrantedScopesLT(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldLT(FieldGrantedScopes, v))
}

// GrantedScopesLTE applies the LTE predicate on the "granted_scopes" field.
func GrantedScopesLTE(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldLTE(FieldGrantedScopes, v))
}

// GrantedScopesContains applies the Contains predicate on the "granted_scopes" field.
func GrantedScopesContains(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldContains(FieldGrantedScopes, v))
}

// GrantedScopesHasPrefix applies the HasPrefix predicate on the "granted_scopes" field.
func GrantedScopesHasPrefix(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldHasPrefix(FieldGrantedScopes, v))
}

// GrantedScopesHasSuffix applies the HasSuffix predicate on the "granted_scopes" field.
func GrantedScopesHasSuffix(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldHasSuffix(FieldGrantedScopes, v))
}

// GrantedScopesEqualFold applies the EqualFold predicate on the "granted_scopes" field.
func GrantedScopesEqualFold(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldEqualFold(FieldGrantedScopes, v))
}

// GrantedScopesContainsFold applies the ContainsFold predicate on the "granted_scopes" field.
func GrantedScopesContainsFold(v string) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldContainsFold(FieldGrantedScopes, v))
}

// GrantedClaimsIsNil applies the IsNil predicate on the "granted_claims" field.
func GrantedClaimsIsNil() predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldIsNull(FieldGrantedClaims))
}

// GrantedClaimsNotNil applies the NotNil predicate on the "granted_claims" field.
func GrantedClaimsNotNil() predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldNotNull(FieldGrantedClaims))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldNotNull(FieldExpiresAt))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldNotNull(FieldLastUsedAt))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ConsentSession {
	return predicate.ConsentSession(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ConsentSession) predicate.ConsentSession {
	return predicate.ConsentSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ConsentSession) predicate.ConsentSession {
	return predicate.ConsentSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ConsentSession) predicate.ConsentSession {
	return predicate.ConsentSession(sql.NotPredicates(p))
}
