// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/auth-api/internal/ent/app"
	"github.com/google/uuid"
)

// AppCreate is the builder for creating a App entity.
type AppCreate struct {
	config
	mutation *AppMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *AppCreate) SetName(v string) *AppCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *AppCreate) SetDescription(v string) *AppCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *AppCreate) SetNillableDescription(v *string) *AppCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetAppType sets the "app_type" field.
func (_c *AppCreate) SetAppType(v app.AppType) *AppCreate {
	_c.mutation.SetAppType(v)
	return _c
}

// SetNillableAppType sets the "app_type" field if the given value is not nil.
func (_c *AppCreate) SetNillableAppType(v *app.AppType) *AppCreate {
	if v != nil {
		_c.SetAppType(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *AppCreate) SetTenantID(v uuid.UUID) *AppCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *AppCreate) SetNillableTenantID(v *uuid.UUID) *AppCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *AppCreate) SetCreatedBy(v uuid.UUID) *AppCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *AppCreate) SetNillableCreatedBy(v *uuid.UUID) *AppCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *AppCreate) SetClientID(v string) *AppCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetKeyHash sets the "key_hash" field.
func (_c *AppCreate) SetKeyHash(v string) *AppCreate {
	_c.mutation.SetKeyHash(v)
	return _c
}

// SetKeyPrefix sets the "key_prefix" field.
func (_c *AppCreate) SetKeyPrefix(v string) *AppCreate {
	_c.mutation.SetKeyPrefix(v)
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *AppCreate) SetScopes(v []string) *AppCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetAllowedIps sets the "allowed_ips" field.
func (_c *AppCreate) SetAllowedIps(v []string) *AppCreate {
	_c.mutation.SetAllowedIps(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AppCreate) SetStatus(v app.Status) *AppCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AppCreate) SetNillableStatus(v *app.Status) *AppCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *AppCreate) SetExpiresAt(v time.Time) *AppCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *AppCreate) SetNillableExpiresAt(v *time.Time) *AppCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *AppCreate) SetLastUsedAt(v time.Time) *AppCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *AppCreate) SetNillableLastUsedAt(v *time.Time) *AppCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetLastUsedIP sets the "last_used_ip" field.
func (_c *AppCreate) SetLastUsedIP(v string) *AppCreate {
	_c.mutation.SetLastUsedIP(v)
	return _c
}

// SetNillableLastUsedIP sets the "last_used_ip" field if the given value is not nil.
func (_c *AppCreate) SetNillableLastUsedIP(v *string) *AppCreate {
	if v != nil {
		_c.SetLastUsedIP(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AppCreate) SetCreatedAt(v time.Time) *AppCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AppCreate) SetNillableCreatedAt(v *time.Time) *AppCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AppCreate) SetUpdatedAt(v time.Time) *AppCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AppCreate) SetNillableUpdatedAt(v *time.Time) *AppCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *AppCreate) SetRevokedAt(v time.Time) *AppCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *AppCreate) SetNillableRevokedAt(v *time.Time) *AppCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetRevokedReason sets the "revoked_reason" field.
func (_c *AppCreate) SetRevokedReason(v string) *AppCreate {
	_c.mutation.SetRevokedReason(v)
	return _c
}

// SetNillableRevokedReason sets the "revoked_reason" field if the given value is not nil.
func (_c *AppCreate) SetNillableRevokedReason(v *string) *AppCreate {
	if v != nil {
		_c.SetRevokedReason(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AppCreate) SetID(v uuid.UUID) *AppCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AppCreate) SetNillableID(v *uuid.UUID) *AppCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AppMutation object of the builder.
func (_c *AppCreate) Mutation() *AppMutation {
	return _c.mutation
}

// Save creates the App in the database.
func (_c *AppCreate) Save(ctx context.Context) (*App, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AppCreate) SaveX(ctx context.Context) *App {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AppCreate) defaults() {
	if _, ok := _c.mutation.AppType(); !ok {
		v := app.DefaultAppType
		_c.mutation.SetAppType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := app.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := app.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := app.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := app.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AppCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "App.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := app.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "App.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AppType(); !ok {
		return &ValidationError{Name: "app_type", err: errors.New(`ent: missing required field "App.app_type"`)}
	}
	if v, ok := _c.mutation.AppType(); ok {
		if err := app.AppTypeValidator(v); err != nil {
			return &ValidationError{Name: "app_type", err: fmt.Errorf(`ent: validator failed for field "App.app_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "App.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := app.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "App.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KeyHash(); !ok {
		return &ValidationError{Name: "key_hash", err: errors.New(`ent: missing required field "App.key_hash"`)}
	}
	if v, ok := _c.mutation.KeyHash(); ok {
		if err := app.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "App.key_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KeyPrefix(); !ok {
		return &ValidationError{Name: "key_prefix", err: errors.New(`ent: missing required field "App.key_prefix"`)}
	}
	if v, ok := _c.mutation.KeyPrefix(); ok {
		if err := app.KeyPrefixValidator(v); err != nil {
			return &ValidationError{Name: "key_prefix", err: fmt.Errorf(`ent: validator failed for field "App.key_prefix": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "App.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := app.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "App.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "App.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "App.updated_at"`)}
	}
	return nil
}

func (_c *AppCreate) sqlSave(ctx context.Context) (*App, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AppCreate) createSpec() (*App, *sqlgraph.CreateSpec) {
	var (
		_node = &App{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(app.Table, sqlgraph.NewFieldSpec(app.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(app.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(app.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.AppType(); ok {
		_spec.SetField(app.FieldAppType, field.TypeEnum, value)
		_node.AppType = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(app.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(app.FieldCreatedBy, field.TypeUUID, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(app.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.KeyHash(); ok {
		_spec.SetField(app.FieldKeyHash, field.TypeString, value)
		_node.KeyHash = value
	}
	if value, ok := _c.mutation.KeyPrefix(); ok {
		_spec.SetField(app.FieldKeyPrefix, field.TypeString, value)
		_node.KeyPrefix = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(app.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.AllowedIps(); ok {
		_spec.SetField(app.FieldAllowedIps, field.TypeJSON, value)
		_node.AllowedIps = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(app.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(app.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(app.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.LastUsedIP(); ok {
		_spec.SetField(app.FieldLastUsedIP, field.TypeString, value)
		_node.LastUsedIP = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(app.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(app.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(app.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.RevokedReason(); ok {
		_spec.SetField(app.FieldRevokedReason, field.TypeString, value)
		_node.RevokedReason = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.App.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AppUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *AppCreate) OnConflict(opts ...sql.ConflictOption) *AppUpsertOne {
	_c.conflict = opts
	return &AppUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.App.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AppCreate) OnConflictColumns(columns ...string) *AppUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AppUpsertOne{
		create: _c,
	}
}

type (
	// AppUpsertOne is the builder for "upsert"-ing
	//  one App node.
	AppUpsertOne struct {
		create *AppCreate
	}

	// AppUpsert is the "OnConflict" setter.
	AppUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *AppUpsert) SetName(v string) *AppUpsert {
	u.Set(app.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AppUpsert) UpdateName() *AppUpsert {
	u.SetExcluded(app.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *AppUpsert) SetDescription(v string) *AppUpsert {
	u.Set(app.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AppUpsert) UpdateDescription() *AppUpsert {
	u.SetExcluded(app.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *AppUpsert) ClearDescription() *AppUpsert {
	u.SetNull(app.FieldDescription)
	return u
}

// SetAppType sets the "app_type" field.
func (u *AppUpsert) SetAppType(v app.AppType) *AppUpsert {
	u.Set(app.FieldAppType, v)
	return u
}

// UpdateAppType sets the "app_type" field to the value that was provided on create.
func (u *AppUpsert) UpdateAppType() *AppUpsert {
	u.SetExcluded(app.FieldAppType)
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *AppUpsert) SetTenantID(v uuid.UUID) *AppUpsert {
	u.Set(app.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *AppUpsert) UpdateTenantID() *AppUpsert {
	u.SetExcluded(app.FieldTenantID)
	return u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *AppUpsert) ClearTenantID() *AppUpsert {
	u.SetNull(app.FieldTenantID)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *AppUpsert) SetCreatedBy(v uuid.UUID) *AppUpsert {
	u.Set(app.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AppUpsert) UpdateCreatedBy() *AppUpsert {
	u.SetExcluded(app.FieldCreatedBy)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *AppUpsert) ClearCreatedBy() *AppUpsert {
	u.SetNull(app.FieldCreatedBy)
	return u
}

// SetClientID sets the "client_id" field.
func (u *AppUpsert) SetClientID(v string) *AppUpsert {
	u.Set(app.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *AppUpsert) UpdateClientID() *AppUpsert {
	u.SetExcluded(app.FieldClientID)
	return u
}

// SetKeyHash sets the "key_hash" field.
func (u *AppUpsert) SetKeyHash(v string) *AppUpsert {
	u.Set(app.FieldKeyHash, v)
	return u
}

// UpdateKeyHash sets the "key_hash" field to the value that was provided on create.
func (u *AppUpsert) UpdateKeyHash() *AppUpsert {
	u.SetExcluded(app.FieldKeyHash)
	return u
}

// SetKeyPrefix sets the "key_prefix" field.
func (u *AppUpsert) SetKeyPrefix(v string) *AppUpsert {
	u.Set(app.FieldKeyPrefix, v)
	return u
}

// UpdateKeyPrefix sets the "key_prefix" field to the value that was provided on create.
func (u *AppUpsert) UpdateKeyPrefix() *AppUpsert {
	u.SetExcluded(app.FieldKeyPrefix)
	return u
}

// SetScopes sets the "scopes" field.
func (u *AppUpsert) SetScopes(v []string) *AppUpsert {
	u.Set(app.FieldScopes, v)
	return u
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *AppUpsert) UpdateScopes() *AppUpsert {
	u.SetExcluded(app.FieldScopes)
	return u
}

// ClearScopes clears the value of the "scopes" field.
func (u *AppUpsert) ClearScopes() *AppUpsert {
	u.SetNull(app.FieldScopes)
	return u
}

// SetAllowedIps sets the "allowed_ips" field.
func (u *AppUpsert) SetAllowedIps(v []string) *AppUpsert {
	u.Set(app.FieldAllowedIps, v)
	return u
}

// UpdateAllowedIps sets the "allowed_ips" field to the value that was provided on create.
func (u *AppUpsert) UpdateAllowedIps() *AppUpsert {
	u.SetExcluded(app.FieldAllowedIps)
	return u
}

// ClearAllowedIps clears the value of the "allowed_ips" field.
func (u *AppUpsert) ClearAllowedIps() *AppUpsert {
	u.SetNull(app.FieldAllowedIps)
	return u
}

// SetStatus sets the "status" field.
func (u *AppUpsert) SetStatus(v app.Status) *AppUpsert {
	u.Set(app.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AppUpsert) UpdateStatus() *AppUpsert {
	u.SetExcluded(app.FieldStatus)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *AppUpsert) SetExpiresAt(v time.Time) *AppUpsert {
	u.Set(app.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AppUpsert) UpdateExpiresAt() *AppUpsert {
	u.SetExcluded(app.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *AppUpsert) ClearExpiresAt() *AppUpsert {
	u.SetNull(app.FieldExpiresAt)
	return u
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *AppUpsert) SetLastUsedAt(v time.Time) *AppUpsert {
	u.Set(app.FieldLastUsedAt, v)
	return u
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *AppUpsert) UpdateLastUsedAt() *AppUpsert {
	u.SetExcluded(app.FieldLastUsedAt)
	return u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *AppUpsert) ClearLastUsedAt() *AppUpsert {
	u.SetNull(app.FieldLastUsedAt)
	return u
}

// SetLastUsedIP sets the "last_used_ip" field.
func (u *AppUpsert) SetLastUsedIP(v string) *AppUpsert {
	u.Set(app.FieldLastUsedIP, v)
	return u
}

// UpdateLastUsedIP sets the "last_used_ip" field to the value that was provided on create.
func (u *AppUpsert) UpdateLastUsedIP() *AppUpsert {
	u.SetExcluded(app.FieldLastUsedIP)
	return u
}

// ClearLastUsedIP clears the value of the "last_used_ip" field.
func (u *AppUpsert) ClearLastUsedIP() *AppUpsert {
	u.SetNull(app.FieldLastUsedIP)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AppUpsert) SetUpdatedAt(v time.Time) *AppUpsert {
	u.Set(app.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AppUpsert) UpdateUpdatedAt() *AppUpsert {
	u.SetExcluded(app.FieldUpdatedAt)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AppUpsert) SetRevokedAt(v time.Time) *AppUpsert {
	u.Set(app.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AppUpsert) UpdateRevokedAt() *AppUpsert {
	u.SetExcluded(app.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AppUpsert) ClearRevokedAt() *AppUpsert {
	u.SetNull(app.FieldRevokedAt)
	return u
}

// SetRevokedReason sets the "revoked_reason" field.
func (u *AppUpsert) SetRevokedReason(v string) *AppUpsert {
	u.Set(app.FieldRevokedReason, v)
	return u
}

// UpdateRevokedReason sets the "revoked_reason" field to the value that was provided on create.
func (u *AppUpsert) UpdateRevokedReason() *AppUpsert {
	u.SetExcluded(app.FieldRevokedReason)
	return u
}

// ClearRevokedReason clears the value of the "revoked_reason" field.
func (u *AppUpsert) ClearRevokedReason() *AppUpsert {
	u.SetNull(app.FieldRevokedReason)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.App.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(app.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AppUpsertOne) UpdateNewValues() *AppUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(app.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(app.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.App.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AppUpsertOne) Ignore() *AppUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AppUpsertOne) DoNothing() *AppUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AppCreate.OnConflict
// documentation for more info.
func (u *AppUpsertOne) Update(set func(*AppUpsert)) *AppUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AppUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *AppUpsertOne) SetName(v string) *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AppUpsertOne) UpdateName() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *AppUpsertOne) SetDescription(v string) *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AppUpsertOne) UpdateDescription() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *AppUpsertOne) ClearDescription() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.ClearDescription()
	})
}

// SetAppType sets the "app_type" field.
func (u *AppUpsertOne) SetAppType(v app.AppType) *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.SetAppType(v)
	})
}

// UpdateAppType sets the "app_type" field to the value that was provided on create.
func (u *AppUpsertOne) UpdateAppType() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.UpdateAppType()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *AppUpsertOne) SetTenantID(v uuid.UUID) *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *AppUpsertOne) UpdateTenantID() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.UpdateTenantID()
	})
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *AppUpsertOne) ClearTenantID() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.ClearTenantID()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *AppUpsertOne) SetCreatedBy(v uuid.UUID) *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AppUpsertOne) UpdateCreatedBy() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *AppUpsertOne) ClearCreatedBy() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.ClearCreatedBy()
	})
}

// SetClientID sets the "client_id" field.
func (u *AppUpsertOne) SetClientID(v string) *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *AppUpsertOne) UpdateClientID() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.UpdateClientID()
	})
}

// SetKeyHash sets the "key_hash" field.
func (u *AppUpsertOne) SetKeyHash(v string) *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.SetKeyHash(v)
	})
}

// UpdateKeyHash sets the "key_hash" field to the value that was provided on create.
func (u *AppUpsertOne) UpdateKeyHash() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.UpdateKeyHash()
	})
}

// SetKeyPrefix sets the "key_prefix" field.
func (u *AppUpsertOne) SetKeyPrefix(v string) *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.SetKeyPrefix(v)
	})
}

// UpdateKeyPrefix sets the "key_prefix" field to the value that was provided on create.
func (u *AppUpsertOne) UpdateKeyPrefix() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.UpdateKeyPrefix()
	})
}

// SetScopes sets the "scopes" field.
func (u *AppUpsertOne) SetScopes(v []string) *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *AppUpsertOne) UpdateScopes() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.UpdateScopes()
	})
}

// ClearScopes clears the value of the "scopes" field.
func (u *AppUpsertOne) ClearScopes() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.ClearScopes()
	})
}

// SetAllowedIps sets the "allowed_ips" field.
func (u *AppUpsertOne) SetAllowedIps(v []string) *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.SetAllowedIps(v)
	})
}

// UpdateAllowedIps sets the "allowed_ips" field to the value that was provided on create.
func (u *AppUpsertOne) UpdateAllowedIps() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.UpdateAllowedIps()
	})
}

// ClearAllowedIps clears the value of the "allowed_ips" field.
func (u *AppUpsertOne) ClearAllowedIps() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.ClearAllowedIps()
	})
}

// SetStatus sets the "status" field.
func (u *AppUpsertOne) SetStatus(v app.Status) *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AppUpsertOne) UpdateStatus() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *AppUpsertOne) SetExpiresAt(v time.Time) *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AppUpsertOne) UpdateExpiresAt() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *AppUpsertOne) ClearExpiresAt() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.ClearExpiresAt()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *AppUpsertOne) SetLastUsedAt(v time.Time) *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *AppUpsertOne) UpdateLastUsedAt() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *AppUpsertOne) ClearLastUsedAt() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetLastUsedIP sets the "last_used_ip" field.
func (u *AppUpsertOne) SetLastUsedIP(v string) *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.SetLastUsedIP(v)
	})
}

// UpdateLastUsedIP sets the "last_used_ip" field to the value that was provided on create.
func (u *AppUpsertOne) UpdateLastUsedIP() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.UpdateLastUsedIP()
	})
}

// ClearLastUsedIP clears the value of the "last_used_ip" field.
func (u *AppUpsertOne) ClearLastUsedIP() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.ClearLastUsedIP()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AppUpsertOne) SetUpdatedAt(v time.Time) *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AppUpsertOne) UpdateUpdatedAt() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AppUpsertOne) SetRevokedAt(v time.Time) *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AppUpsertOne) UpdateRevokedAt() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AppUpsertOne) ClearRevokedAt() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.ClearRevokedAt()
	})
}

// SetRevokedReason sets the "revoked_reason" field.
func (u *AppUpsertOne) SetRevokedReason(v string) *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.SetRevokedReason(v)
	})
}

// UpdateRevokedReason sets the "revoked_reason" field to the value that was provided on create.
func (u *AppUpsertOne) UpdateRevokedReason() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.UpdateRevokedReason()
	})
}

// ClearRevokedReason clears the value of the "revoked_reason" field.
func (u *AppUpsertOne) ClearRevokedReason() *AppUpsertOne {
	return u.Update(func(s *AppUpsert) {
		s.ClearRevokedReason()
	})
}

// Exec executes the query.
func (u *AppUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AppCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AppUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AppUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AppUpsertOne.ID is not supported by MySQL driver. Use AppUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AppUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AppCreateBulk is the builder for creating many App entities in bulk.
type AppCreateBulk struct {
	config
	err      error
	builders []*AppCreate
	conflict []sql.ConflictOption
}

// Save creates the App entities in the database.
func (_c *AppCreateBulk) Save(ctx context.Context) ([]*App, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*App, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AppCreateBulk) SaveX(ctx context.Context) []*App {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.App.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AppUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *AppCreateBulk) OnConflict(opts ...sql.ConflictOption) *AppUpsertBulk {
	_c.conflict = opts
	return &AppUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.App.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AppCreateBulk) OnConflictColumns(columns ...string) *AppUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AppUpsertBulk{
		create: _c,
	}
}

// AppUpsertBulk is the builder for "upsert"-ing
// a bulk of App nodes.
type AppUpsertBulk struct {
	create *AppCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.App.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(app.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AppUpsertBulk) UpdateNewValues() *AppUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(app.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(app.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.App.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AppUpsertBulk) Ignore() *AppUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AppUpsertBulk) DoNothing() *AppUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AppCreateBulk.OnConflict
// documentation for more info.
func (u *AppUpsertBulk) Update(set func(*AppUpsert)) *AppUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AppUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *AppUpsertBulk) SetName(v string) *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AppUpsertBulk) UpdateName() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *AppUpsertBulk) SetDescription(v string) *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AppUpsertBulk) UpdateDescription() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *AppUpsertBulk) ClearDescription() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.ClearDescription()
	})
}

// SetAppType sets the "app_type" field.
func (u *AppUpsertBulk) SetAppType(v app.AppType) *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.SetAppType(v)
	})
}

// UpdateAppType sets the "app_type" field to the value that was provided on create.
func (u *AppUpsertBulk) UpdateAppType() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.UpdateAppType()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *AppUpsertBulk) SetTenantID(v uuid.UUID) *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *AppUpsertBulk) UpdateTenantID() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.UpdateTenantID()
	})
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *AppUpsertBulk) ClearTenantID() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.ClearTenantID()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *AppUpsertBulk) SetCreatedBy(v uuid.UUID) *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AppUpsertBulk) UpdateCreatedBy() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *AppUpsertBulk) ClearCreatedBy() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.ClearCreatedBy()
	})
}

// SetClientID sets the "client_id" field.
func (u *AppUpsertBulk) SetClientID(v string) *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *AppUpsertBulk) UpdateClientID() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.UpdateClientID()
	})
}

// SetKeyHash sets the "key_hash" field.
func (u *AppUpsertBulk) SetKeyHash(v string) *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.SetKeyHash(v)
	})
}

// UpdateKeyHash sets the "key_hash" field to the value that was provided on create.
func (u *AppUpsertBulk) UpdateKeyHash() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.UpdateKeyHash()
	})
}

// SetKeyPrefix sets the "key_prefix" field.
func (u *AppUpsertBulk) SetKeyPrefix(v string) *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.SetKeyPrefix(v)
	})
}

// UpdateKeyPrefix sets the "key_prefix" field to the value that was provided on create.
func (u *AppUpsertBulk) UpdateKeyPrefix() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.UpdateKeyPrefix()
	})
}

// SetScopes sets the "scopes" field.
func (u *AppUpsertBulk) SetScopes(v []string) *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *AppUpsertBulk) UpdateScopes() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.UpdateScopes()
	})
}

// ClearScopes clears the value of the "scopes" field.
func (u *AppUpsertBulk) ClearScopes() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.ClearScopes()
	})
}

// SetAllowedIps sets the "allowed_ips" field.
func (u *AppUpsertBulk) SetAllowedIps(v []string) *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.SetAllowedIps(v)
	})
}

// UpdateAllowedIps sets the "allowed_ips" field to the value that was provided on create.
func (u *AppUpsertBulk) UpdateAllowedIps() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.UpdateAllowedIps()
	})
}

// ClearAllowedIps clears the value of the "allowed_ips" field.
func (u *AppUpsertBulk) ClearAllowedIps() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.ClearAllowedIps()
	})
}

// SetStatus sets the "status" field.
func (u *AppUpsertBulk) SetStatus(v app.Status) *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AppUpsertBulk) UpdateStatus() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *AppUpsertBulk) SetExpiresAt(v time.Time) *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AppUpsertBulk) UpdateExpiresAt() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *AppUpsertBulk) ClearExpiresAt() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.ClearExpiresAt()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *AppUpsertBulk) SetLastUsedAt(v time.Time) *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *AppUpsertBulk) UpdateLastUsedAt() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *AppUpsertBulk) ClearLastUsedAt() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetLastUsedIP sets the "last_used_ip" field.
func (u *AppUpsertBulk) SetLastUsedIP(v string) *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.SetLastUsedIP(v)
	})
}

// UpdateLastUsedIP sets the "last_used_ip" field to the value that was provided on create.
func (u *AppUpsertBulk) UpdateLastUsedIP() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.UpdateLastUsedIP()
	})
}

// ClearLastUsedIP clears the value of the "last_used_ip" field.
func (u *AppUpsertBulk) ClearLastUsedIP() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.ClearLastUsedIP()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AppUpsertBulk) SetUpdatedAt(v time.Time) *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AppUpsertBulk) UpdateUpdatedAt() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AppUpsertBulk) SetRevokedAt(v time.Time) *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AppUpsertBulk) UpdateRevokedAt() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AppUpsertBulk) ClearRevokedAt() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.ClearRevokedAt()
	})
}

// SetRevokedReason sets the "revoked_reason" field.
func (u *AppUpsertBulk) SetRevokedReason(v string) *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.SetRevokedReason(v)
	})
}

// UpdateRevokedReason sets the "revoked_reason" field to the value that was provided on create.
func (u *AppUpsertBulk) UpdateRevokedReason() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.UpdateRevokedReason()
	})
}

// ClearRevokedReason clears the value of the "revoked_reason" field.
func (u *AppUpsertBulk) ClearRevokedReason() *AppUpsertBulk {
	return u.Update(func(s *AppUpsert) {
		s.ClearRevokedReason()
	})
}

// Exec executes the query.
func (u *AppUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AppCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AppCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AppUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
