// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/auth-api/internal/ent/app"
	"github.com/bengobox/auth-api/internal/ent/predicate"
	"github.com/google/uuid"
)

// AppUpdate is the builder for updating App entities.
type AppUpdate struct {
	config
	hooks    []Hook
	mutation *AppMutation
}

// Where appends a list predicates to the AppUpdate builder.
func (_u *AppUpdate) Where(ps ...predicate.App) *AppUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *AppUpdate) SetName(v string) *AppUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AppUpdate) SetNillableName(v *string) *AppUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AppUpdate) SetDescription(v string) *AppUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AppUpdate) SetNillableDescription(v *string) *AppUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AppUpdate) ClearDescription() *AppUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetAppType sets the "app_type" field.
func (_u *AppUpdate) SetAppType(v app.AppType) *AppUpdate {
	_u.mutation.SetAppType(v)
	return _u
}

// SetNillableAppType sets the "app_type" field if the given value is not nil.
func (_u *AppUpdate) SetNillableAppType(v *app.AppType) *AppUpdate {
	if v != nil {
		_u.SetAppType(*v)
	}
	return _u
}

// SetEnvironment sets the "environment" field.
func (_u *AppUpdate) SetEnvironment(v app.Environment) *AppUpdate {
	_u.mutation.SetEnvironment(v)
	return _u
}

// SetNillableEnvironment sets the "environment" field if the given value is not nil.
func (_u *AppUpdate) SetNillableEnvironment(v *app.Environment) *AppUpdate {
	if v != nil {
		_u.SetEnvironment(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *AppUpdate) SetTenantID(v uuid.UUID) *AppUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *AppUpdate) SetNillableTenantID(v *uuid.UUID) *AppUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *AppUpdate) ClearTenantID() *AppUpdate {
	_u.mutation.ClearTenantID()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AppUpdate) SetCreatedBy(v uuid.UUID) *AppUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AppUpdate) SetNillableCreatedBy(v *uuid.UUID) *AppUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *AppUpdate) ClearCreatedBy() *AppUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *AppUpdate) SetClientID(v string) *AppUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *AppUpdate) SetNillableClientID(v *string) *AppUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetKeyHash sets the "key_hash" field.
func (_u *AppUpdate) SetKeyHash(v string) *AppUpdate {
	_u.mutation.SetKeyHash(v)
	return _u
}

// SetNillableKeyHash sets the "key_hash" field if the given value is not nil.
func (_u *AppUpdate) SetNillableKeyHash(v *string) *AppUpdate {
	if v != nil {
		_u.SetKeyHash(*v)
	}
	return _u
}

// SetKeyPrefix sets the "key_prefix" field.
func (_u *AppUpdate) SetKeyPrefix(v string) *AppUpdate {
	_u.mutation.SetKeyPrefix(v)
	return _u
}

// SetNillableKeyPrefix sets the "key_prefix" field if the given value is not nil.
func (_u *AppUpdate) SetNillableKeyPrefix(v *string) *AppUpdate {
	if v != nil {
		_u.SetKeyPrefix(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *AppUpdate) SetScopes(v []string) *AppUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *AppUpdate) AppendScopes(v []string) *AppUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// ClearScopes clears the value of the "scopes" field.
func (_u *AppUpdate) ClearScopes() *AppUpdate {
	_u.mutation.ClearScopes()
	return _u
}

// SetAllowedIps sets the "allowed_ips" field.
func (_u *AppUpdate) SetAllowedIps(v []string) *AppUpdate {
	_u.mutation.SetAllowedIps(v)
	return _u
}

// AppendAllowedIps appends value to the "allowed_ips" field.
func (_u *AppUpdate) AppendAllowedIps(v []string) *AppUpdate {
	_u.mutation.AppendAllowedIps(v)
	return _u
}

// ClearAllowedIps clears the value of the "allowed_ips" field.
func (_u *AppUpdate) ClearAllowedIps() *AppUpdate {
	_u.mutation.ClearAllowedIps()
	return _u
}

// SetStatus sets the "status" field.
func (_u *AppUpdate) SetStatus(v app.Status) *AppUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AppUpdate) SetNillableStatus(v *app.Status) *AppUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AppUpdate) SetExpiresAt(v time.Time) *AppUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AppUpdate) SetNillableExpiresAt(v *time.Time) *AppUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *AppUpdate) ClearExpiresAt() *AppUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *AppUpdate) SetLastUsedAt(v time.Time) *AppUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *AppUpdate) SetNillableLastUsedAt(v *time.Time) *AppUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *AppUpdate) ClearLastUsedAt() *AppUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetLastUsedIP sets the "last_used_ip" field.
func (_u *AppUpdate) SetLastUsedIP(v string) *AppUpdate {
	_u.mutation.SetLastUsedIP(v)
	return _u
}

// SetNillableLastUsedIP sets the "last_used_ip" field if the given value is not nil.
func (_u *AppUpdate) SetNillableLastUsedIP(v *string) *AppUpdate {
	if v != nil {
		_u.SetLastUsedIP(*v)
	}
	return _u
}

// ClearLastUsedIP clears the value of the "last_used_ip" field.
func (_u *AppUpdate) ClearLastUsedIP() *AppUpdate {
	_u.mutation.ClearLastUsedIP()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppUpdate) SetUpdatedAt(v time.Time) *AppUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *AppUpdate) SetRevokedAt(v time.Time) *AppUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *AppUpdate) SetNillableRevokedAt(v *time.Time) *AppUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *AppUpdate) ClearRevokedAt() *AppUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetRevokedReason sets the "revoked_reason" field.
func (_u *AppUpdate) SetRevokedReason(v string) *AppUpdate {
	_u.mutation.SetRevokedReason(v)
	return _u
}

// SetNillableRevokedReason sets the "revoked_reason" field if the given value is not nil.
func (_u *AppUpdate) SetNillableRevokedReason(v *string) *AppUpdate {
	if v != nil {
		_u.SetRevokedReason(*v)
	}
	return _u
}

// ClearRevokedReason clears the value of the "revoked_reason" field.
func (_u *AppUpdate) ClearRevokedReason() *AppUpdate {
	_u.mutation.ClearRevokedReason()
	return _u
}

// Mutation returns the AppMutation object of the builder.
func (_u *AppUpdate) Mutation() *AppMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AppUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AppUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AppUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := app.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AppUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := app.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "App.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppType(); ok {
		if err := app.AppTypeValidator(v); err != nil {
			return &ValidationError{Name: "app_type", err: fmt.Errorf(`ent: validator failed for field "App.app_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Environment(); ok {
		if err := app.EnvironmentValidator(v); err != nil {
			return &ValidationError{Name: "environment", err: fmt.Errorf(`ent: validator failed for field "App.environment": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := app.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "App.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyHash(); ok {
		if err := app.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "App.key_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyPrefix(); ok {
		if err := app.KeyPrefixValidator(v); err != nil {
			return &ValidationError{Name: "key_prefix", err: fmt.Errorf(`ent: validator failed for field "App.key_prefix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := app.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "App.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AppUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(app.Table, app.Columns, sqlgraph.NewFieldSpec(app.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(app.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(app.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(app.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.AppType(); ok {
		_spec.SetField(app.FieldAppType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Environment(); ok {
		_spec.SetField(app.FieldEnvironment, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(app.FieldTenantID, field.TypeUUID, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(app.FieldTenantID, field.TypeUUID)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(app.FieldCreatedBy, field.TypeUUID, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(app.FieldCreatedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(app.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyHash(); ok {
		_spec.SetField(app.FieldKeyHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyPrefix(); ok {
		_spec.SetField(app.FieldKeyPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(app.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, app.FieldScopes, value)
		})
	}
	if _u.mutation.ScopesCleared() {
		_spec.ClearField(app.FieldScopes, field.TypeJSON)
	}
	if value, ok := _u.mutation.AllowedIps(); ok {
		_spec.SetField(app.FieldAllowedIps, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedIps(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, app.FieldAllowedIps, value)
		})
	}
	if _u.mutation.AllowedIpsCleared() {
		_spec.ClearField(app.FieldAllowedIps, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(app.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(app.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(app.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(app.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(app.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedIP(); ok {
		_spec.SetField(app.FieldLastUsedIP, field.TypeString, value)
	}
	if _u.mutation.LastUsedIPCleared() {
		_spec.ClearField(app.FieldLastUsedIP, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(app.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(app.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(app.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedReason(); ok {
		_spec.SetField(app.FieldRevokedReason, field.TypeString, value)
	}
	if _u.mutation.RevokedReasonCleared() {
		_spec.ClearField(app.FieldRevokedReason, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{app.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AppUpdateOne is the builder for updating a single App entity.
type AppUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppMutation
}

// SetName sets the "name" field.
func (_u *AppUpdateOne) SetName(v string) *AppUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableName(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AppUpdateOne) SetDescription(v string) *AppUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableDescription(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AppUpdateOne) ClearDescription() *AppUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetAppType sets the "app_type" field.
func (_u *AppUpdateOne) SetAppType(v app.AppType) *AppUpdateOne {
	_u.mutation.SetAppType(v)
	return _u
}

// SetNillableAppType sets the "app_type" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableAppType(v *app.AppType) *AppUpdateOne {
	if v != nil {
		_u.SetAppType(*v)
	}
	return _u
}

// SetEnvironment sets the "environment" field.
func (_u *AppUpdateOne) SetEnvironment(v app.Environment) *AppUpdateOne {
	_u.mutation.SetEnvironment(v)
	return _u
}

// SetNillableEnvironment sets the "environment" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableEnvironment(v *app.Environment) *AppUpdateOne {
	if v != nil {
		_u.SetEnvironment(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *AppUpdateOne) SetTenantID(v uuid.UUID) *AppUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableTenantID(v *uuid.UUID) *AppUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *AppUpdateOne) ClearTenantID() *AppUpdateOne {
	_u.mutation.ClearTenantID()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AppUpdateOne) SetCreatedBy(v uuid.UUID) *AppUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *AppUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *AppUpdateOne) ClearCreatedBy() *AppUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *AppUpdateOne) SetClientID(v string) *AppUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableClientID(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetKeyHash sets the "key_hash" field.
func (_u *AppUpdateOne) SetKeyHash(v string) *AppUpdateOne {
	_u.mutation.SetKeyHash(v)
	return _u
}

// SetNillableKeyHash sets the "key_hash" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableKeyHash(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetKeyHash(*v)
	}
	return _u
}

// SetKeyPrefix sets the "key_prefix" field.
func (_u *AppUpdateOne) SetKeyPrefix(v string) *AppUpdateOne {
	_u.mutation.SetKeyPrefix(v)
	return _u
}

// SetNillableKeyPrefix sets the "key_prefix" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableKeyPrefix(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetKeyPrefix(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *AppUpdateOne) SetScopes(v []string) *AppUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *AppUpdateOne) AppendScopes(v []string) *AppUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// ClearScopes clears the value of the "scopes" field.
func (_u *AppUpdateOne) ClearScopes() *AppUpdateOne {
	_u.mutation.ClearScopes()
	return _u
}

// SetAllowedIps sets the "allowed_ips" field.
func (_u *AppUpdateOne) SetAllowedIps(v []string) *AppUpdateOne {
	_u.mutation.SetAllowedIps(v)
	return _u
}

// AppendAllowedIps appends value to the "allowed_ips" field.
func (_u *AppUpdateOne) AppendAllowedIps(v []string) *AppUpdateOne {
	_u.mutation.AppendAllowedIps(v)
	return _u
}

// ClearAllowedIps clears the value of the "allowed_ips" field.
func (_u *AppUpdateOne) ClearAllowedIps() *AppUpdateOne {
	_u.mutation.ClearAllowedIps()
	return _u
}

// SetStatus sets the "status" field.
func (_u *AppUpdateOne) SetStatus(v app.Status) *AppUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableStatus(v *app.Status) *AppUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AppUpdateOne) SetExpiresAt(v time.Time) *AppUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableExpiresAt(v *time.Time) *AppUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *AppUpdateOne) ClearExpiresAt() *AppUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *AppUpdateOne) SetLastUsedAt(v time.Time) *AppUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableLastUsedAt(v *time.Time) *AppUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *AppUpdateOne) ClearLastUsedAt() *AppUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetLastUsedIP sets the "last_used_ip" field.
func (_u *AppUpdateOne) SetLastUsedIP(v string) *AppUpdateOne {
	_u.mutation.SetLastUsedIP(v)
	return _u
}

// SetNillableLastUsedIP sets the "last_used_ip" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableLastUsedIP(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetLastUsedIP(*v)
	}
	return _u
}

// ClearLastUsedIP clears the value of the "last_used_ip" field.
func (_u *AppUpdateOne) ClearLastUsedIP() *AppUpdateOne {
	_u.mutation.ClearLastUsedIP()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppUpdateOne) SetUpdatedAt(v time.Time) *AppUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *AppUpdateOne) SetRevokedAt(v time.Time) *AppUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableRevokedAt(v *time.Time) *AppUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *AppUpdateOne) ClearRevokedAt() *AppUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetRevokedReason sets the "revoked_reason" field.
func (_u *AppUpdateOne) SetRevokedReason(v string) *AppUpdateOne {
	_u.mutation.SetRevokedReason(v)
	return _u
}

// SetNillableRevokedReason sets the "revoked_reason" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableRevokedReason(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetRevokedReason(*v)
	}
	return _u
}

// ClearRevokedReason clears the value of the "revoked_reason" field.
func (_u *AppUpdateOne) ClearRevokedReason() *AppUpdateOne {
	_u.mutation.ClearRevokedReason()
	return _u
}

// Mutation returns the AppMutation object of the builder.
func (_u *AppUpdateOne) Mutation() *AppMutation {
	return _u.mutation
}

// Where appends a list predicates to the AppUpdate builder.
func (_u *AppUpdateOne) Where(ps ...predicate.App) *AppUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AppUpdateOne) Select(field string, fields ...string) *AppUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated App entity.
func (_u *AppUpdateOne) Save(ctx context.Context) (*App, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppUpdateOne) SaveX(ctx context.Context) *App {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AppUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AppUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := app.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AppUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := app.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "App.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppType(); ok {
		if err := app.AppTypeValidator(v); err != nil {
			return &ValidationError{Name: "app_type", err: fmt.Errorf(`ent: validator failed for field "App.app_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Environment(); ok {
		if err := app.EnvironmentValidator(v); err != nil {
			return &ValidationError{Name: "environment", err: fmt.Errorf(`ent: validator failed for field "App.environment": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := app.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "App.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyHash(); ok {
		if err := app.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "App.key_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyPrefix(); ok {
		if err := app.KeyPrefixValidator(v); err != nil {
			return &ValidationError{Name: "key_prefix", err: fmt.Errorf(`ent: validator failed for field "App.key_prefix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := app.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "App.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AppUpdateOne) sqlSave(ctx context.Context) (_node *App, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(app.Table, app.Columns, sqlgraph.NewFieldSpec(app.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "App.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, app.FieldID)
		for _, f := range fields {
			if !app.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != app.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(app.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(app.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(app.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.AppType(); ok {
		_spec.SetField(app.FieldAppType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Environment(); ok {
		_spec.SetField(app.FieldEnvironment, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(app.FieldTenantID, field.TypeUUID, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(app.FieldTenantID, field.TypeUUID)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(app.FieldCreatedBy, field.TypeUUID, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(app.FieldCreatedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(app.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyHash(); ok {
		_spec.SetField(app.FieldKeyHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyPrefix(); ok {
		_spec.SetField(app.FieldKeyPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(app.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, app.FieldScopes, value)
		})
	}
	if _u.mutation.ScopesCleared() {
		_spec.ClearField(app.FieldScopes, field.TypeJSON)
	}
	if value, ok := _u.mutation.AllowedIps(); ok {
		_spec.SetField(app.FieldAllowedIps, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedIps(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, app.FieldAllowedIps, value)
		})
	}
	if _u.mutation.AllowedIpsCleared() {
		_spec.ClearField(app.FieldAllowedIps, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(app.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(app.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(app.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(app.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(app.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedIP(); ok {
		_spec.SetField(app.FieldLastUsedIP, field.TypeString, value)
	}
	if _u.mutation.LastUsedIPCleared() {
		_spec.ClearField(app.FieldLastUsedIP, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(app.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(app.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(app.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedReason(); ok {
		_spec.SetField(app.FieldRevokedReason, field.TypeString, value)
	}
	if _u.mutation.RevokedReasonCleared() {
		_spec.ClearField(app.FieldRevokedReason, field.TypeString)
	}
	_node = &App{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{app.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
