// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/auth-service/internal/ent/authorizationcode"
	"github.com/bengobox/auth-service/internal/ent/user"
	"github.com/google/uuid"
)

// AuthorizationCodeCreate is the builder for creating a AuthorizationCode entity.
type AuthorizationCodeCreate struct {
	config
	mutation *AuthorizationCodeMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *AuthorizationCodeCreate) SetUserID(v uuid.UUID) *AuthorizationCodeCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *AuthorizationCodeCreate) SetClientID(v string) *AuthorizationCodeCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetRedirectURI sets the "redirect_uri" field.
func (_c *AuthorizationCodeCreate) SetRedirectURI(v string) *AuthorizationCodeCreate {
	_c.mutation.SetRedirectURI(v)
	return _c
}

// SetScope sets the "scope" field.
func (_c *AuthorizationCodeCreate) SetScope(v string) *AuthorizationCodeCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_c *AuthorizationCodeCreate) SetNillableScope(v *string) *AuthorizationCodeCreate {
	if v != nil {
		_c.SetScope(*v)
	}
	return _c
}

// SetCodeHash sets the "code_hash" field.
func (_c *AuthorizationCodeCreate) SetCodeHash(v string) *AuthorizationCodeCreate {
	_c.mutation.SetCodeHash(v)
	return _c
}

// SetCodeChallenge sets the "code_challenge" field.
func (_c *AuthorizationCodeCreate) SetCodeChallenge(v string) *AuthorizationCodeCreate {
	_c.mutation.SetCodeChallenge(v)
	return _c
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_c *AuthorizationCodeCreate) SetNillableCodeChallenge(v *string) *AuthorizationCodeCreate {
	if v != nil {
		_c.SetCodeChallenge(*v)
	}
	return _c
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_c *AuthorizationCodeCreate) SetCodeChallengeMethod(v string) *AuthorizationCodeCreate {
	_c.mutation.SetCodeChallengeMethod(v)
	return _c
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (_c *AuthorizationCodeCreate) SetNillableCodeChallengeMethod(v *string) *AuthorizationCodeCreate {
	if v != nil {
		_c.SetCodeChallengeMethod(*v)
	}
	return _c
}

// SetNonce sets the "nonce" field.
func (_c *AuthorizationCodeCreate) SetNonce(v string) *AuthorizationCodeCreate {
	_c.mutation.SetNonce(v)
	return _c
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (_c *AuthorizationCodeCreate) SetNillableNonce(v *string) *AuthorizationCodeCreate {
	if v != nil {
		_c.SetNonce(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *AuthorizationCodeCreate) SetExpiresAt(v time.Time) *AuthorizationCodeCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetConsumedAt sets the "consumed_at" field.
func (_c *AuthorizationCodeCreate) SetConsumedAt(v time.Time) *AuthorizationCodeCreate {
	_c.mutation.SetConsumedAt(v)
	return _c
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_c *AuthorizationCodeCreate) SetNillableConsumedAt(v *time.Time) *AuthorizationCodeCreate {
	if v != nil {
		_c.SetConsumedAt(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *AuthorizationCodeCreate) SetMetadata(v map[string]interface{}) *AuthorizationCodeCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuthorizationCodeCreate) SetCreatedAt(v time.Time) *AuthorizationCodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuthorizationCodeCreate) SetNillableCreatedAt(v *time.Time) *AuthorizationCodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuthorizationCodeCreate) SetID(v uuid.UUID) *AuthorizationCodeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AuthorizationCodeCreate) SetNillableID(v *uuid.UUID) *AuthorizationCodeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *AuthorizationCodeCreate) SetUser(v *User) *AuthorizationCodeCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the AuthorizationCodeMutation object of the builder.
func (_c *AuthorizationCodeCreate) Mutation() *AuthorizationCodeMutation {
	return _c.mutation
}

// Save creates the AuthorizationCode in the database.
func (_c *AuthorizationCodeCreate) Save(ctx context.Context) (*AuthorizationCode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthorizationCodeCreate) SaveX(ctx context.Context) *AuthorizationCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthorizationCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthorizationCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthorizationCodeCreate) defaults() {
	if _, ok := _c.mutation.Scope(); !ok {
		v := authorizationcode.DefaultScope
		_c.mutation.SetScope(v)
	}
	if _, ok := _c.mutation.CodeChallenge(); !ok {
		v := authorizationcode.DefaultCodeChallenge
		_c.mutation.SetCodeChallenge(v)
	}
	if _, ok := _c.mutation.CodeChallengeMethod(); !ok {
		v := authorizationcode.DefaultCodeChallengeMethod
		_c.mutation.SetCodeChallengeMethod(v)
	}
	if _, ok := _c.mutation.Nonce(); !ok {
		v := authorizationcode.DefaultNonce
		_c.mutation.SetNonce(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := authorizationcode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := authorizationcode.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthorizationCodeCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AuthorizationCode.user_id"`)}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "AuthorizationCode.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := authorizationcode.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "AuthorizationCode.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedirectURI(); !ok {
		return &ValidationError{Name: "redirect_uri", err: errors.New(`ent: missing required field "AuthorizationCode.redirect_uri"`)}
	}
	if v, ok := _c.mutation.RedirectURI(); ok {
		if err := authorizationcode.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "AuthorizationCode.redirect_uri": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "AuthorizationCode.scope"`)}
	}
	if _, ok := _c.mutation.CodeHash(); !ok {
		return &ValidationError{Name: "code_hash", err: errors.New(`ent: missing required field "AuthorizationCode.code_hash"`)}
	}
	if v, ok := _c.mutation.CodeHash(); ok {
		if err := authorizationcode.CodeHashValidator(v); err != nil {
			return &ValidationError{Name: "code_hash", err: fmt.Errorf(`ent: validator failed for field "AuthorizationCode.code_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CodeChallenge(); !ok {
		return &ValidationError{Name: "code_challenge", err: errors.New(`ent: missing required field "AuthorizationCode.code_challenge"`)}
	}
	if _, ok := _c.mutation.CodeChallengeMethod(); !ok {
		return &ValidationError{Name: "code_challenge_method", err: errors.New(`ent: missing required field "AuthorizationCode.code_challenge_method"`)}
	}
	if _, ok := _c.mutation.Nonce(); !ok {
		return &ValidationError{Name: "nonce", err: errors.New(`ent: missing required field "AuthorizationCode.nonce"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "AuthorizationCode.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuthorizationCode.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "AuthorizationCode.user"`)}
	}
	return nil
}

func (_c *AuthorizationCodeCreate) sqlSave(ctx context.Context) (*AuthorizationCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthorizationCodeCreate) createSpec() (*AuthorizationCode, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthorizationCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authorizationcode.Table, sqlgraph.NewFieldSpec(authorizationcode.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(authorizationcode.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.RedirectURI(); ok {
		_spec.SetField(authorizationcode.FieldRedirectURI, field.TypeString, value)
		_node.RedirectURI = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(authorizationcode.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.CodeHash(); ok {
		_spec.SetField(authorizationcode.FieldCodeHash, field.TypeString, value)
		_node.CodeHash = value
	}
	if value, ok := _c.mutation.CodeChallenge(); ok {
		_spec.SetField(authorizationcode.FieldCodeChallenge, field.TypeString, value)
		_node.CodeChallenge = value
	}
	if value, ok := _c.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(authorizationcode.FieldCodeChallengeMethod, field.TypeString, value)
		_node.CodeChallengeMethod = value
	}
	if value, ok := _c.mutation.Nonce(); ok {
		_spec.SetField(authorizationcode.FieldNonce, field.TypeString, value)
		_node.Nonce = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(authorizationcode.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.ConsumedAt(); ok {
		_spec.SetField(authorizationcode.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(authorizationcode.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(authorizationcode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authorizationcode.UserTable,
			Columns: []string{authorizationcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AuthorizationCodeCreateBulk is the builder for creating many AuthorizationCode entities in bulk.
type AuthorizationCodeCreateBulk struct {
	config
	err      error
	builders []*AuthorizationCodeCreate
}

// Save creates the AuthorizationCode entities in the database.
func (_c *AuthorizationCodeCreateBulk) Save(ctx context.Context) ([]*AuthorizationCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthorizationCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthorizationCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthorizationCodeCreateBulk) SaveX(ctx context.Context) []*AuthorizationCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthorizationCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthorizationCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
