// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/auth-api/internal/ent/equityholderapplication"
	"github.com/bengobox/auth-api/internal/ent/predicate"
	"github.com/google/uuid"
)

// EquityHolderApplicationUpdate is the builder for updating EquityHolderApplication entities.
type EquityHolderApplicationUpdate struct {
	config
	hooks    []Hook
	mutation *EquityHolderApplicationMutation
}

// Where appends a list predicates to the EquityHolderApplicationUpdate builder.
func (_u *EquityHolderApplicationUpdate) Where(ps ...predicate.EquityHolderApplication) *EquityHolderApplicationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *EquityHolderApplicationUpdate) SetTenantID(v uuid.UUID) *EquityHolderApplicationUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *EquityHolderApplicationUpdate) SetNillableTenantID(v *uuid.UUID) *EquityHolderApplicationUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *EquityHolderApplicationUpdate) SetStatus(v equityholderapplication.Status) *EquityHolderApplicationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EquityHolderApplicationUpdate) SetNillableStatus(v *equityholderapplication.Status) *EquityHolderApplicationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetKycReference sets the "kyc_reference" field.
func (_u *EquityHolderApplicationUpdate) SetKycReference(v string) *EquityHolderApplicationUpdate {
	_u.mutation.SetKycReference(v)
	return _u
}

// SetNillableKycReference sets the "kyc_reference" field if the given value is not nil.
func (_u *EquityHolderApplicationUpdate) SetNillableKycReference(v *string) *EquityHolderApplicationUpdate {
	if v != nil {
		_u.SetKycReference(*v)
	}
	return _u
}

// ClearKycReference clears the value of the "kyc_reference" field.
func (_u *EquityHolderApplicationUpdate) ClearKycReference() *EquityHolderApplicationUpdate {
	_u.mutation.ClearKycReference()
	return _u
}

// SetKycResult sets the "kyc_result" field.
func (_u *EquityHolderApplicationUpdate) SetKycResult(v string) *EquityHolderApplicationUpdate {
	_u.mutation.SetKycResult(v)
	return _u
}

// SetNillableKycResult sets the "kyc_result" field if the given value is not nil.
func (_u *EquityHolderApplicationUpdate) SetNillableKycResult(v *string) *EquityHolderApplicationUpdate {
	if v != nil {
		_u.SetKycResult(*v)
	}
	return _u
}

// ClearKycResult clears the value of the "kyc_result" field.
func (_u *EquityHolderApplicationUpdate) ClearKycResult() *EquityHolderApplicationUpdate {
	_u.mutation.ClearKycResult()
	return _u
}

// SetEpaAcceptanceID sets the "epa_acceptance_id" field.
func (_u *EquityHolderApplicationUpdate) SetEpaAcceptanceID(v uuid.UUID) *EquityHolderApplicationUpdate {
	_u.mutation.SetEpaAcceptanceID(v)
	return _u
}

// SetNillableEpaAcceptanceID sets the "epa_acceptance_id" field if the given value is not nil.
func (_u *EquityHolderApplicationUpdate) SetNillableEpaAcceptanceID(v *uuid.UUID) *EquityHolderApplicationUpdate {
	if v != nil {
		_u.SetEpaAcceptanceID(*v)
	}
	return _u
}

// ClearEpaAcceptanceID clears the value of the "epa_acceptance_id" field.
func (_u *EquityHolderApplicationUpdate) ClearEpaAcceptanceID() *EquityHolderApplicationUpdate {
	_u.mutation.ClearEpaAcceptanceID()
	return _u
}

// SetTreasuryHolderID sets the "treasury_holder_id" field.
func (_u *EquityHolderApplicationUpdate) SetTreasuryHolderID(v uuid.UUID) *EquityHolderApplicationUpdate {
	_u.mutation.SetTreasuryHolderID(v)
	return _u
}

// SetNillableTreasuryHolderID sets the "treasury_holder_id" field if the given value is not nil.
func (_u *EquityHolderApplicationUpdate) SetNillableTreasuryHolderID(v *uuid.UUID) *EquityHolderApplicationUpdate {
	if v != nil {
		_u.SetTreasuryHolderID(*v)
	}
	return _u
}

// ClearTreasuryHolderID clears the value of the "treasury_holder_id" field.
func (_u *EquityHolderApplicationUpdate) ClearTreasuryHolderID() *EquityHolderApplicationUpdate {
	_u.mutation.ClearTreasuryHolderID()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *EquityHolderApplicationUpdate) SetNotes(v string) *EquityHolderApplicationUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *EquityHolderApplicationUpdate) SetNillableNotes(v *string) *EquityHolderApplicationUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *EquityHolderApplicationUpdate) ClearNotes() *EquityHolderApplicationUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EquityHolderApplicationUpdate) SetUpdatedAt(v time.Time) *EquityHolderApplicationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the EquityHolderApplicationMutation object of the builder.
func (_u *EquityHolderApplicationUpdate) Mutation() *EquityHolderApplicationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EquityHolderApplicationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EquityHolderApplicationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EquityHolderApplicationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EquityHolderApplicationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EquityHolderApplicationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := equityholderapplication.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EquityHolderApplicationUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := equityholderapplication.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EquityHolderApplication.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KycReference(); ok {
		if err := equityholderapplication.KycReferenceValidator(v); err != nil {
			return &ValidationError{Name: "kyc_reference", err: fmt.Errorf(`ent: validator failed for field "EquityHolderApplication.kyc_reference": %w`, err)}
		}
	}
	return nil
}

func (_u *EquityHolderApplicationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(equityholderapplication.Table, equityholderapplication.Columns, sqlgraph.NewFieldSpec(equityholderapplication.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(equityholderapplication.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(equityholderapplication.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.KycReference(); ok {
		_spec.SetField(equityholderapplication.FieldKycReference, field.TypeString, value)
	}
	if _u.mutation.KycReferenceCleared() {
		_spec.ClearField(equityholderapplication.FieldKycReference, field.TypeString)
	}
	if value, ok := _u.mutation.KycResult(); ok {
		_spec.SetField(equityholderapplication.FieldKycResult, field.TypeString, value)
	}
	if _u.mutation.KycResultCleared() {
		_spec.ClearField(equityholderapplication.FieldKycResult, field.TypeString)
	}
	if value, ok := _u.mutation.EpaAcceptanceID(); ok {
		_spec.SetField(equityholderapplication.FieldEpaAcceptanceID, field.TypeUUID, value)
	}
	if _u.mutation.EpaAcceptanceIDCleared() {
		_spec.ClearField(equityholderapplication.FieldEpaAcceptanceID, field.TypeUUID)
	}
	if value, ok := _u.mutation.TreasuryHolderID(); ok {
		_spec.SetField(equityholderapplication.FieldTreasuryHolderID, field.TypeUUID, value)
	}
	if _u.mutation.TreasuryHolderIDCleared() {
		_spec.ClearField(equityholderapplication.FieldTreasuryHolderID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(equityholderapplication.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(equityholderapplication.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(equityholderapplication.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{equityholderapplication.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EquityHolderApplicationUpdateOne is the builder for updating a single EquityHolderApplication entity.
type EquityHolderApplicationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EquityHolderApplicationMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *EquityHolderApplicationUpdateOne) SetTenantID(v uuid.UUID) *EquityHolderApplicationUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *EquityHolderApplicationUpdateOne) SetNillableTenantID(v *uuid.UUID) *EquityHolderApplicationUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *EquityHolderApplicationUpdateOne) SetStatus(v equityholderapplication.Status) *EquityHolderApplicationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EquityHolderApplicationUpdateOne) SetNillableStatus(v *equityholderapplication.Status) *EquityHolderApplicationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetKycReference sets the "kyc_reference" field.
func (_u *EquityHolderApplicationUpdateOne) SetKycReference(v string) *EquityHolderApplicationUpdateOne {
	_u.mutation.SetKycReference(v)
	return _u
}

// SetNillableKycReference sets the "kyc_reference" field if the given value is not nil.
func (_u *EquityHolderApplicationUpdateOne) SetNillableKycReference(v *string) *EquityHolderApplicationUpdateOne {
	if v != nil {
		_u.SetKycReference(*v)
	}
	return _u
}

// ClearKycReference clears the value of the "kyc_reference" field.
func (_u *EquityHolderApplicationUpdateOne) ClearKycReference() *EquityHolderApplicationUpdateOne {
	_u.mutation.ClearKycReference()
	return _u
}

// SetKycResult sets the "kyc_result" field.
func (_u *EquityHolderApplicationUpdateOne) SetKycResult(v string) *EquityHolderApplicationUpdateOne {
	_u.mutation.SetKycResult(v)
	return _u
}

// SetNillableKycResult sets the "kyc_result" field if the given value is not nil.
func (_u *EquityHolderApplicationUpdateOne) SetNillableKycResult(v *string) *EquityHolderApplicationUpdateOne {
	if v != nil {
		_u.SetKycResult(*v)
	}
	return _u
}

// ClearKycResult clears the value of the "kyc_result" field.
func (_u *EquityHolderApplicationUpdateOne) ClearKycResult() *EquityHolderApplicationUpdateOne {
	_u.mutation.ClearKycResult()
	return _u
}

// SetEpaAcceptanceID sets the "epa_acceptance_id" field.
func (_u *EquityHolderApplicationUpdateOne) SetEpaAcceptanceID(v uuid.UUID) *EquityHolderApplicationUpdateOne {
	_u.mutation.SetEpaAcceptanceID(v)
	return _u
}

// SetNillableEpaAcceptanceID sets the "epa_acceptance_id" field if the given value is not nil.
func (_u *EquityHolderApplicationUpdateOne) SetNillableEpaAcceptanceID(v *uuid.UUID) *EquityHolderApplicationUpdateOne {
	if v != nil {
		_u.SetEpaAcceptanceID(*v)
	}
	return _u
}

// ClearEpaAcceptanceID clears the value of the "epa_acceptance_id" field.
func (_u *EquityHolderApplicationUpdateOne) ClearEpaAcceptanceID() *EquityHolderApplicationUpdateOne {
	_u.mutation.ClearEpaAcceptanceID()
	return _u
}

// SetTreasuryHolderID sets the "treasury_holder_id" field.
func (_u *EquityHolderApplicationUpdateOne) SetTreasuryHolderID(v uuid.UUID) *EquityHolderApplicationUpdateOne {
	_u.mutation.SetTreasuryHolderID(v)
	return _u
}

// SetNillableTreasuryHolderID sets the "treasury_holder_id" field if the given value is not nil.
func (_u *EquityHolderApplicationUpdateOne) SetNillableTreasuryHolderID(v *uuid.UUID) *EquityHolderApplicationUpdateOne {
	if v != nil {
		_u.SetTreasuryHolderID(*v)
	}
	return _u
}

// ClearTreasuryHolderID clears the value of the "treasury_holder_id" field.
func (_u *EquityHolderApplicationUpdateOne) ClearTreasuryHolderID() *EquityHolderApplicationUpdateOne {
	_u.mutation.ClearTreasuryHolderID()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *EquityHolderApplicationUpdateOne) SetNotes(v string) *EquityHolderApplicationUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *EquityHolderApplicationUpdateOne) SetNillableNotes(v *string) *EquityHolderApplicationUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *EquityHolderApplicationUpdateOne) ClearNotes() *EquityHolderApplicationUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EquityHolderApplicationUpdateOne) SetUpdatedAt(v time.Time) *EquityHolderApplicationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the EquityHolderApplicationMutation object of the builder.
func (_u *EquityHolderApplicationUpdateOne) Mutation() *EquityHolderApplicationMutation {
	return _u.mutation
}

// Where appends a list predicates to the EquityHolderApplicationUpdate builder.
func (_u *EquityHolderApplicationUpdateOne) Where(ps ...predicate.EquityHolderApplication) *EquityHolderApplicationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EquityHolderApplicationUpdateOne) Select(field string, fields ...string) *EquityHolderApplicationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EquityHolderApplication entity.
func (_u *EquityHolderApplicationUpdateOne) Save(ctx context.Context) (*EquityHolderApplication, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EquityHolderApplicationUpdateOne) SaveX(ctx context.Context) *EquityHolderApplication {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EquityHolderApplicationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EquityHolderApplicationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EquityHolderApplicationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := equityholderapplication.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EquityHolderApplicationUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := equityholderapplication.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EquityHolderApplication.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KycReference(); ok {
		if err := equityholderapplication.KycReferenceValidator(v); err != nil {
			return &ValidationError{Name: "kyc_reference", err: fmt.Errorf(`ent: validator failed for field "EquityHolderApplication.kyc_reference": %w`, err)}
		}
	}
	return nil
}

func (_u *EquityHolderApplicationUpdateOne) sqlSave(ctx context.Context) (_node *EquityHolderApplication, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(equityholderapplication.Table, equityholderapplication.Columns, sqlgraph.NewFieldSpec(equityholderapplication.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EquityHolderApplication.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, equityholderapplication.FieldID)
		for _, f := range fields {
			if !equityholderapplication.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != equityholderapplication.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(equityholderapplication.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(equityholderapplication.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.KycReference(); ok {
		_spec.SetField(equityholderapplication.FieldKycReference, field.TypeString, value)
	}
	if _u.mutation.KycReferenceCleared() {
		_spec.ClearField(equityholderapplication.FieldKycReference, field.TypeString)
	}
	if value, ok := _u.mutation.KycResult(); ok {
		_spec.SetField(equityholderapplication.FieldKycResult, field.TypeString, value)
	}
	if _u.mutation.KycResultCleared() {
		_spec.ClearField(equityholderapplication.FieldKycResult, field.TypeString)
	}
	if value, ok := _u.mutation.EpaAcceptanceID(); ok {
		_spec.SetField(equityholderapplication.FieldEpaAcceptanceID, field.TypeUUID, value)
	}
	if _u.mutation.EpaAcceptanceIDCleared() {
		_spec.ClearField(equityholderapplication.FieldEpaAcceptanceID, field.TypeUUID)
	}
	if value, ok := _u.mutation.TreasuryHolderID(); ok {
		_spec.SetField(equityholderapplication.FieldTreasuryHolderID, field.TypeUUID, value)
	}
	if _u.mutation.TreasuryHolderIDCleared() {
		_spec.ClearField(equityholderapplication.FieldTreasuryHolderID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(equityholderapplication.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(equityholderapplication.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(equityholderapplication.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &EquityHolderApplication{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{equityholderapplication.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
