// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/auth-api/internal/ent/equityholderapplication"
	"github.com/bengobox/auth-api/internal/ent/predicate"
)

// EquityHolderApplicationDelete is the builder for deleting a EquityHolderApplication entity.
type EquityHolderApplicationDelete struct {
	config
	hooks    []Hook
	mutation *EquityHolderApplicationMutation
}

// Where appends a list predicates to the EquityHolderApplicationDelete builder.
func (_d *EquityHolderApplicationDelete) Where(ps ...predicate.EquityHolderApplication) *EquityHolderApplicationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EquityHolderApplicationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EquityHolderApplicationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EquityHolderApplicationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(equityholderapplication.Table, sqlgraph.NewFieldSpec(equityholderapplication.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EquityHolderApplicationDeleteOne is the builder for deleting a single EquityHolderApplication entity.
type EquityHolderApplicationDeleteOne struct {
	_d *EquityHolderApplicationDelete
}

// Where appends a list predicates to the EquityHolderApplicationDelete builder.
func (_d *EquityHolderApplicationDeleteOne) Where(ps ...predicate.EquityHolderApplication) *EquityHolderApplicationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EquityHolderApplicationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{equityholderapplication.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EquityHolderApplicationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
