// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/auth-api/internal/ent/featureentitlement"
	"github.com/bengobox/auth-api/internal/ent/predicate"
	"github.com/google/uuid"
)

// FeatureEntitlementUpdate is the builder for updating FeatureEntitlement entities.
type FeatureEntitlementUpdate struct {
	config
	hooks    []Hook
	mutation *FeatureEntitlementMutation
}

// Where appends a list predicates to the FeatureEntitlementUpdate builder.
func (_u *FeatureEntitlementUpdate) Where(ps ...predicate.FeatureEntitlement) *FeatureEntitlementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *FeatureEntitlementUpdate) SetTenantID(v uuid.UUID) *FeatureEntitlementUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *FeatureEntitlementUpdate) SetNillableTenantID(v *uuid.UUID) *FeatureEntitlementUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetFeatureCode sets the "feature_code" field.
func (_u *FeatureEntitlementUpdate) SetFeatureCode(v string) *FeatureEntitlementUpdate {
	_u.mutation.SetFeatureCode(v)
	return _u
}

// SetNillableFeatureCode sets the "feature_code" field if the given value is not nil.
func (_u *FeatureEntitlementUpdate) SetNillableFeatureCode(v *string) *FeatureEntitlementUpdate {
	if v != nil {
		_u.SetFeatureCode(*v)
	}
	return _u
}

// SetLimitJSON sets the "limit_json" field.
func (_u *FeatureEntitlementUpdate) SetLimitJSON(v map[string]interface{}) *FeatureEntitlementUpdate {
	_u.mutation.SetLimitJSON(v)
	return _u
}

// ClearLimitJSON clears the value of the "limit_json" field.
func (_u *FeatureEntitlementUpdate) ClearLimitJSON() *FeatureEntitlementUpdate {
	_u.mutation.ClearLimitJSON()
	return _u
}

// SetPlanSource sets the "plan_source" field.
func (_u *FeatureEntitlementUpdate) SetPlanSource(v string) *FeatureEntitlementUpdate {
	_u.mutation.SetPlanSource(v)
	return _u
}

// SetNillablePlanSource sets the "plan_source" field if the given value is not nil.
func (_u *FeatureEntitlementUpdate) SetNillablePlanSource(v *string) *FeatureEntitlementUpdate {
	if v != nil {
		_u.SetPlanSource(*v)
	}
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *FeatureEntitlementUpdate) SetSyncedAt(v time.Time) *FeatureEntitlementUpdate {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *FeatureEntitlementUpdate) SetNillableSyncedAt(v *time.Time) *FeatureEntitlementUpdate {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (_u *FeatureEntitlementUpdate) ClearSyncedAt() *FeatureEntitlementUpdate {
	_u.mutation.ClearSyncedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FeatureEntitlementUpdate) SetUpdatedAt(v time.Time) *FeatureEntitlementUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FeatureEntitlementMutation object of the builder.
func (_u *FeatureEntitlementUpdate) Mutation() *FeatureEntitlementMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FeatureEntitlementUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FeatureEntitlementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FeatureEntitlementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FeatureEntitlementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FeatureEntitlementUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := featureentitlement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FeatureEntitlementUpdate) check() error {
	if v, ok := _u.mutation.FeatureCode(); ok {
		if err := featureentitlement.FeatureCodeValidator(v); err != nil {
			return &ValidationError{Name: "feature_code", err: fmt.Errorf(`ent: validator failed for field "FeatureEntitlement.feature_code": %w`, err)}
		}
	}
	return nil
}

func (_u *FeatureEntitlementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(featureentitlement.Table, featureentitlement.Columns, sqlgraph.NewFieldSpec(featureentitlement.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(featureentitlement.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.FeatureCode(); ok {
		_spec.SetField(featureentitlement.FieldFeatureCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.LimitJSON(); ok {
		_spec.SetField(featureentitlement.FieldLimitJSON, field.TypeJSON, value)
	}
	if _u.mutation.LimitJSONCleared() {
		_spec.ClearField(featureentitlement.FieldLimitJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.PlanSource(); ok {
		_spec.SetField(featureentitlement.FieldPlanSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(featureentitlement.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SyncedAtCleared() {
		_spec.ClearField(featureentitlement.FieldSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(featureentitlement.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{featureentitlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FeatureEntitlementUpdateOne is the builder for updating a single FeatureEntitlement entity.
type FeatureEntitlementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FeatureEntitlementMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *FeatureEntitlementUpdateOne) SetTenantID(v uuid.UUID) *FeatureEntitlementUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *FeatureEntitlementUpdateOne) SetNillableTenantID(v *uuid.UUID) *FeatureEntitlementUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetFeatureCode sets the "feature_code" field.
func (_u *FeatureEntitlementUpdateOne) SetFeatureCode(v string) *FeatureEntitlementUpdateOne {
	_u.mutation.SetFeatureCode(v)
	return _u
}

// SetNillableFeatureCode sets the "feature_code" field if the given value is not nil.
func (_u *FeatureEntitlementUpdateOne) SetNillableFeatureCode(v *string) *FeatureEntitlementUpdateOne {
	if v != nil {
		_u.SetFeatureCode(*v)
	}
	return _u
}

// SetLimitJSON sets the "limit_json" field.
func (_u *FeatureEntitlementUpdateOne) SetLimitJSON(v map[string]interface{}) *FeatureEntitlementUpdateOne {
	_u.mutation.SetLimitJSON(v)
	return _u
}

// ClearLimitJSON clears the value of the "limit_json" field.
func (_u *FeatureEntitlementUpdateOne) ClearLimitJSON() *FeatureEntitlementUpdateOne {
	_u.mutation.ClearLimitJSON()
	return _u
}

// SetPlanSource sets the "plan_source" field.
func (_u *FeatureEntitlementUpdateOne) SetPlanSource(v string) *FeatureEntitlementUpdateOne {
	_u.mutation.SetPlanSource(v)
	return _u
}

// SetNillablePlanSource sets the "plan_source" field if the given value is not nil.
func (_u *FeatureEntitlementUpdateOne) SetNillablePlanSource(v *string) *FeatureEntitlementUpdateOne {
	if v != nil {
		_u.SetPlanSource(*v)
	}
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *FeatureEntitlementUpdateOne) SetSyncedAt(v time.Time) *FeatureEntitlementUpdateOne {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *FeatureEntitlementUpdateOne) SetNillableSyncedAt(v *time.Time) *FeatureEntitlementUpdateOne {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (_u *FeatureEntitlementUpdateOne) ClearSyncedAt() *FeatureEntitlementUpdateOne {
	_u.mutation.ClearSyncedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FeatureEntitlementUpdateOne) SetUpdatedAt(v time.Time) *FeatureEntitlementUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FeatureEntitlementMutation object of the builder.
func (_u *FeatureEntitlementUpdateOne) Mutation() *FeatureEntitlementMutation {
	return _u.mutation
}

// Where appends a list predicates to the FeatureEntitlementUpdate builder.
func (_u *FeatureEntitlementUpdateOne) Where(ps ...predicate.FeatureEntitlement) *FeatureEntitlementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FeatureEntitlementUpdateOne) Select(field string, fields ...string) *FeatureEntitlementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FeatureEntitlement entity.
func (_u *FeatureEntitlementUpdateOne) Save(ctx context.Context) (*FeatureEntitlement, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FeatureEntitlementUpdateOne) SaveX(ctx context.Context) *FeatureEntitlement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FeatureEntitlementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FeatureEntitlementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FeatureEntitlementUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := featureentitlement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FeatureEntitlementUpdateOne) check() error {
	if v, ok := _u.mutation.FeatureCode(); ok {
		if err := featureentitlement.FeatureCodeValidator(v); err != nil {
			return &ValidationError{Name: "feature_code", err: fmt.Errorf(`ent: validator failed for field "FeatureEntitlement.feature_code": %w`, err)}
		}
	}
	return nil
}

func (_u *FeatureEntitlementUpdateOne) sqlSave(ctx context.Context) (_node *FeatureEntitlement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(featureentitlement.Table, featureentitlement.Columns, sqlgraph.NewFieldSpec(featureentitlement.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FeatureEntitlement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, featureentitlement.FieldID)
		for _, f := range fields {
			if !featureentitlement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != featureentitlement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(featureentitlement.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.FeatureCode(); ok {
		_spec.SetField(featureentitlement.FieldFeatureCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.LimitJSON(); ok {
		_spec.SetField(featureentitlement.FieldLimitJSON, field.TypeJSON, value)
	}
	if _u.mutation.LimitJSONCleared() {
		_spec.ClearField(featureentitlement.FieldLimitJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.PlanSource(); ok {
		_spec.SetField(featureentitlement.FieldPlanSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(featureentitlement.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SyncedAtCleared() {
		_spec.ClearField(featureentitlement.FieldSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(featureentitlement.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &FeatureEntitlement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{featureentitlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
