// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/auth-api/internal/ent/legaldocument"
	"github.com/bengobox/auth-api/internal/ent/predicate"
)

// LegalDocumentDelete is the builder for deleting a LegalDocument entity.
type LegalDocumentDelete struct {
	config
	hooks    []Hook
	mutation *LegalDocumentMutation
}

// Where appends a list predicates to the LegalDocumentDelete builder.
func (_d *LegalDocumentDelete) Where(ps ...predicate.LegalDocument) *LegalDocumentDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *LegalDocumentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LegalDocumentDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *LegalDocumentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(legaldocument.Table, sqlgraph.NewFieldSpec(legaldocument.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// LegalDocumentDeleteOne is the builder for deleting a single LegalDocument entity.
type LegalDocumentDeleteOne struct {
	_d *LegalDocumentDelete
}

// Where appends a list predicates to the LegalDocumentDelete builder.
func (_d *LegalDocumentDeleteOne) Where(ps ...predicate.LegalDocument) *LegalDocumentDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *LegalDocumentDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{legaldocument.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LegalDocumentDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
