// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/auth-service/internal/ent/mfatotpsecret"
	"github.com/bengobox/auth-service/internal/ent/predicate"
	"github.com/bengobox/auth-service/internal/ent/user"
	"github.com/google/uuid"
)

// MFATOTPSecretUpdate is the builder for updating MFATOTPSecret entities.
type MFATOTPSecretUpdate struct {
	config
	hooks    []Hook
	mutation *MFATOTPSecretMutation
}

// Where appends a list predicates to the MFATOTPSecretUpdate builder.
func (_u *MFATOTPSecretUpdate) Where(ps ...predicate.MFATOTPSecret) *MFATOTPSecretUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MFATOTPSecretUpdate) SetUserID(v uuid.UUID) *MFATOTPSecretUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MFATOTPSecretUpdate) SetNillableUserID(v *uuid.UUID) *MFATOTPSecretUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSecret sets the "secret" field.
func (_u *MFATOTPSecretUpdate) SetSecret(v string) *MFATOTPSecretUpdate {
	_u.mutation.SetSecret(v)
	return _u
}

// SetNillableSecret sets the "secret" field if the given value is not nil.
func (_u *MFATOTPSecretUpdate) SetNillableSecret(v *string) *MFATOTPSecretUpdate {
	if v != nil {
		_u.SetSecret(*v)
	}
	return _u
}

// SetDigits sets the "digits" field.
func (_u *MFATOTPSecretUpdate) SetDigits(v int) *MFATOTPSecretUpdate {
	_u.mutation.ResetDigits()
	_u.mutation.SetDigits(v)
	return _u
}

// SetNillableDigits sets the "digits" field if the given value is not nil.
func (_u *MFATOTPSecretUpdate) SetNillableDigits(v *int) *MFATOTPSecretUpdate {
	if v != nil {
		_u.SetDigits(*v)
	}
	return _u
}

// AddDigits adds value to the "digits" field.
func (_u *MFATOTPSecretUpdate) AddDigits(v int) *MFATOTPSecretUpdate {
	_u.mutation.AddDigits(v)
	return _u
}

// SetPeriod sets the "period" field.
func (_u *MFATOTPSecretUpdate) SetPeriod(v int) *MFATOTPSecretUpdate {
	_u.mutation.ResetPeriod()
	_u.mutation.SetPeriod(v)
	return _u
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_u *MFATOTPSecretUpdate) SetNillablePeriod(v *int) *MFATOTPSecretUpdate {
	if v != nil {
		_u.SetPeriod(*v)
	}
	return _u
}

// AddPeriod adds value to the "period" field.
func (_u *MFATOTPSecretUpdate) AddPeriod(v int) *MFATOTPSecretUpdate {
	_u.mutation.AddPeriod(v)
	return _u
}

// SetEnabledAt sets the "enabled_at" field.
func (_u *MFATOTPSecretUpdate) SetEnabledAt(v time.Time) *MFATOTPSecretUpdate {
	_u.mutation.SetEnabledAt(v)
	return _u
}

// SetNillableEnabledAt sets the "enabled_at" field if the given value is not nil.
func (_u *MFATOTPSecretUpdate) SetNillableEnabledAt(v *time.Time) *MFATOTPSecretUpdate {
	if v != nil {
		_u.SetEnabledAt(*v)
	}
	return _u
}

// ClearEnabledAt clears the value of the "enabled_at" field.
func (_u *MFATOTPSecretUpdate) ClearEnabledAt() *MFATOTPSecretUpdate {
	_u.mutation.ClearEnabledAt()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *MFATOTPSecretUpdate) SetLastUsedAt(v time.Time) *MFATOTPSecretUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *MFATOTPSecretUpdate) SetNillableLastUsedAt(v *time.Time) *MFATOTPSecretUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *MFATOTPSecretUpdate) ClearLastUsedAt() *MFATOTPSecretUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *MFATOTPSecretUpdate) SetUser(v *User) *MFATOTPSecretUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the MFATOTPSecretMutation object of the builder.
func (_u *MFATOTPSecretUpdate) Mutation() *MFATOTPSecretMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MFATOTPSecretUpdate) ClearUser() *MFATOTPSecretUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MFATOTPSecretUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MFATOTPSecretUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MFATOTPSecretUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MFATOTPSecretUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MFATOTPSecretUpdate) check() error {
	if v, ok := _u.mutation.Secret(); ok {
		if err := mfatotpsecret.SecretValidator(v); err != nil {
			return &ValidationError{Name: "secret", err: fmt.Errorf(`ent: validator failed for field "MFATOTPSecret.secret": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MFATOTPSecret.user"`)
	}
	return nil
}

func (_u *MFATOTPSecretUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mfatotpsecret.Table, mfatotpsecret.Columns, sqlgraph.NewFieldSpec(mfatotpsecret.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Secret(); ok {
		_spec.SetField(mfatotpsecret.FieldSecret, field.TypeString, value)
	}
	if value, ok := _u.mutation.Digits(); ok {
		_spec.SetField(mfatotpsecret.FieldDigits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDigits(); ok {
		_spec.AddField(mfatotpsecret.FieldDigits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Period(); ok {
		_spec.SetField(mfatotpsecret.FieldPeriod, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPeriod(); ok {
		_spec.AddField(mfatotpsecret.FieldPeriod, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EnabledAt(); ok {
		_spec.SetField(mfatotpsecret.FieldEnabledAt, field.TypeTime, value)
	}
	if _u.mutation.EnabledAtCleared() {
		_spec.ClearField(mfatotpsecret.FieldEnabledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(mfatotpsecret.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(mfatotpsecret.FieldLastUsedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mfatotpsecret.UserTable,
			Columns: []string{mfatotpsecret.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mfatotpsecret.UserTable,
			Columns: []string{mfatotpsecret.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mfatotpsecret.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MFATOTPSecretUpdateOne is the builder for updating a single MFATOTPSecret entity.
type MFATOTPSecretUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MFATOTPSecretMutation
}

// SetUserID sets the "user_id" field.
func (_u *MFATOTPSecretUpdateOne) SetUserID(v uuid.UUID) *MFATOTPSecretUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MFATOTPSecretUpdateOne) SetNillableUserID(v *uuid.UUID) *MFATOTPSecretUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSecret sets the "secret" field.
func (_u *MFATOTPSecretUpdateOne) SetSecret(v string) *MFATOTPSecretUpdateOne {
	_u.mutation.SetSecret(v)
	return _u
}

// SetNillableSecret sets the "secret" field if the given value is not nil.
func (_u *MFATOTPSecretUpdateOne) SetNillableSecret(v *string) *MFATOTPSecretUpdateOne {
	if v != nil {
		_u.SetSecret(*v)
	}
	return _u
}

// SetDigits sets the "digits" field.
func (_u *MFATOTPSecretUpdateOne) SetDigits(v int) *MFATOTPSecretUpdateOne {
	_u.mutation.ResetDigits()
	_u.mutation.SetDigits(v)
	return _u
}

// SetNillableDigits sets the "digits" field if the given value is not nil.
func (_u *MFATOTPSecretUpdateOne) SetNillableDigits(v *int) *MFATOTPSecretUpdateOne {
	if v != nil {
		_u.SetDigits(*v)
	}
	return _u
}

// AddDigits adds value to the "digits" field.
func (_u *MFATOTPSecretUpdateOne) AddDigits(v int) *MFATOTPSecretUpdateOne {
	_u.mutation.AddDigits(v)
	return _u
}

// SetPeriod sets the "period" field.
func (_u *MFATOTPSecretUpdateOne) SetPeriod(v int) *MFATOTPSecretUpdateOne {
	_u.mutation.ResetPeriod()
	_u.mutation.SetPeriod(v)
	return _u
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_u *MFATOTPSecretUpdateOne) SetNillablePeriod(v *int) *MFATOTPSecretUpdateOne {
	if v != nil {
		_u.SetPeriod(*v)
	}
	return _u
}

// AddPeriod adds value to the "period" field.
func (_u *MFATOTPSecretUpdateOne) AddPeriod(v int) *MFATOTPSecretUpdateOne {
	_u.mutation.AddPeriod(v)
	return _u
}

// SetEnabledAt sets the "enabled_at" field.
func (_u *MFATOTPSecretUpdateOne) SetEnabledAt(v time.Time) *MFATOTPSecretUpdateOne {
	_u.mutation.SetEnabledAt(v)
	return _u
}

// SetNillableEnabledAt sets the "enabled_at" field if the given value is not nil.
func (_u *MFATOTPSecretUpdateOne) SetNillableEnabledAt(v *time.Time) *MFATOTPSecretUpdateOne {
	if v != nil {
		_u.SetEnabledAt(*v)
	}
	return _u
}

// ClearEnabledAt clears the value of the "enabled_at" field.
func (_u *MFATOTPSecretUpdateOne) ClearEnabledAt() *MFATOTPSecretUpdateOne {
	_u.mutation.ClearEnabledAt()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *MFATOTPSecretUpdateOne) SetLastUsedAt(v time.Time) *MFATOTPSecretUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *MFATOTPSecretUpdateOne) SetNillableLastUsedAt(v *time.Time) *MFATOTPSecretUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *MFATOTPSecretUpdateOne) ClearLastUsedAt() *MFATOTPSecretUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *MFATOTPSecretUpdateOne) SetUser(v *User) *MFATOTPSecretUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the MFATOTPSecretMutation object of the builder.
func (_u *MFATOTPSecretUpdateOne) Mutation() *MFATOTPSecretMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MFATOTPSecretUpdateOne) ClearUser() *MFATOTPSecretUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the MFATOTPSecretUpdate builder.
func (_u *MFATOTPSecretUpdateOne) Where(ps ...predicate.MFATOTPSecret) *MFATOTPSecretUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MFATOTPSecretUpdateOne) Select(field string, fields ...string) *MFATOTPSecretUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MFATOTPSecret entity.
func (_u *MFATOTPSecretUpdateOne) Save(ctx context.Context) (*MFATOTPSecret, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MFATOTPSecretUpdateOne) SaveX(ctx context.Context) *MFATOTPSecret {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MFATOTPSecretUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MFATOTPSecretUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MFATOTPSecretUpdateOne) check() error {
	if v, ok := _u.mutation.Secret(); ok {
		if err := mfatotpsecret.SecretValidator(v); err != nil {
			return &ValidationError{Name: "secret", err: fmt.Errorf(`ent: validator failed for field "MFATOTPSecret.secret": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MFATOTPSecret.user"`)
	}
	return nil
}

func (_u *MFATOTPSecretUpdateOne) sqlSave(ctx context.Context) (_node *MFATOTPSecret, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mfatotpsecret.Table, mfatotpsecret.Columns, sqlgraph.NewFieldSpec(mfatotpsecret.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MFATOTPSecret.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mfatotpsecret.FieldID)
		for _, f := range fields {
			if !mfatotpsecret.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mfatotpsecret.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Secret(); ok {
		_spec.SetField(mfatotpsecret.FieldSecret, field.TypeString, value)
	}
	if value, ok := _u.mutation.Digits(); ok {
		_spec.SetField(mfatotpsecret.FieldDigits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDigits(); ok {
		_spec.AddField(mfatotpsecret.FieldDigits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Period(); ok {
		_spec.SetField(mfatotpsecret.FieldPeriod, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPeriod(); ok {
		_spec.AddField(mfatotpsecret.FieldPeriod, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EnabledAt(); ok {
		_spec.SetField(mfatotpsecret.FieldEnabledAt, field.TypeTime, value)
	}
	if _u.mutation.EnabledAtCleared() {
		_spec.ClearField(mfatotpsecret.FieldEnabledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(mfatotpsecret.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(mfatotpsecret.FieldLastUsedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mfatotpsecret.UserTable,
			Columns: []string{mfatotpsecret.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mfatotpsecret.UserTable,
			Columns: []string{mfatotpsecret.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MFATOTPSecret{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mfatotpsecret.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
