// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/auth-service/internal/ent/mfatotpsecret"
	"github.com/bengobox/auth-service/internal/ent/user"
	"github.com/google/uuid"
)

// MFATOTPSecretCreate is the builder for creating a MFATOTPSecret entity.
type MFATOTPSecretCreate struct {
	config
	mutation *MFATOTPSecretMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *MFATOTPSecretCreate) SetUserID(v uuid.UUID) *MFATOTPSecretCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSecret sets the "secret" field.
func (_c *MFATOTPSecretCreate) SetSecret(v string) *MFATOTPSecretCreate {
	_c.mutation.SetSecret(v)
	return _c
}

// SetDigits sets the "digits" field.
func (_c *MFATOTPSecretCreate) SetDigits(v int) *MFATOTPSecretCreate {
	_c.mutation.SetDigits(v)
	return _c
}

// SetNillableDigits sets the "digits" field if the given value is not nil.
func (_c *MFATOTPSecretCreate) SetNillableDigits(v *int) *MFATOTPSecretCreate {
	if v != nil {
		_c.SetDigits(*v)
	}
	return _c
}

// SetPeriod sets the "period" field.
func (_c *MFATOTPSecretCreate) SetPeriod(v int) *MFATOTPSecretCreate {
	_c.mutation.SetPeriod(v)
	return _c
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_c *MFATOTPSecretCreate) SetNillablePeriod(v *int) *MFATOTPSecretCreate {
	if v != nil {
		_c.SetPeriod(*v)
	}
	return _c
}

// SetEnabledAt sets the "enabled_at" field.
func (_c *MFATOTPSecretCreate) SetEnabledAt(v time.Time) *MFATOTPSecretCreate {
	_c.mutation.SetEnabledAt(v)
	return _c
}

// SetNillableEnabledAt sets the "enabled_at" field if the given value is not nil.
func (_c *MFATOTPSecretCreate) SetNillableEnabledAt(v *time.Time) *MFATOTPSecretCreate {
	if v != nil {
		_c.SetEnabledAt(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *MFATOTPSecretCreate) SetLastUsedAt(v time.Time) *MFATOTPSecretCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *MFATOTPSecretCreate) SetNillableLastUsedAt(v *time.Time) *MFATOTPSecretCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MFATOTPSecretCreate) SetCreatedAt(v time.Time) *MFATOTPSecretCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MFATOTPSecretCreate) SetNillableCreatedAt(v *time.Time) *MFATOTPSecretCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MFATOTPSecretCreate) SetID(v uuid.UUID) *MFATOTPSecretCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MFATOTPSecretCreate) SetNillableID(v *uuid.UUID) *MFATOTPSecretCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *MFATOTPSecretCreate) SetUser(v *User) *MFATOTPSecretCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the MFATOTPSecretMutation object of the builder.
func (_c *MFATOTPSecretCreate) Mutation() *MFATOTPSecretMutation {
	return _c.mutation
}

// Save creates the MFATOTPSecret in the database.
func (_c *MFATOTPSecretCreate) Save(ctx context.Context) (*MFATOTPSecret, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MFATOTPSecretCreate) SaveX(ctx context.Context) *MFATOTPSecret {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MFATOTPSecretCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MFATOTPSecretCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MFATOTPSecretCreate) defaults() {
	if _, ok := _c.mutation.Digits(); !ok {
		v := mfatotpsecret.DefaultDigits
		_c.mutation.SetDigits(v)
	}
	if _, ok := _c.mutation.Period(); !ok {
		v := mfatotpsecret.DefaultPeriod
		_c.mutation.SetPeriod(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mfatotpsecret.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := mfatotpsecret.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MFATOTPSecretCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "MFATOTPSecret.user_id"`)}
	}
	if _, ok := _c.mutation.Secret(); !ok {
		return &ValidationError{Name: "secret", err: errors.New(`ent: missing required field "MFATOTPSecret.secret"`)}
	}
	if v, ok := _c.mutation.Secret(); ok {
		if err := mfatotpsecret.SecretValidator(v); err != nil {
			return &ValidationError{Name: "secret", err: fmt.Errorf(`ent: validator failed for field "MFATOTPSecret.secret": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Digits(); !ok {
		return &ValidationError{Name: "digits", err: errors.New(`ent: missing required field "MFATOTPSecret.digits"`)}
	}
	if _, ok := _c.mutation.Period(); !ok {
		return &ValidationError{Name: "period", err: errors.New(`ent: missing required field "MFATOTPSecret.period"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MFATOTPSecret.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "MFATOTPSecret.user"`)}
	}
	return nil
}

func (_c *MFATOTPSecretCreate) sqlSave(ctx context.Context) (*MFATOTPSecret, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MFATOTPSecretCreate) createSpec() (*MFATOTPSecret, *sqlgraph.CreateSpec) {
	var (
		_node = &MFATOTPSecret{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mfatotpsecret.Table, sqlgraph.NewFieldSpec(mfatotpsecret.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Secret(); ok {
		_spec.SetField(mfatotpsecret.FieldSecret, field.TypeString, value)
		_node.Secret = value
	}
	if value, ok := _c.mutation.Digits(); ok {
		_spec.SetField(mfatotpsecret.FieldDigits, field.TypeInt, value)
		_node.Digits = value
	}
	if value, ok := _c.mutation.Period(); ok {
		_spec.SetField(mfatotpsecret.FieldPeriod, field.TypeInt, value)
		_node.Period = value
	}
	if value, ok := _c.mutation.EnabledAt(); ok {
		_spec.SetField(mfatotpsecret.FieldEnabledAt, field.TypeTime, value)
		_node.EnabledAt = value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(mfatotpsecret.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mfatotpsecret.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mfatotpsecret.UserTable,
			Columns: []string{mfatotpsecret.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MFATOTPSecretCreateBulk is the builder for creating many MFATOTPSecret entities in bulk.
type MFATOTPSecretCreateBulk struct {
	config
	err      error
	builders []*MFATOTPSecretCreate
}

// Save creates the MFATOTPSecret entities in the database.
func (_c *MFATOTPSecretCreateBulk) Save(ctx context.Context) ([]*MFATOTPSecret, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MFATOTPSecret, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MFATOTPSecretMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MFATOTPSecretCreateBulk) SaveX(ctx context.Context) []*MFATOTPSecret {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MFATOTPSecretCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MFATOTPSecretCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
