// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/auth-api/internal/ent/passwordpolicy"
	"github.com/google/uuid"
)

// PasswordPolicyCreate is the builder for creating a PasswordPolicy entity.
type PasswordPolicyCreate struct {
	config
	mutation *PasswordPolicyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *PasswordPolicyCreate) SetTenantID(v uuid.UUID) *PasswordPolicyCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *PasswordPolicyCreate) SetNillableTenantID(v *uuid.UUID) *PasswordPolicyCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetMinLength sets the "min_length" field.
func (_c *PasswordPolicyCreate) SetMinLength(v int) *PasswordPolicyCreate {
	_c.mutation.SetMinLength(v)
	return _c
}

// SetNillableMinLength sets the "min_length" field if the given value is not nil.
func (_c *PasswordPolicyCreate) SetNillableMinLength(v *int) *PasswordPolicyCreate {
	if v != nil {
		_c.SetMinLength(*v)
	}
	return _c
}

// SetRequireUpper sets the "require_upper" field.
func (_c *PasswordPolicyCreate) SetRequireUpper(v bool) *PasswordPolicyCreate {
	_c.mutation.SetRequireUpper(v)
	return _c
}

// SetNillableRequireUpper sets the "require_upper" field if the given value is not nil.
func (_c *PasswordPolicyCreate) SetNillableRequireUpper(v *bool) *PasswordPolicyCreate {
	if v != nil {
		_c.SetRequireUpper(*v)
	}
	return _c
}

// SetRequireLower sets the "require_lower" field.
func (_c *PasswordPolicyCreate) SetRequireLower(v bool) *PasswordPolicyCreate {
	_c.mutation.SetRequireLower(v)
	return _c
}

// SetNillableRequireLower sets the "require_lower" field if the given value is not nil.
func (_c *PasswordPolicyCreate) SetNillableRequireLower(v *bool) *PasswordPolicyCreate {
	if v != nil {
		_c.SetRequireLower(*v)
	}
	return _c
}

// SetRequireDigit sets the "require_digit" field.
func (_c *PasswordPolicyCreate) SetRequireDigit(v bool) *PasswordPolicyCreate {
	_c.mutation.SetRequireDigit(v)
	return _c
}

// SetNillableRequireDigit sets the "require_digit" field if the given value is not nil.
func (_c *PasswordPolicyCreate) SetNillableRequireDigit(v *bool) *PasswordPolicyCreate {
	if v != nil {
		_c.SetRequireDigit(*v)
	}
	return _c
}

// SetRequireSymbol sets the "require_symbol" field.
func (_c *PasswordPolicyCreate) SetRequireSymbol(v bool) *PasswordPolicyCreate {
	_c.mutation.SetRequireSymbol(v)
	return _c
}

// SetNillableRequireSymbol sets the "require_symbol" field if the given value is not nil.
func (_c *PasswordPolicyCreate) SetNillableRequireSymbol(v *bool) *PasswordPolicyCreate {
	if v != nil {
		_c.SetRequireSymbol(*v)
	}
	return _c
}

// SetExpiryDays sets the "expiry_days" field.
func (_c *PasswordPolicyCreate) SetExpiryDays(v int) *PasswordPolicyCreate {
	_c.mutation.SetExpiryDays(v)
	return _c
}

// SetNillableExpiryDays sets the "expiry_days" field if the given value is not nil.
func (_c *PasswordPolicyCreate) SetNillableExpiryDays(v *int) *PasswordPolicyCreate {
	if v != nil {
		_c.SetExpiryDays(*v)
	}
	return _c
}

// SetReuseBlockCount sets the "reuse_block_count" field.
func (_c *PasswordPolicyCreate) SetReuseBlockCount(v int) *PasswordPolicyCreate {
	_c.mutation.SetReuseBlockCount(v)
	return _c
}

// SetNillableReuseBlockCount sets the "reuse_block_count" field if the given value is not nil.
func (_c *PasswordPolicyCreate) SetNillableReuseBlockCount(v *int) *PasswordPolicyCreate {
	if v != nil {
		_c.SetReuseBlockCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PasswordPolicyCreate) SetCreatedAt(v time.Time) *PasswordPolicyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PasswordPolicyCreate) SetNillableCreatedAt(v *time.Time) *PasswordPolicyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PasswordPolicyCreate) SetUpdatedAt(v time.Time) *PasswordPolicyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PasswordPolicyCreate) SetNillableUpdatedAt(v *time.Time) *PasswordPolicyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PasswordPolicyCreate) SetID(v uuid.UUID) *PasswordPolicyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PasswordPolicyCreate) SetNillableID(v *uuid.UUID) *PasswordPolicyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PasswordPolicyMutation object of the builder.
func (_c *PasswordPolicyCreate) Mutation() *PasswordPolicyMutation {
	return _c.mutation
}

// Save creates the PasswordPolicy in the database.
func (_c *PasswordPolicyCreate) Save(ctx context.Context) (*PasswordPolicy, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PasswordPolicyCreate) SaveX(ctx context.Context) *PasswordPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PasswordPolicyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PasswordPolicyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PasswordPolicyCreate) defaults() {
	if _, ok := _c.mutation.MinLength(); !ok {
		v := passwordpolicy.DefaultMinLength
		_c.mutation.SetMinLength(v)
	}
	if _, ok := _c.mutation.RequireUpper(); !ok {
		v := passwordpolicy.DefaultRequireUpper
		_c.mutation.SetRequireUpper(v)
	}
	if _, ok := _c.mutation.RequireLower(); !ok {
		v := passwordpolicy.DefaultRequireLower
		_c.mutation.SetRequireLower(v)
	}
	if _, ok := _c.mutation.RequireDigit(); !ok {
		v := passwordpolicy.DefaultRequireDigit
		_c.mutation.SetRequireDigit(v)
	}
	if _, ok := _c.mutation.RequireSymbol(); !ok {
		v := passwordpolicy.DefaultRequireSymbol
		_c.mutation.SetRequireSymbol(v)
	}
	if _, ok := _c.mutation.ExpiryDays(); !ok {
		v := passwordpolicy.DefaultExpiryDays
		_c.mutation.SetExpiryDays(v)
	}
	if _, ok := _c.mutation.ReuseBlockCount(); !ok {
		v := passwordpolicy.DefaultReuseBlockCount
		_c.mutation.SetReuseBlockCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := passwordpolicy.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := passwordpolicy.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := passwordpolicy.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PasswordPolicyCreate) check() error {
	if _, ok := _c.mutation.MinLength(); !ok {
		return &ValidationError{Name: "min_length", err: errors.New(`ent: missing required field "PasswordPolicy.min_length"`)}
	}
	if _, ok := _c.mutation.RequireUpper(); !ok {
		return &ValidationError{Name: "require_upper", err: errors.New(`ent: missing required field "PasswordPolicy.require_upper"`)}
	}
	if _, ok := _c.mutation.RequireLower(); !ok {
		return &ValidationError{Name: "require_lower", err: errors.New(`ent: missing required field "PasswordPolicy.require_lower"`)}
	}
	if _, ok := _c.mutation.RequireDigit(); !ok {
		return &ValidationError{Name: "require_digit", err: errors.New(`ent: missing required field "PasswordPolicy.require_digit"`)}
	}
	if _, ok := _c.mutation.RequireSymbol(); !ok {
		return &ValidationError{Name: "require_symbol", err: errors.New(`ent: missing required field "PasswordPolicy.require_symbol"`)}
	}
	if _, ok := _c.mutation.ExpiryDays(); !ok {
		return &ValidationError{Name: "expiry_days", err: errors.New(`ent: missing required field "PasswordPolicy.expiry_days"`)}
	}
	if _, ok := _c.mutation.ReuseBlockCount(); !ok {
		return &ValidationError{Name: "reuse_block_count", err: errors.New(`ent: missing required field "PasswordPolicy.reuse_block_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PasswordPolicy.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PasswordPolicy.updated_at"`)}
	}
	return nil
}

func (_c *PasswordPolicyCreate) sqlSave(ctx context.Context) (*PasswordPolicy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PasswordPolicyCreate) createSpec() (*PasswordPolicy, *sqlgraph.CreateSpec) {
	var (
		_node = &PasswordPolicy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(passwordpolicy.Table, sqlgraph.NewFieldSpec(passwordpolicy.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(passwordpolicy.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.MinLength(); ok {
		_spec.SetField(passwordpolicy.FieldMinLength, field.TypeInt, value)
		_node.MinLength = value
	}
	if value, ok := _c.mutation.RequireUpper(); ok {
		_spec.SetField(passwordpolicy.FieldRequireUpper, field.TypeBool, value)
		_node.RequireUpper = value
	}
	if value, ok := _c.mutation.RequireLower(); ok {
		_spec.SetField(passwordpolicy.FieldRequireLower, field.TypeBool, value)
		_node.RequireLower = value
	}
	if value, ok := _c.mutation.RequireDigit(); ok {
		_spec.SetField(passwordpolicy.FieldRequireDigit, field.TypeBool, value)
		_node.RequireDigit = value
	}
	if value, ok := _c.mutation.RequireSymbol(); ok {
		_spec.SetField(passwordpolicy.FieldRequireSymbol, field.TypeBool, value)
		_node.RequireSymbol = value
	}
	if value, ok := _c.mutation.ExpiryDays(); ok {
		_spec.SetField(passwordpolicy.FieldExpiryDays, field.TypeInt, value)
		_node.ExpiryDays = value
	}
	if value, ok := _c.mutation.ReuseBlockCount(); ok {
		_spec.SetField(passwordpolicy.FieldReuseBlockCount, field.TypeInt, value)
		_node.ReuseBlockCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(passwordpolicy.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(passwordpolicy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PasswordPolicy.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PasswordPolicyUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *PasswordPolicyCreate) OnConflict(opts ...sql.ConflictOption) *PasswordPolicyUpsertOne {
	_c.conflict = opts
	return &PasswordPolicyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PasswordPolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PasswordPolicyCreate) OnConflictColumns(columns ...string) *PasswordPolicyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PasswordPolicyUpsertOne{
		create: _c,
	}
}

type (
	// PasswordPolicyUpsertOne is the builder for "upsert"-ing
	//  one PasswordPolicy node.
	PasswordPolicyUpsertOne struct {
		create *PasswordPolicyCreate
	}

	// PasswordPolicyUpsert is the "OnConflict" setter.
	PasswordPolicyUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *PasswordPolicyUpsert) SetTenantID(v uuid.UUID) *PasswordPolicyUpsert {
	u.Set(passwordpolicy.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *PasswordPolicyUpsert) UpdateTenantID() *PasswordPolicyUpsert {
	u.SetExcluded(passwordpolicy.FieldTenantID)
	return u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *PasswordPolicyUpsert) ClearTenantID() *PasswordPolicyUpsert {
	u.SetNull(passwordpolicy.FieldTenantID)
	return u
}

// SetMinLength sets the "min_length" field.
func (u *PasswordPolicyUpsert) SetMinLength(v int) *PasswordPolicyUpsert {
	u.Set(passwordpolicy.FieldMinLength, v)
	return u
}

// UpdateMinLength sets the "min_length" field to the value that was provided on create.
func (u *PasswordPolicyUpsert) UpdateMinLength() *PasswordPolicyUpsert {
	u.SetExcluded(passwordpolicy.FieldMinLength)
	return u
}

// AddMinLength adds v to the "min_length" field.
func (u *PasswordPolicyUpsert) AddMinLength(v int) *PasswordPolicyUpsert {
	u.Add(passwordpolicy.FieldMinLength, v)
	return u
}

// SetRequireUpper sets the "require_upper" field.
func (u *PasswordPolicyUpsert) SetRequireUpper(v bool) *PasswordPolicyUpsert {
	u.Set(passwordpolicy.FieldRequireUpper, v)
	return u
}

// UpdateRequireUpper sets the "require_upper" field to the value that was provided on create.
func (u *PasswordPolicyUpsert) UpdateRequireUpper() *PasswordPolicyUpsert {
	u.SetExcluded(passwordpolicy.FieldRequireUpper)
	return u
}

// SetRequireLower sets the "require_lower" field.
func (u *PasswordPolicyUpsert) SetRequireLower(v bool) *PasswordPolicyUpsert {
	u.Set(passwordpolicy.FieldRequireLower, v)
	return u
}

// UpdateRequireLower sets the "require_lower" field to the value that was provided on create.
func (u *PasswordPolicyUpsert) UpdateRequireLower() *PasswordPolicyUpsert {
	u.SetExcluded(passwordpolicy.FieldRequireLower)
	return u
}

// SetRequireDigit sets the "require_digit" field.
func (u *PasswordPolicyUpsert) SetRequireDigit(v bool) *PasswordPolicyUpsert {
	u.Set(passwordpolicy.FieldRequireDigit, v)
	return u
}

// UpdateRequireDigit sets the "require_digit" field to the value that was provided on create.
func (u *PasswordPolicyUpsert) UpdateRequireDigit() *PasswordPolicyUpsert {
	u.SetExcluded(passwordpolicy.FieldRequireDigit)
	return u
}

// SetRequireSymbol sets the "require_symbol" field.
func (u *PasswordPolicyUpsert) SetRequireSymbol(v bool) *PasswordPolicyUpsert {
	u.Set(passwordpolicy.FieldRequireSymbol, v)
	return u
}

// UpdateRequireSymbol sets the "require_symbol" field to the value that was provided on create.
func (u *PasswordPolicyUpsert) UpdateRequireSymbol() *PasswordPolicyUpsert {
	u.SetExcluded(passwordpolicy.FieldRequireSymbol)
	return u
}

// SetExpiryDays sets the "expiry_days" field.
func (u *PasswordPolicyUpsert) SetExpiryDays(v int) *PasswordPolicyUpsert {
	u.Set(passwordpolicy.FieldExpiryDays, v)
	return u
}

// UpdateExpiryDays sets the "expiry_days" field to the value that was provided on create.
func (u *PasswordPolicyUpsert) UpdateExpiryDays() *PasswordPolicyUpsert {
	u.SetExcluded(passwordpolicy.FieldExpiryDays)
	return u
}

// AddExpiryDays adds v to the "expiry_days" field.
func (u *PasswordPolicyUpsert) AddExpiryDays(v int) *PasswordPolicyUpsert {
	u.Add(passwordpolicy.FieldExpiryDays, v)
	return u
}

// SetReuseBlockCount sets the "reuse_block_count" field.
func (u *PasswordPolicyUpsert) SetReuseBlockCount(v int) *PasswordPolicyUpsert {
	u.Set(passwordpolicy.FieldReuseBlockCount, v)
	return u
}

// UpdateReuseBlockCount sets the "reuse_block_count" field to the value that was provided on create.
func (u *PasswordPolicyUpsert) UpdateReuseBlockCount() *PasswordPolicyUpsert {
	u.SetExcluded(passwordpolicy.FieldReuseBlockCount)
	return u
}

// AddReuseBlockCount adds v to the "reuse_block_count" field.
func (u *PasswordPolicyUpsert) AddReuseBlockCount(v int) *PasswordPolicyUpsert {
	u.Add(passwordpolicy.FieldReuseBlockCount, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PasswordPolicyUpsert) SetUpdatedAt(v time.Time) *PasswordPolicyUpsert {
	u.Set(passwordpolicy.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PasswordPolicyUpsert) UpdateUpdatedAt() *PasswordPolicyUpsert {
	u.SetExcluded(passwordpolicy.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PasswordPolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(passwordpolicy.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PasswordPolicyUpsertOne) UpdateNewValues() *PasswordPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(passwordpolicy.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(passwordpolicy.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PasswordPolicy.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PasswordPolicyUpsertOne) Ignore() *PasswordPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PasswordPolicyUpsertOne) DoNothing() *PasswordPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PasswordPolicyCreate.OnConflict
// documentation for more info.
func (u *PasswordPolicyUpsertOne) Update(set func(*PasswordPolicyUpsert)) *PasswordPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PasswordPolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *PasswordPolicyUpsertOne) SetTenantID(v uuid.UUID) *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *PasswordPolicyUpsertOne) UpdateTenantID() *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.UpdateTenantID()
	})
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *PasswordPolicyUpsertOne) ClearTenantID() *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.ClearTenantID()
	})
}

// SetMinLength sets the "min_length" field.
func (u *PasswordPolicyUpsertOne) SetMinLength(v int) *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.SetMinLength(v)
	})
}

// AddMinLength adds v to the "min_length" field.
func (u *PasswordPolicyUpsertOne) AddMinLength(v int) *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.AddMinLength(v)
	})
}

// UpdateMinLength sets the "min_length" field to the value that was provided on create.
func (u *PasswordPolicyUpsertOne) UpdateMinLength() *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.UpdateMinLength()
	})
}

// SetRequireUpper sets the "require_upper" field.
func (u *PasswordPolicyUpsertOne) SetRequireUpper(v bool) *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.SetRequireUpper(v)
	})
}

// UpdateRequireUpper sets the "require_upper" field to the value that was provided on create.
func (u *PasswordPolicyUpsertOne) UpdateRequireUpper() *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.UpdateRequireUpper()
	})
}

// SetRequireLower sets the "require_lower" field.
func (u *PasswordPolicyUpsertOne) SetRequireLower(v bool) *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.SetRequireLower(v)
	})
}

// UpdateRequireLower sets the "require_lower" field to the value that was provided on create.
func (u *PasswordPolicyUpsertOne) UpdateRequireLower() *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.UpdateRequireLower()
	})
}

// SetRequireDigit sets the "require_digit" field.
func (u *PasswordPolicyUpsertOne) SetRequireDigit(v bool) *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.SetRequireDigit(v)
	})
}

// UpdateRequireDigit sets the "require_digit" field to the value that was provided on create.
func (u *PasswordPolicyUpsertOne) UpdateRequireDigit() *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.UpdateRequireDigit()
	})
}

// SetRequireSymbol sets the "require_symbol" field.
func (u *PasswordPolicyUpsertOne) SetRequireSymbol(v bool) *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.SetRequireSymbol(v)
	})
}

// UpdateRequireSymbol sets the "require_symbol" field to the value that was provided on create.
func (u *PasswordPolicyUpsertOne) UpdateRequireSymbol() *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.UpdateRequireSymbol()
	})
}

// SetExpiryDays sets the "expiry_days" field.
func (u *PasswordPolicyUpsertOne) SetExpiryDays(v int) *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.SetExpiryDays(v)
	})
}

// AddExpiryDays adds v to the "expiry_days" field.
func (u *PasswordPolicyUpsertOne) AddExpiryDays(v int) *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.AddExpiryDays(v)
	})
}

// UpdateExpiryDays sets the "expiry_days" field to the value that was provided on create.
func (u *PasswordPolicyUpsertOne) UpdateExpiryDays() *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.UpdateExpiryDays()
	})
}

// SetReuseBlockCount sets the "reuse_block_count" field.
func (u *PasswordPolicyUpsertOne) SetReuseBlockCount(v int) *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.SetReuseBlockCount(v)
	})
}

// AddReuseBlockCount adds v to the "reuse_block_count" field.
func (u *PasswordPolicyUpsertOne) AddReuseBlockCount(v int) *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.AddReuseBlockCount(v)
	})
}

// UpdateReuseBlockCount sets the "reuse_block_count" field to the value that was provided on create.
func (u *PasswordPolicyUpsertOne) UpdateReuseBlockCount() *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.UpdateReuseBlockCount()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PasswordPolicyUpsertOne) SetUpdatedAt(v time.Time) *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PasswordPolicyUpsertOne) UpdateUpdatedAt() *PasswordPolicyUpsertOne {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PasswordPolicyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PasswordPolicyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PasswordPolicyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PasswordPolicyUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PasswordPolicyUpsertOne.ID is not supported by MySQL driver. Use PasswordPolicyUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PasswordPolicyUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PasswordPolicyCreateBulk is the builder for creating many PasswordPolicy entities in bulk.
type PasswordPolicyCreateBulk struct {
	config
	err      error
	builders []*PasswordPolicyCreate
	conflict []sql.ConflictOption
}

// Save creates the PasswordPolicy entities in the database.
func (_c *PasswordPolicyCreateBulk) Save(ctx context.Context) ([]*PasswordPolicy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PasswordPolicy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PasswordPolicyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PasswordPolicyCreateBulk) SaveX(ctx context.Context) []*PasswordPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PasswordPolicyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PasswordPolicyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PasswordPolicy.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PasswordPolicyUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *PasswordPolicyCreateBulk) OnConflict(opts ...sql.ConflictOption) *PasswordPolicyUpsertBulk {
	_c.conflict = opts
	return &PasswordPolicyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PasswordPolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PasswordPolicyCreateBulk) OnConflictColumns(columns ...string) *PasswordPolicyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PasswordPolicyUpsertBulk{
		create: _c,
	}
}

// PasswordPolicyUpsertBulk is the builder for "upsert"-ing
// a bulk of PasswordPolicy nodes.
type PasswordPolicyUpsertBulk struct {
	create *PasswordPolicyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PasswordPolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(passwordpolicy.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PasswordPolicyUpsertBulk) UpdateNewValues() *PasswordPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(passwordpolicy.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(passwordpolicy.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PasswordPolicy.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PasswordPolicyUpsertBulk) Ignore() *PasswordPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PasswordPolicyUpsertBulk) DoNothing() *PasswordPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PasswordPolicyCreateBulk.OnConflict
// documentation for more info.
func (u *PasswordPolicyUpsertBulk) Update(set func(*PasswordPolicyUpsert)) *PasswordPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PasswordPolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *PasswordPolicyUpsertBulk) SetTenantID(v uuid.UUID) *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *PasswordPolicyUpsertBulk) UpdateTenantID() *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.UpdateTenantID()
	})
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *PasswordPolicyUpsertBulk) ClearTenantID() *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.ClearTenantID()
	})
}

// SetMinLength sets the "min_length" field.
func (u *PasswordPolicyUpsertBulk) SetMinLength(v int) *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.SetMinLength(v)
	})
}

// AddMinLength adds v to the "min_length" field.
func (u *PasswordPolicyUpsertBulk) AddMinLength(v int) *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.AddMinLength(v)
	})
}

// UpdateMinLength sets the "min_length" field to the value that was provided on create.
func (u *PasswordPolicyUpsertBulk) UpdateMinLength() *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.UpdateMinLength()
	})
}

// SetRequireUpper sets the "require_upper" field.
func (u *PasswordPolicyUpsertBulk) SetRequireUpper(v bool) *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.SetRequireUpper(v)
	})
}

// UpdateRequireUpper sets the "require_upper" field to the value that was provided on create.
func (u *PasswordPolicyUpsertBulk) UpdateRequireUpper() *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.UpdateRequireUpper()
	})
}

// SetRequireLower sets the "require_lower" field.
func (u *PasswordPolicyUpsertBulk) SetRequireLower(v bool) *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.SetRequireLower(v)
	})
}

// UpdateRequireLower sets the "require_lower" field to the value that was provided on create.
func (u *PasswordPolicyUpsertBulk) UpdateRequireLower() *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.UpdateRequireLower()
	})
}

// SetRequireDigit sets the "require_digit" field.
func (u *PasswordPolicyUpsertBulk) SetRequireDigit(v bool) *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.SetRequireDigit(v)
	})
}

// UpdateRequireDigit sets the "require_digit" field to the value that was provided on create.
func (u *PasswordPolicyUpsertBulk) UpdateRequireDigit() *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.UpdateRequireDigit()
	})
}

// SetRequireSymbol sets the "require_symbol" field.
func (u *PasswordPolicyUpsertBulk) SetRequireSymbol(v bool) *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.SetRequireSymbol(v)
	})
}

// UpdateRequireSymbol sets the "require_symbol" field to the value that was provided on create.
func (u *PasswordPolicyUpsertBulk) UpdateRequireSymbol() *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.UpdateRequireSymbol()
	})
}

// SetExpiryDays sets the "expiry_days" field.
func (u *PasswordPolicyUpsertBulk) SetExpiryDays(v int) *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.SetExpiryDays(v)
	})
}

// AddExpiryDays adds v to the "expiry_days" field.
func (u *PasswordPolicyUpsertBulk) AddExpiryDays(v int) *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.AddExpiryDays(v)
	})
}

// UpdateExpiryDays sets the "expiry_days" field to the value that was provided on create.
func (u *PasswordPolicyUpsertBulk) UpdateExpiryDays() *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.UpdateExpiryDays()
	})
}

// SetReuseBlockCount sets the "reuse_block_count" field.
func (u *PasswordPolicyUpsertBulk) SetReuseBlockCount(v int) *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.SetReuseBlockCount(v)
	})
}

// AddReuseBlockCount adds v to the "reuse_block_count" field.
func (u *PasswordPolicyUpsertBulk) AddReuseBlockCount(v int) *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.AddReuseBlockCount(v)
	})
}

// UpdateReuseBlockCount sets the "reuse_block_count" field to the value that was provided on create.
func (u *PasswordPolicyUpsertBulk) UpdateReuseBlockCount() *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.UpdateReuseBlockCount()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PasswordPolicyUpsertBulk) SetUpdatedAt(v time.Time) *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PasswordPolicyUpsertBulk) UpdateUpdatedAt() *PasswordPolicyUpsertBulk {
	return u.Update(func(s *PasswordPolicyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PasswordPolicyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PasswordPolicyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PasswordPolicyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PasswordPolicyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
