// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/auth-api/internal/ent/portalshortlink"
	"github.com/google/uuid"
)

// PortalShortLink is the model entity for the PortalShortLink schema.
type PortalShortLink struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Short URL code included in /p/:code redirect URLs
	Code string `json:"code,omitempty"`
	// treasury-api equity_holder.id this link belongs to
	HolderID uuid.UUID `json:"holder_id,omitempty"`
	// Signed equity portal JWT; appended to the redirect URL
	JwtToken string `json:"jwt_token,omitempty"`
	// When the link (and its JWT) expires
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Total times the short link has been visited
	Clicks int `json:"clicks,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PortalShortLink) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case portalshortlink.FieldClicks:
			values[i] = new(sql.NullInt64)
		case portalshortlink.FieldCode, portalshortlink.FieldJwtToken:
			values[i] = new(sql.NullString)
		case portalshortlink.FieldExpiresAt, portalshortlink.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case portalshortlink.FieldID, portalshortlink.FieldHolderID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PortalShortLink fields.
func (_m *PortalShortLink) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case portalshortlink.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case portalshortlink.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case portalshortlink.FieldHolderID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field holder_id", values[i])
			} else if value != nil {
				_m.HolderID = *value
			}
		case portalshortlink.FieldJwtToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field jwt_token", values[i])
			} else if value.Valid {
				_m.JwtToken = value.String
			}
		case portalshortlink.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case portalshortlink.FieldClicks:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field clicks", values[i])
			} else if value.Valid {
				_m.Clicks = int(value.Int64)
			}
		case portalshortlink.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PortalShortLink.
// This includes values selected through modifiers, order, etc.
func (_m *PortalShortLink) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PortalShortLink.
// Note that you need to call PortalShortLink.Unwrap() before calling this method if this PortalShortLink
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PortalShortLink) Update() *PortalShortLinkUpdateOne {
	return NewPortalShortLinkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PortalShortLink entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PortalShortLink) Unwrap() *PortalShortLink {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PortalShortLink is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PortalShortLink) String() string {
	var builder strings.Builder
	builder.WriteString("PortalShortLink(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("holder_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.HolderID))
	builder.WriteString(", ")
	builder.WriteString("jwt_token=")
	builder.WriteString(_m.JwtToken)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("clicks=")
	builder.WriteString(fmt.Sprintf("%v", _m.Clicks))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PortalShortLinks is a parsable slice of PortalShortLink.
type PortalShortLinks []*PortalShortLink
