// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/bengobox/auth-service/internal/ent/auditlog"
	"github.com/bengobox/auth-service/internal/ent/authorizationcode"
	"github.com/bengobox/auth-service/internal/ent/consentsession"
	"github.com/bengobox/auth-service/internal/ent/featureentitlement"
	"github.com/bengobox/auth-service/internal/ent/integrationconfig"
	"github.com/bengobox/auth-service/internal/ent/loginattempt"
	"github.com/bengobox/auth-service/internal/ent/mfabackupcode"
	"github.com/bengobox/auth-service/internal/ent/mfasettings"
	"github.com/bengobox/auth-service/internal/ent/mfatotpsecret"
	"github.com/bengobox/auth-service/internal/ent/oauthclient"
	"github.com/bengobox/auth-service/internal/ent/passwordresettoken"
	"github.com/bengobox/auth-service/internal/ent/schema"
	"github.com/bengobox/auth-service/internal/ent/session"
	"github.com/bengobox/auth-service/internal/ent/tenant"
	"github.com/bengobox/auth-service/internal/ent/tenantmembership"
	"github.com/bengobox/auth-service/internal/ent/usagemetric"
	"github.com/bengobox/auth-service/internal/ent/user"
	"github.com/bengobox/auth-service/internal/ent/useridentity"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescAction is the schema descriptor for action field.
	auditlogDescAction := auditlogFields[3].Descriptor()
	// auditlog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditlog.ActionValidator = auditlogDescAction.Validators[0].(func(string) error)
	// auditlogDescOccurredAt is the schema descriptor for occurred_at field.
	auditlogDescOccurredAt := auditlogFields[9].Descriptor()
	// auditlog.DefaultOccurredAt holds the default value on creation for the occurred_at field.
	auditlog.DefaultOccurredAt = auditlogDescOccurredAt.Default.(func() time.Time)
	// auditlogDescID is the schema descriptor for id field.
	auditlogDescID := auditlogFields[0].Descriptor()
	// auditlog.DefaultID holds the default value on creation for the id field.
	auditlog.DefaultID = auditlogDescID.Default.(func() uuid.UUID)
	authorizationcodeFields := schema.AuthorizationCode{}.Fields()
	_ = authorizationcodeFields
	// authorizationcodeDescClientID is the schema descriptor for client_id field.
	authorizationcodeDescClientID := authorizationcodeFields[2].Descriptor()
	// authorizationcode.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	authorizationcode.ClientIDValidator = authorizationcodeDescClientID.Validators[0].(func(string) error)
	// authorizationcodeDescRedirectURI is the schema descriptor for redirect_uri field.
	authorizationcodeDescRedirectURI := authorizationcodeFields[3].Descriptor()
	// authorizationcode.RedirectURIValidator is a validator for the "redirect_uri" field. It is called by the builders before save.
	authorizationcode.RedirectURIValidator = authorizationcodeDescRedirectURI.Validators[0].(func(string) error)
	// authorizationcodeDescScope is the schema descriptor for scope field.
	authorizationcodeDescScope := authorizationcodeFields[4].Descriptor()
	// authorizationcode.DefaultScope holds the default value on creation for the scope field.
	authorizationcode.DefaultScope = authorizationcodeDescScope.Default.(string)
	// authorizationcodeDescCodeHash is the schema descriptor for code_hash field.
	authorizationcodeDescCodeHash := authorizationcodeFields[5].Descriptor()
	// authorizationcode.CodeHashValidator is a validator for the "code_hash" field. It is called by the builders before save.
	authorizationcode.CodeHashValidator = authorizationcodeDescCodeHash.Validators[0].(func(string) error)
	// authorizationcodeDescCodeChallenge is the schema descriptor for code_challenge field.
	authorizationcodeDescCodeChallenge := authorizationcodeFields[6].Descriptor()
	// authorizationcode.DefaultCodeChallenge holds the default value on creation for the code_challenge field.
	authorizationcode.DefaultCodeChallenge = authorizationcodeDescCodeChallenge.Default.(string)
	// authorizationcodeDescCodeChallengeMethod is the schema descriptor for code_challenge_method field.
	authorizationcodeDescCodeChallengeMethod := authorizationcodeFields[7].Descriptor()
	// authorizationcode.DefaultCodeChallengeMethod holds the default value on creation for the code_challenge_method field.
	authorizationcode.DefaultCodeChallengeMethod = authorizationcodeDescCodeChallengeMethod.Default.(string)
	// authorizationcodeDescNonce is the schema descriptor for nonce field.
	authorizationcodeDescNonce := authorizationcodeFields[8].Descriptor()
	// authorizationcode.DefaultNonce holds the default value on creation for the nonce field.
	authorizationcode.DefaultNonce = authorizationcodeDescNonce.Default.(string)
	// authorizationcodeDescCreatedAt is the schema descriptor for created_at field.
	authorizationcodeDescCreatedAt := authorizationcodeFields[12].Descriptor()
	// authorizationcode.DefaultCreatedAt holds the default value on creation for the created_at field.
	authorizationcode.DefaultCreatedAt = authorizationcodeDescCreatedAt.Default.(func() time.Time)
	// authorizationcodeDescID is the schema descriptor for id field.
	authorizationcodeDescID := authorizationcodeFields[0].Descriptor()
	// authorizationcode.DefaultID holds the default value on creation for the id field.
	authorizationcode.DefaultID = authorizationcodeDescID.Default.(func() uuid.UUID)
	consentsessionFields := schema.ConsentSession{}.Fields()
	_ = consentsessionFields
	// consentsessionDescClientID is the schema descriptor for client_id field.
	consentsessionDescClientID := consentsessionFields[2].Descriptor()
	// consentsession.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	consentsession.ClientIDValidator = consentsessionDescClientID.Validators[0].(func(string) error)
	// consentsessionDescGrantedScopes is the schema descriptor for granted_scopes field.
	consentsessionDescGrantedScopes := consentsessionFields[3].Descriptor()
	// consentsession.DefaultGrantedScopes holds the default value on creation for the granted_scopes field.
	consentsession.DefaultGrantedScopes = consentsessionDescGrantedScopes.Default.(string)
	// consentsessionDescCreatedAt is the schema descriptor for created_at field.
	consentsessionDescCreatedAt := consentsessionFields[8].Descriptor()
	// consentsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	consentsession.DefaultCreatedAt = consentsessionDescCreatedAt.Default.(func() time.Time)
	// consentsessionDescUpdatedAt is the schema descriptor for updated_at field.
	consentsessionDescUpdatedAt := consentsessionFields[9].Descriptor()
	// consentsession.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	consentsession.DefaultUpdatedAt = consentsessionDescUpdatedAt.Default.(func() time.Time)
	// consentsession.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	consentsession.UpdateDefaultUpdatedAt = consentsessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// consentsessionDescID is the schema descriptor for id field.
	consentsessionDescID := consentsessionFields[0].Descriptor()
	// consentsession.DefaultID holds the default value on creation for the id field.
	consentsession.DefaultID = consentsessionDescID.Default.(func() uuid.UUID)
	featureentitlementFields := schema.FeatureEntitlement{}.Fields()
	_ = featureentitlementFields
	// featureentitlementDescFeatureCode is the schema descriptor for feature_code field.
	featureentitlementDescFeatureCode := featureentitlementFields[2].Descriptor()
	// featureentitlement.FeatureCodeValidator is a validator for the "feature_code" field. It is called by the builders before save.
	featureentitlement.FeatureCodeValidator = featureentitlementDescFeatureCode.Validators[0].(func(string) error)
	// featureentitlementDescPlanSource is the schema descriptor for plan_source field.
	featureentitlementDescPlanSource := featureentitlementFields[4].Descriptor()
	// featureentitlement.DefaultPlanSource holds the default value on creation for the plan_source field.
	featureentitlement.DefaultPlanSource = featureentitlementDescPlanSource.Default.(string)
	// featureentitlementDescCreatedAt is the schema descriptor for created_at field.
	featureentitlementDescCreatedAt := featureentitlementFields[6].Descriptor()
	// featureentitlement.DefaultCreatedAt holds the default value on creation for the created_at field.
	featureentitlement.DefaultCreatedAt = featureentitlementDescCreatedAt.Default.(func() time.Time)
	// featureentitlementDescUpdatedAt is the schema descriptor for updated_at field.
	featureentitlementDescUpdatedAt := featureentitlementFields[7].Descriptor()
	// featureentitlement.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	featureentitlement.DefaultUpdatedAt = featureentitlementDescUpdatedAt.Default.(func() time.Time)
	// featureentitlement.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	featureentitlement.UpdateDefaultUpdatedAt = featureentitlementDescUpdatedAt.UpdateDefault.(func() time.Time)
	// featureentitlementDescID is the schema descriptor for id field.
	featureentitlementDescID := featureentitlementFields[0].Descriptor()
	// featureentitlement.DefaultID holds the default value on creation for the id field.
	featureentitlement.DefaultID = featureentitlementDescID.Default.(func() uuid.UUID)
	integrationconfigFields := schema.IntegrationConfig{}.Fields()
	_ = integrationconfigFields
	// integrationconfigDescService is the schema descriptor for service field.
	integrationconfigDescService := integrationconfigFields[2].Descriptor()
	// integrationconfig.ServiceValidator is a validator for the "service" field. It is called by the builders before save.
	integrationconfig.ServiceValidator = integrationconfigDescService.Validators[0].(func(string) error)
	// integrationconfigDescConfigData is the schema descriptor for config_data field.
	integrationconfigDescConfigData := integrationconfigFields[3].Descriptor()
	// integrationconfig.ConfigDataValidator is a validator for the "config_data" field. It is called by the builders before save.
	integrationconfig.ConfigDataValidator = integrationconfigDescConfigData.Validators[0].(func(string) error)
	// integrationconfigDescKeyID is the schema descriptor for key_id field.
	integrationconfigDescKeyID := integrationconfigFields[4].Descriptor()
	// integrationconfig.KeyIDValidator is a validator for the "key_id" field. It is called by the builders before save.
	integrationconfig.KeyIDValidator = integrationconfigDescKeyID.Validators[0].(func(string) error)
	// integrationconfigDescCreatedAt is the schema descriptor for created_at field.
	integrationconfigDescCreatedAt := integrationconfigFields[5].Descriptor()
	// integrationconfig.DefaultCreatedAt holds the default value on creation for the created_at field.
	integrationconfig.DefaultCreatedAt = integrationconfigDescCreatedAt.Default.(func() time.Time)
	// integrationconfigDescUpdatedAt is the schema descriptor for updated_at field.
	integrationconfigDescUpdatedAt := integrationconfigFields[6].Descriptor()
	// integrationconfig.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	integrationconfig.DefaultUpdatedAt = integrationconfigDescUpdatedAt.Default.(func() time.Time)
	// integrationconfig.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	integrationconfig.UpdateDefaultUpdatedAt = integrationconfigDescUpdatedAt.UpdateDefault.(func() time.Time)
	// integrationconfigDescID is the schema descriptor for id field.
	integrationconfigDescID := integrationconfigFields[0].Descriptor()
	// integrationconfig.DefaultID holds the default value on creation for the id field.
	integrationconfig.DefaultID = integrationconfigDescID.Default.(func() uuid.UUID)
	loginattemptFields := schema.LoginAttempt{}.Fields()
	_ = loginattemptFields
	// loginattemptDescEmail is the schema descriptor for email field.
	loginattemptDescEmail := loginattemptFields[3].Descriptor()
	// loginattempt.DefaultEmail holds the default value on creation for the email field.
	loginattempt.DefaultEmail = loginattemptDescEmail.Default.(string)
	// loginattemptDescSuccess is the schema descriptor for success field.
	loginattemptDescSuccess := loginattemptFields[6].Descriptor()
	// loginattempt.DefaultSuccess holds the default value on creation for the success field.
	loginattempt.DefaultSuccess = loginattemptDescSuccess.Default.(bool)
	// loginattemptDescOccurredAt is the schema descriptor for occurred_at field.
	loginattemptDescOccurredAt := loginattemptFields[8].Descriptor()
	// loginattempt.DefaultOccurredAt holds the default value on creation for the occurred_at field.
	loginattempt.DefaultOccurredAt = loginattemptDescOccurredAt.Default.(func() time.Time)
	// loginattemptDescID is the schema descriptor for id field.
	loginattemptDescID := loginattemptFields[0].Descriptor()
	// loginattempt.DefaultID holds the default value on creation for the id field.
	loginattempt.DefaultID = loginattemptDescID.Default.(func() uuid.UUID)
	mfabackupcodeFields := schema.MFABackupCode{}.Fields()
	_ = mfabackupcodeFields
	// mfabackupcodeDescCodeHash is the schema descriptor for code_hash field.
	mfabackupcodeDescCodeHash := mfabackupcodeFields[2].Descriptor()
	// mfabackupcode.CodeHashValidator is a validator for the "code_hash" field. It is called by the builders before save.
	mfabackupcode.CodeHashValidator = mfabackupcodeDescCodeHash.Validators[0].(func(string) error)
	// mfabackupcodeDescCreatedAt is the schema descriptor for created_at field.
	mfabackupcodeDescCreatedAt := mfabackupcodeFields[4].Descriptor()
	// mfabackupcode.DefaultCreatedAt holds the default value on creation for the created_at field.
	mfabackupcode.DefaultCreatedAt = mfabackupcodeDescCreatedAt.Default.(func() time.Time)
	// mfabackupcodeDescID is the schema descriptor for id field.
	mfabackupcodeDescID := mfabackupcodeFields[0].Descriptor()
	// mfabackupcode.DefaultID holds the default value on creation for the id field.
	mfabackupcode.DefaultID = mfabackupcodeDescID.Default.(func() uuid.UUID)
	mfasettingsFields := schema.MFASettings{}.Fields()
	_ = mfasettingsFields
	// mfasettingsDescPrimaryMethod is the schema descriptor for primary_method field.
	mfasettingsDescPrimaryMethod := mfasettingsFields[1].Descriptor()
	// mfasettings.DefaultPrimaryMethod holds the default value on creation for the primary_method field.
	mfasettings.DefaultPrimaryMethod = mfasettingsDescPrimaryMethod.Default.(string)
	// mfasettingsDescRecoveryChannel is the schema descriptor for recovery_channel field.
	mfasettingsDescRecoveryChannel := mfasettingsFields[3].Descriptor()
	// mfasettings.DefaultRecoveryChannel holds the default value on creation for the recovery_channel field.
	mfasettings.DefaultRecoveryChannel = mfasettingsDescRecoveryChannel.Default.(string)
	// mfasettingsDescCreatedAt is the schema descriptor for created_at field.
	mfasettingsDescCreatedAt := mfasettingsFields[4].Descriptor()
	// mfasettings.DefaultCreatedAt holds the default value on creation for the created_at field.
	mfasettings.DefaultCreatedAt = mfasettingsDescCreatedAt.Default.(func() time.Time)
	// mfasettingsDescUpdatedAt is the schema descriptor for updated_at field.
	mfasettingsDescUpdatedAt := mfasettingsFields[5].Descriptor()
	// mfasettings.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mfasettings.DefaultUpdatedAt = mfasettingsDescUpdatedAt.Default.(func() time.Time)
	// mfasettings.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mfasettings.UpdateDefaultUpdatedAt = mfasettingsDescUpdatedAt.UpdateDefault.(func() time.Time)
	mfatotpsecretFields := schema.MFATOTPSecret{}.Fields()
	_ = mfatotpsecretFields
	// mfatotpsecretDescSecret is the schema descriptor for secret field.
	mfatotpsecretDescSecret := mfatotpsecretFields[2].Descriptor()
	// mfatotpsecret.SecretValidator is a validator for the "secret" field. It is called by the builders before save.
	mfatotpsecret.SecretValidator = mfatotpsecretDescSecret.Validators[0].(func(string) error)
	// mfatotpsecretDescDigits is the schema descriptor for digits field.
	mfatotpsecretDescDigits := mfatotpsecretFields[3].Descriptor()
	// mfatotpsecret.DefaultDigits holds the default value on creation for the digits field.
	mfatotpsecret.DefaultDigits = mfatotpsecretDescDigits.Default.(int)
	// mfatotpsecretDescPeriod is the schema descriptor for period field.
	mfatotpsecretDescPeriod := mfatotpsecretFields[4].Descriptor()
	// mfatotpsecret.DefaultPeriod holds the default value on creation for the period field.
	mfatotpsecret.DefaultPeriod = mfatotpsecretDescPeriod.Default.(int)
	// mfatotpsecretDescCreatedAt is the schema descriptor for created_at field.
	mfatotpsecretDescCreatedAt := mfatotpsecretFields[7].Descriptor()
	// mfatotpsecret.DefaultCreatedAt holds the default value on creation for the created_at field.
	mfatotpsecret.DefaultCreatedAt = mfatotpsecretDescCreatedAt.Default.(func() time.Time)
	// mfatotpsecretDescID is the schema descriptor for id field.
	mfatotpsecretDescID := mfatotpsecretFields[0].Descriptor()
	// mfatotpsecret.DefaultID holds the default value on creation for the id field.
	mfatotpsecret.DefaultID = mfatotpsecretDescID.Default.(func() uuid.UUID)
	oauthclientFields := schema.OAuthClient{}.Fields()
	_ = oauthclientFields
	// oauthclientDescClientID is the schema descriptor for client_id field.
	oauthclientDescClientID := oauthclientFields[1].Descriptor()
	// oauthclient.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauthclient.ClientIDValidator = oauthclientDescClientID.Validators[0].(func(string) error)
	// oauthclientDescName is the schema descriptor for name field.
	oauthclientDescName := oauthclientFields[3].Descriptor()
	// oauthclient.NameValidator is a validator for the "name" field. It is called by the builders before save.
	oauthclient.NameValidator = oauthclientDescName.Validators[0].(func(string) error)
	// oauthclientDescPublic is the schema descriptor for public field.
	oauthclientDescPublic := oauthclientFields[6].Descriptor()
	// oauthclient.DefaultPublic holds the default value on creation for the public field.
	oauthclient.DefaultPublic = oauthclientDescPublic.Default.(bool)
	// oauthclientDescCreatedAt is the schema descriptor for created_at field.
	oauthclientDescCreatedAt := oauthclientFields[9].Descriptor()
	// oauthclient.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthclient.DefaultCreatedAt = oauthclientDescCreatedAt.Default.(func() time.Time)
	// oauthclientDescUpdatedAt is the schema descriptor for updated_at field.
	oauthclientDescUpdatedAt := oauthclientFields[10].Descriptor()
	// oauthclient.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthclient.DefaultUpdatedAt = oauthclientDescUpdatedAt.Default.(func() time.Time)
	// oauthclient.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthclient.UpdateDefaultUpdatedAt = oauthclientDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauthclientDescID is the schema descriptor for id field.
	oauthclientDescID := oauthclientFields[0].Descriptor()
	// oauthclient.DefaultID holds the default value on creation for the id field.
	oauthclient.DefaultID = oauthclientDescID.Default.(func() uuid.UUID)
	passwordresettokenFields := schema.PasswordResetToken{}.Fields()
	_ = passwordresettokenFields
	// passwordresettokenDescTokenHash is the schema descriptor for token_hash field.
	passwordresettokenDescTokenHash := passwordresettokenFields[2].Descriptor()
	// passwordresettoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	passwordresettoken.TokenHashValidator = passwordresettokenDescTokenHash.Validators[0].(func(string) error)
	// passwordresettokenDescCreatedAt is the schema descriptor for created_at field.
	passwordresettokenDescCreatedAt := passwordresettokenFields[5].Descriptor()
	// passwordresettoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	passwordresettoken.DefaultCreatedAt = passwordresettokenDescCreatedAt.Default.(func() time.Time)
	// passwordresettokenDescID is the schema descriptor for id field.
	passwordresettokenDescID := passwordresettokenFields[0].Descriptor()
	// passwordresettoken.DefaultID holds the default value on creation for the id field.
	passwordresettoken.DefaultID = passwordresettokenDescID.Default.(func() uuid.UUID)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescSessionType is the schema descriptor for session_type field.
	sessionDescSessionType := sessionFields[4].Descriptor()
	// session.DefaultSessionType holds the default value on creation for the session_type field.
	session.DefaultSessionType = sessionDescSessionType.Default.(string)
	// sessionDescStatus is the schema descriptor for status field.
	sessionDescStatus := sessionFields[5].Descriptor()
	// session.DefaultStatus holds the default value on creation for the status field.
	session.DefaultStatus = sessionDescStatus.Default.(string)
	// sessionDescRefreshTokenHash is the schema descriptor for refresh_token_hash field.
	sessionDescRefreshTokenHash := sessionFields[6].Descriptor()
	// session.RefreshTokenHashValidator is a validator for the "refresh_token_hash" field. It is called by the builders before save.
	session.RefreshTokenHashValidator = sessionDescRefreshTokenHash.Validators[0].(func(string) error)
	// sessionDescIssuedAt is the schema descriptor for issued_at field.
	sessionDescIssuedAt := sessionFields[7].Descriptor()
	// session.DefaultIssuedAt holds the default value on creation for the issued_at field.
	session.DefaultIssuedAt = sessionDescIssuedAt.Default.(func() time.Time)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[14].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescUpdatedAt is the schema descriptor for updated_at field.
	sessionDescUpdatedAt := sessionFields[15].Descriptor()
	// session.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	session.DefaultUpdatedAt = sessionDescUpdatedAt.Default.(func() time.Time)
	// session.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	session.UpdateDefaultUpdatedAt = sessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[1].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = tenantDescName.Validators[0].(func(string) error)
	// tenantDescSlug is the schema descriptor for slug field.
	tenantDescSlug := tenantFields[2].Descriptor()
	// tenant.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	tenant.SlugValidator = tenantDescSlug.Validators[0].(func(string) error)
	// tenantDescStatus is the schema descriptor for status field.
	tenantDescStatus := tenantFields[3].Descriptor()
	// tenant.DefaultStatus holds the default value on creation for the status field.
	tenant.DefaultStatus = tenantDescStatus.Default.(string)
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantFields[5].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescUpdatedAt is the schema descriptor for updated_at field.
	tenantDescUpdatedAt := tenantFields[6].Descriptor()
	// tenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenant.DefaultUpdatedAt = tenantDescUpdatedAt.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenant.UpdateDefaultUpdatedAt = tenantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantFields[0].Descriptor()
	// tenant.DefaultID holds the default value on creation for the id field.
	tenant.DefaultID = tenantDescID.Default.(func() uuid.UUID)
	tenantmembershipFields := schema.TenantMembership{}.Fields()
	_ = tenantmembershipFields
	// tenantmembershipDescStatus is the schema descriptor for status field.
	tenantmembershipDescStatus := tenantmembershipFields[4].Descriptor()
	// tenantmembership.DefaultStatus holds the default value on creation for the status field.
	tenantmembership.DefaultStatus = tenantmembershipDescStatus.Default.(string)
	// tenantmembershipDescCreatedAt is the schema descriptor for created_at field.
	tenantmembershipDescCreatedAt := tenantmembershipFields[5].Descriptor()
	// tenantmembership.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenantmembership.DefaultCreatedAt = tenantmembershipDescCreatedAt.Default.(func() time.Time)
	// tenantmembershipDescUpdatedAt is the schema descriptor for updated_at field.
	tenantmembershipDescUpdatedAt := tenantmembershipFields[6].Descriptor()
	// tenantmembership.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenantmembership.DefaultUpdatedAt = tenantmembershipDescUpdatedAt.Default.(func() time.Time)
	// tenantmembership.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenantmembership.UpdateDefaultUpdatedAt = tenantmembershipDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantmembershipDescID is the schema descriptor for id field.
	tenantmembershipDescID := tenantmembershipFields[0].Descriptor()
	// tenantmembership.DefaultID holds the default value on creation for the id field.
	tenantmembership.DefaultID = tenantmembershipDescID.Default.(func() uuid.UUID)
	usagemetricFields := schema.UsageMetric{}.Fields()
	_ = usagemetricFields
	// usagemetricDescActiveUsers is the schema descriptor for active_users field.
	usagemetricDescActiveUsers := usagemetricFields[3].Descriptor()
	// usagemetric.DefaultActiveUsers holds the default value on creation for the active_users field.
	usagemetric.DefaultActiveUsers = usagemetricDescActiveUsers.Default.(int)
	// usagemetricDescAuthTransactions is the schema descriptor for auth_transactions field.
	usagemetricDescAuthTransactions := usagemetricFields[4].Descriptor()
	// usagemetric.DefaultAuthTransactions holds the default value on creation for the auth_transactions field.
	usagemetric.DefaultAuthTransactions = usagemetricDescAuthTransactions.Default.(int)
	// usagemetricDescMfaPrompts is the schema descriptor for mfa_prompts field.
	usagemetricDescMfaPrompts := usagemetricFields[5].Descriptor()
	// usagemetric.DefaultMfaPrompts holds the default value on creation for the mfa_prompts field.
	usagemetric.DefaultMfaPrompts = usagemetricDescMfaPrompts.Default.(int)
	// usagemetricDescMachineTokens is the schema descriptor for machine_tokens field.
	usagemetricDescMachineTokens := usagemetricFields[6].Descriptor()
	// usagemetric.DefaultMachineTokens holds the default value on creation for the machine_tokens field.
	usagemetric.DefaultMachineTokens = usagemetricDescMachineTokens.Default.(int)
	// usagemetricDescCreatedAt is the schema descriptor for created_at field.
	usagemetricDescCreatedAt := usagemetricFields[7].Descriptor()
	// usagemetric.DefaultCreatedAt holds the default value on creation for the created_at field.
	usagemetric.DefaultCreatedAt = usagemetricDescCreatedAt.Default.(func() time.Time)
	// usagemetricDescUpdatedAt is the schema descriptor for updated_at field.
	usagemetricDescUpdatedAt := usagemetricFields[8].Descriptor()
	// usagemetric.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	usagemetric.DefaultUpdatedAt = usagemetricDescUpdatedAt.Default.(func() time.Time)
	// usagemetric.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	usagemetric.UpdateDefaultUpdatedAt = usagemetricDescUpdatedAt.UpdateDefault.(func() time.Time)
	// usagemetricDescID is the schema descriptor for id field.
	usagemetricDescID := usagemetricFields[0].Descriptor()
	// usagemetric.DefaultID holds the default value on creation for the id field.
	usagemetric.DefaultID = usagemetricDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[3].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescPrimaryTenantID is the schema descriptor for primary_tenant_id field.
	userDescPrimaryTenantID := userFields[6].Descriptor()
	// user.PrimaryTenantIDValidator is a validator for the "primary_tenant_id" field. It is called by the builders before save.
	user.PrimaryTenantIDValidator = userDescPrimaryTenantID.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	useridentityFields := schema.UserIdentity{}.Fields()
	_ = useridentityFields
	// useridentityDescProvider is the schema descriptor for provider field.
	useridentityDescProvider := useridentityFields[2].Descriptor()
	// useridentity.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	useridentity.ProviderValidator = useridentityDescProvider.Validators[0].(func(string) error)
	// useridentityDescProviderSubject is the schema descriptor for provider_subject field.
	useridentityDescProviderSubject := useridentityFields[3].Descriptor()
	// useridentity.ProviderSubjectValidator is a validator for the "provider_subject" field. It is called by the builders before save.
	useridentity.ProviderSubjectValidator = useridentityDescProviderSubject.Validators[0].(func(string) error)
	// useridentityDescProviderEmail is the schema descriptor for provider_email field.
	useridentityDescProviderEmail := useridentityFields[4].Descriptor()
	// useridentity.ProviderEmailValidator is a validator for the "provider_email" field. It is called by the builders before save.
	useridentity.ProviderEmailValidator = useridentityDescProviderEmail.Validators[0].(func(string) error)
	// useridentityDescEmailVerified is the schema descriptor for email_verified field.
	useridentityDescEmailVerified := useridentityFields[5].Descriptor()
	// useridentity.DefaultEmailVerified holds the default value on creation for the email_verified field.
	useridentity.DefaultEmailVerified = useridentityDescEmailVerified.Default.(bool)
	// useridentityDescLinkedAt is the schema descriptor for linked_at field.
	useridentityDescLinkedAt := useridentityFields[11].Descriptor()
	// useridentity.DefaultLinkedAt holds the default value on creation for the linked_at field.
	useridentity.DefaultLinkedAt = useridentityDescLinkedAt.Default.(func() time.Time)
	// useridentityDescUpdatedAt is the schema descriptor for updated_at field.
	useridentityDescUpdatedAt := useridentityFields[12].Descriptor()
	// useridentity.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	useridentity.DefaultUpdatedAt = useridentityDescUpdatedAt.Default.(func() time.Time)
	// useridentity.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	useridentity.UpdateDefaultUpdatedAt = useridentityDescUpdatedAt.UpdateDefault.(func() time.Time)
	// useridentityDescID is the schema descriptor for id field.
	useridentityDescID := useridentityFields[0].Descriptor()
	// useridentity.DefaultID holds the default value on creation for the id field.
	useridentity.DefaultID = useridentityDescID.Default.(func() uuid.UUID)
}
