// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/auth-api/internal/ent/outlet"
	"github.com/bengobox/auth-api/internal/ent/predicate"
	"github.com/bengobox/auth-api/internal/ent/tenant"
	"github.com/bengobox/auth-api/internal/ent/tenantmembership"
	"github.com/google/uuid"
)

// TenantUpdate is the builder for updating Tenant entities.
type TenantUpdate struct {
	config
	hooks    []Hook
	mutation *TenantMutation
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdate) Where(ps ...predicate.Tenant) *TenantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TenantUpdate) SetName(v string) *TenantUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableName(v *string) *TenantUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *TenantUpdate) SetSlug(v string) *TenantUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableSlug(v *string) *TenantUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantUpdate) SetStatus(v string) *TenantUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableStatus(v *string) *TenantUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSubscriptionExempt sets the "subscription_exempt" field.
func (_u *TenantUpdate) SetSubscriptionExempt(v bool) *TenantUpdate {
	_u.mutation.SetSubscriptionExempt(v)
	return _u
}

// SetNillableSubscriptionExempt sets the "subscription_exempt" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableSubscriptionExempt(v *bool) *TenantUpdate {
	if v != nil {
		_u.SetSubscriptionExempt(*v)
	}
	return _u
}

// SetIsDemo sets the "is_demo" field.
func (_u *TenantUpdate) SetIsDemo(v bool) *TenantUpdate {
	_u.mutation.SetIsDemo(v)
	return _u
}

// SetNillableIsDemo sets the "is_demo" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableIsDemo(v *bool) *TenantUpdate {
	if v != nil {
		_u.SetIsDemo(*v)
	}
	return _u
}

// SetIsReseller sets the "is_reseller" field.
func (_u *TenantUpdate) SetIsReseller(v bool) *TenantUpdate {
	_u.mutation.SetIsReseller(v)
	return _u
}

// SetNillableIsReseller sets the "is_reseller" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableIsReseller(v *bool) *TenantUpdate {
	if v != nil {
		_u.SetIsReseller(*v)
	}
	return _u
}

// SetManagedByResellerTenantID sets the "managed_by_reseller_tenant_id" field.
func (_u *TenantUpdate) SetManagedByResellerTenantID(v uuid.UUID) *TenantUpdate {
	_u.mutation.SetManagedByResellerTenantID(v)
	return _u
}

// SetNillableManagedByResellerTenantID sets the "managed_by_reseller_tenant_id" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableManagedByResellerTenantID(v *uuid.UUID) *TenantUpdate {
	if v != nil {
		_u.SetManagedByResellerTenantID(*v)
	}
	return _u
}

// ClearManagedByResellerTenantID clears the value of the "managed_by_reseller_tenant_id" field.
func (_u *TenantUpdate) ClearManagedByResellerTenantID() *TenantUpdate {
	_u.mutation.ClearManagedByResellerTenantID()
	return _u
}

// SetContactEmail sets the "contact_email" field.
func (_u *TenantUpdate) SetContactEmail(v string) *TenantUpdate {
	_u.mutation.SetContactEmail(v)
	return _u
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableContactEmail(v *string) *TenantUpdate {
	if v != nil {
		_u.SetContactEmail(*v)
	}
	return _u
}

// ClearContactEmail clears the value of the "contact_email" field.
func (_u *TenantUpdate) ClearContactEmail() *TenantUpdate {
	_u.mutation.ClearContactEmail()
	return _u
}

// SetContactPhone sets the "contact_phone" field.
func (_u *TenantUpdate) SetContactPhone(v string) *TenantUpdate {
	_u.mutation.SetContactPhone(v)
	return _u
}

// SetNillableContactPhone sets the "contact_phone" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableContactPhone(v *string) *TenantUpdate {
	if v != nil {
		_u.SetContactPhone(*v)
	}
	return _u
}

// ClearContactPhone clears the value of the "contact_phone" field.
func (_u *TenantUpdate) ClearContactPhone() *TenantUpdate {
	_u.mutation.ClearContactPhone()
	return _u
}

// SetLogoURL sets the "logo_url" field.
func (_u *TenantUpdate) SetLogoURL(v string) *TenantUpdate {
	_u.mutation.SetLogoURL(v)
	return _u
}

// SetNillableLogoURL sets the "logo_url" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableLogoURL(v *string) *TenantUpdate {
	if v != nil {
		_u.SetLogoURL(*v)
	}
	return _u
}

// ClearLogoURL clears the value of the "logo_url" field.
func (_u *TenantUpdate) ClearLogoURL() *TenantUpdate {
	_u.mutation.ClearLogoURL()
	return _u
}

// SetWebsite sets the "website" field.
func (_u *TenantUpdate) SetWebsite(v string) *TenantUpdate {
	_u.mutation.SetWebsite(v)
	return _u
}

// SetNillableWebsite sets the "website" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableWebsite(v *string) *TenantUpdate {
	if v != nil {
		_u.SetWebsite(*v)
	}
	return _u
}

// ClearWebsite clears the value of the "website" field.
func (_u *TenantUpdate) ClearWebsite() *TenantUpdate {
	_u.mutation.ClearWebsite()
	return _u
}

// SetCountry sets the "country" field.
func (_u *TenantUpdate) SetCountry(v string) *TenantUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableCountry(v *string) *TenantUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *TenantUpdate) ClearCountry() *TenantUpdate {
	_u.mutation.ClearCountry()
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *TenantUpdate) SetTimezone(v string) *TenantUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableTimezone(v *string) *TenantUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// ClearTimezone clears the value of the "timezone" field.
func (_u *TenantUpdate) ClearTimezone() *TenantUpdate {
	_u.mutation.ClearTimezone()
	return _u
}

// SetBrandColors sets the "brand_colors" field.
func (_u *TenantUpdate) SetBrandColors(v map[string]interface{}) *TenantUpdate {
	_u.mutation.SetBrandColors(v)
	return _u
}

// ClearBrandColors clears the value of the "brand_colors" field.
func (_u *TenantUpdate) ClearBrandColors() *TenantUpdate {
	_u.mutation.ClearBrandColors()
	return _u
}

// SetOrgSize sets the "org_size" field.
func (_u *TenantUpdate) SetOrgSize(v string) *TenantUpdate {
	_u.mutation.SetOrgSize(v)
	return _u
}

// SetNillableOrgSize sets the "org_size" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableOrgSize(v *string) *TenantUpdate {
	if v != nil {
		_u.SetOrgSize(*v)
	}
	return _u
}

// ClearOrgSize clears the value of the "org_size" field.
func (_u *TenantUpdate) ClearOrgSize() *TenantUpdate {
	_u.mutation.ClearOrgSize()
	return _u
}

// SetUseCase sets the "use_case" field.
func (_u *TenantUpdate) SetUseCase(v string) *TenantUpdate {
	_u.mutation.SetUseCase(v)
	return _u
}

// SetNillableUseCase sets the "use_case" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableUseCase(v *string) *TenantUpdate {
	if v != nil {
		_u.SetUseCase(*v)
	}
	return _u
}

// ClearUseCase clears the value of the "use_case" field.
func (_u *TenantUpdate) ClearUseCase() *TenantUpdate {
	_u.mutation.ClearUseCase()
	return _u
}

// SetUseCases sets the "use_cases" field.
func (_u *TenantUpdate) SetUseCases(v []string) *TenantUpdate {
	_u.mutation.SetUseCases(v)
	return _u
}

// AppendUseCases appends value to the "use_cases" field.
func (_u *TenantUpdate) AppendUseCases(v []string) *TenantUpdate {
	_u.mutation.AppendUseCases(v)
	return _u
}

// ClearUseCases clears the value of the "use_cases" field.
func (_u *TenantUpdate) ClearUseCases() *TenantUpdate {
	_u.mutation.ClearUseCases()
	return _u
}

// SetTaxPin sets the "tax_pin" field.
func (_u *TenantUpdate) SetTaxPin(v string) *TenantUpdate {
	_u.mutation.SetTaxPin(v)
	return _u
}

// SetNillableTaxPin sets the "tax_pin" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableTaxPin(v *string) *TenantUpdate {
	if v != nil {
		_u.SetTaxPin(*v)
	}
	return _u
}

// ClearTaxPin clears the value of the "tax_pin" field.
func (_u *TenantUpdate) ClearTaxPin() *TenantUpdate {
	_u.mutation.ClearTaxPin()
	return _u
}

// SetVatRegistered sets the "vat_registered" field.
func (_u *TenantUpdate) SetVatRegistered(v bool) *TenantUpdate {
	_u.mutation.SetVatRegistered(v)
	return _u
}

// SetNillableVatRegistered sets the "vat_registered" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableVatRegistered(v *bool) *TenantUpdate {
	if v != nil {
		_u.SetVatRegistered(*v)
	}
	return _u
}

// SetVatRegisteredOn sets the "vat_registered_on" field.
func (_u *TenantUpdate) SetVatRegisteredOn(v time.Time) *TenantUpdate {
	_u.mutation.SetVatRegisteredOn(v)
	return _u
}

// SetNillableVatRegisteredOn sets the "vat_registered_on" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableVatRegisteredOn(v *time.Time) *TenantUpdate {
	if v != nil {
		_u.SetVatRegisteredOn(*v)
	}
	return _u
}

// ClearVatRegisteredOn clears the value of the "vat_registered_on" field.
func (_u *TenantUpdate) ClearVatRegisteredOn() *TenantUpdate {
	_u.mutation.ClearVatRegisteredOn()
	return _u
}

// SetSubscriptionPlan sets the "subscription_plan" field.
func (_u *TenantUpdate) SetSubscriptionPlan(v string) *TenantUpdate {
	_u.mutation.SetSubscriptionPlan(v)
	return _u
}

// SetNillableSubscriptionPlan sets the "subscription_plan" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableSubscriptionPlan(v *string) *TenantUpdate {
	if v != nil {
		_u.SetSubscriptionPlan(*v)
	}
	return _u
}

// ClearSubscriptionPlan clears the value of the "subscription_plan" field.
func (_u *TenantUpdate) ClearSubscriptionPlan() *TenantUpdate {
	_u.mutation.ClearSubscriptionPlan()
	return _u
}

// SetSubscriptionStatus sets the "subscription_status" field.
func (_u *TenantUpdate) SetSubscriptionStatus(v string) *TenantUpdate {
	_u.mutation.SetSubscriptionStatus(v)
	return _u
}

// SetNillableSubscriptionStatus sets the "subscription_status" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableSubscriptionStatus(v *string) *TenantUpdate {
	if v != nil {
		_u.SetSubscriptionStatus(*v)
	}
	return _u
}

// ClearSubscriptionStatus clears the value of the "subscription_status" field.
func (_u *TenantUpdate) ClearSubscriptionStatus() *TenantUpdate {
	_u.mutation.ClearSubscriptionStatus()
	return _u
}

// SetSubscriptionExpiresAt sets the "subscription_expires_at" field.
func (_u *TenantUpdate) SetSubscriptionExpiresAt(v time.Time) *TenantUpdate {
	_u.mutation.SetSubscriptionExpiresAt(v)
	return _u
}

// SetNillableSubscriptionExpiresAt sets the "subscription_expires_at" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableSubscriptionExpiresAt(v *time.Time) *TenantUpdate {
	if v != nil {
		_u.SetSubscriptionExpiresAt(*v)
	}
	return _u
}

// ClearSubscriptionExpiresAt clears the value of the "subscription_expires_at" field.
func (_u *TenantUpdate) ClearSubscriptionExpiresAt() *TenantUpdate {
	_u.mutation.ClearSubscriptionExpiresAt()
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *TenantUpdate) SetSubscriptionID(v string) *TenantUpdate {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableSubscriptionID(v *string) *TenantUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (_u *TenantUpdate) ClearSubscriptionID() *TenantUpdate {
	_u.mutation.ClearSubscriptionID()
	return _u
}

// SetTierLimits sets the "tier_limits" field.
func (_u *TenantUpdate) SetTierLimits(v map[string]interface{}) *TenantUpdate {
	_u.mutation.SetTierLimits(v)
	return _u
}

// ClearTierLimits clears the value of the "tier_limits" field.
func (_u *TenantUpdate) ClearTierLimits() *TenantUpdate {
	_u.mutation.ClearTierLimits()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *TenantUpdate) SetMetadata(v map[string]interface{}) *TenantUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *TenantUpdate) ClearMetadata() *TenantUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantUpdate) SetUpdatedAt(v time.Time) *TenantUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddMembershipIDs adds the "memberships" edge to the TenantMembership entity by IDs.
func (_u *TenantUpdate) AddMembershipIDs(ids ...uuid.UUID) *TenantUpdate {
	_u.mutation.AddMembershipIDs(ids...)
	return _u
}

// AddMemberships adds the "memberships" edges to the TenantMembership entity.
func (_u *TenantUpdate) AddMemberships(v ...*TenantMembership) *TenantUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipIDs(ids...)
}

// AddOutletIDs adds the "outlets" edge to the Outlet entity by IDs.
func (_u *TenantUpdate) AddOutletIDs(ids ...uuid.UUID) *TenantUpdate {
	_u.mutation.AddOutletIDs(ids...)
	return _u
}

// AddOutlets adds the "outlets" edges to the Outlet entity.
func (_u *TenantUpdate) AddOutlets(v ...*Outlet) *TenantUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOutletIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdate) Mutation() *TenantMutation {
	return _u.mutation
}

// ClearMemberships clears all "memberships" edges to the TenantMembership entity.
func (_u *TenantUpdate) ClearMemberships() *TenantUpdate {
	_u.mutation.ClearMemberships()
	return _u
}

// RemoveMembershipIDs removes the "memberships" edge to TenantMembership entities by IDs.
func (_u *TenantUpdate) RemoveMembershipIDs(ids ...uuid.UUID) *TenantUpdate {
	_u.mutation.RemoveMembershipIDs(ids...)
	return _u
}

// RemoveMemberships removes "memberships" edges to TenantMembership entities.
func (_u *TenantUpdate) RemoveMemberships(v ...*TenantMembership) *TenantUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipIDs(ids...)
}

// ClearOutlets clears all "outlets" edges to the Outlet entity.
func (_u *TenantUpdate) ClearOutlets() *TenantUpdate {
	_u.mutation.ClearOutlets()
	return _u
}

// RemoveOutletIDs removes the "outlets" edge to Outlet entities by IDs.
func (_u *TenantUpdate) RemoveOutletIDs(ids ...uuid.UUID) *TenantUpdate {
	_u.mutation.RemoveOutletIDs(ids...)
	return _u
}

// RemoveOutlets removes "outlets" edges to Outlet entities.
func (_u *TenantUpdate) RemoveOutlets(v ...*Outlet) *TenantUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOutletIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := tenant.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Tenant.slug": %w`, err)}
		}
	}
	return nil
}

func (_u *TenantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(tenant.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenant.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubscriptionExempt(); ok {
		_spec.SetField(tenant.FieldSubscriptionExempt, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsDemo(); ok {
		_spec.SetField(tenant.FieldIsDemo, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsReseller(); ok {
		_spec.SetField(tenant.FieldIsReseller, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ManagedByResellerTenantID(); ok {
		_spec.SetField(tenant.FieldManagedByResellerTenantID, field.TypeUUID, value)
	}
	if _u.mutation.ManagedByResellerTenantIDCleared() {
		_spec.ClearField(tenant.FieldManagedByResellerTenantID, field.TypeUUID)
	}
	if value, ok := _u.mutation.ContactEmail(); ok {
		_spec.SetField(tenant.FieldContactEmail, field.TypeString, value)
	}
	if _u.mutation.ContactEmailCleared() {
		_spec.ClearField(tenant.FieldContactEmail, field.TypeString)
	}
	if value, ok := _u.mutation.ContactPhone(); ok {
		_spec.SetField(tenant.FieldContactPhone, field.TypeString, value)
	}
	if _u.mutation.ContactPhoneCleared() {
		_spec.ClearField(tenant.FieldContactPhone, field.TypeString)
	}
	if value, ok := _u.mutation.LogoURL(); ok {
		_spec.SetField(tenant.FieldLogoURL, field.TypeString, value)
	}
	if _u.mutation.LogoURLCleared() {
		_spec.ClearField(tenant.FieldLogoURL, field.TypeString)
	}
	if value, ok := _u.mutation.Website(); ok {
		_spec.SetField(tenant.FieldWebsite, field.TypeString, value)
	}
	if _u.mutation.WebsiteCleared() {
		_spec.ClearField(tenant.FieldWebsite, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(tenant.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(tenant.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(tenant.FieldTimezone, field.TypeString, value)
	}
	if _u.mutation.TimezoneCleared() {
		_spec.ClearField(tenant.FieldTimezone, field.TypeString)
	}
	if value, ok := _u.mutation.BrandColors(); ok {
		_spec.SetField(tenant.FieldBrandColors, field.TypeJSON, value)
	}
	if _u.mutation.BrandColorsCleared() {
		_spec.ClearField(tenant.FieldBrandColors, field.TypeJSON)
	}
	if value, ok := _u.mutation.OrgSize(); ok {
		_spec.SetField(tenant.FieldOrgSize, field.TypeString, value)
	}
	if _u.mutation.OrgSizeCleared() {
		_spec.ClearField(tenant.FieldOrgSize, field.TypeString)
	}
	if value, ok := _u.mutation.UseCase(); ok {
		_spec.SetField(tenant.FieldUseCase, field.TypeString, value)
	}
	if _u.mutation.UseCaseCleared() {
		_spec.ClearField(tenant.FieldUseCase, field.TypeString)
	}
	if value, ok := _u.mutation.UseCases(); ok {
		_spec.SetField(tenant.FieldUseCases, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUseCases(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenant.FieldUseCases, value)
		})
	}
	if _u.mutation.UseCasesCleared() {
		_spec.ClearField(tenant.FieldUseCases, field.TypeJSON)
	}
	if value, ok := _u.mutation.TaxPin(); ok {
		_spec.SetField(tenant.FieldTaxPin, field.TypeString, value)
	}
	if _u.mutation.TaxPinCleared() {
		_spec.ClearField(tenant.FieldTaxPin, field.TypeString)
	}
	if value, ok := _u.mutation.VatRegistered(); ok {
		_spec.SetField(tenant.FieldVatRegistered, field.TypeBool, value)
	}
	if value, ok := _u.mutation.VatRegisteredOn(); ok {
		_spec.SetField(tenant.FieldVatRegisteredOn, field.TypeTime, value)
	}
	if _u.mutation.VatRegisteredOnCleared() {
		_spec.ClearField(tenant.FieldVatRegisteredOn, field.TypeTime)
	}
	if value, ok := _u.mutation.SubscriptionPlan(); ok {
		_spec.SetField(tenant.FieldSubscriptionPlan, field.TypeString, value)
	}
	if _u.mutation.SubscriptionPlanCleared() {
		_spec.ClearField(tenant.FieldSubscriptionPlan, field.TypeString)
	}
	if value, ok := _u.mutation.SubscriptionStatus(); ok {
		_spec.SetField(tenant.FieldSubscriptionStatus, field.TypeString, value)
	}
	if _u.mutation.SubscriptionStatusCleared() {
		_spec.ClearField(tenant.FieldSubscriptionStatus, field.TypeString)
	}
	if value, ok := _u.mutation.SubscriptionExpiresAt(); ok {
		_spec.SetField(tenant.FieldSubscriptionExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.SubscriptionExpiresAtCleared() {
		_spec.ClearField(tenant.FieldSubscriptionExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(tenant.FieldSubscriptionID, field.TypeString, value)
	}
	if _u.mutation.SubscriptionIDCleared() {
		_spec.ClearField(tenant.FieldSubscriptionID, field.TypeString)
	}
	if value, ok := _u.mutation.TierLimits(); ok {
		_spec.SetField(tenant.FieldTierLimits, field.TypeJSON, value)
	}
	if _u.mutation.TierLimitsCleared() {
		_spec.ClearField(tenant.FieldTierLimits, field.TypeJSON)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(tenant.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(tenant.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipsTable,
			Columns: []string{tenant.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantmembership.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !_u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipsTable,
			Columns: []string{tenant.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantmembership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipsTable,
			Columns: []string{tenant.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantmembership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OutletsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.OutletsTable,
			Columns: []string{tenant.OutletsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(outlet.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOutletsIDs(); len(nodes) > 0 && !_u.mutation.OutletsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.OutletsTable,
			Columns: []string{tenant.OutletsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(outlet.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OutletsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.OutletsTable,
			Columns: []string{tenant.OutletsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(outlet.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantUpdateOne is the builder for updating a single Tenant entity.
type TenantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantMutation
}

// SetName sets the "name" field.
func (_u *TenantUpdateOne) SetName(v string) *TenantUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableName(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *TenantUpdateOne) SetSlug(v string) *TenantUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableSlug(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantUpdateOne) SetStatus(v string) *TenantUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableStatus(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSubscriptionExempt sets the "subscription_exempt" field.
func (_u *TenantUpdateOne) SetSubscriptionExempt(v bool) *TenantUpdateOne {
	_u.mutation.SetSubscriptionExempt(v)
	return _u
}

// SetNillableSubscriptionExempt sets the "subscription_exempt" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableSubscriptionExempt(v *bool) *TenantUpdateOne {
	if v != nil {
		_u.SetSubscriptionExempt(*v)
	}
	return _u
}

// SetIsDemo sets the "is_demo" field.
func (_u *TenantUpdateOne) SetIsDemo(v bool) *TenantUpdateOne {
	_u.mutation.SetIsDemo(v)
	return _u
}

// SetNillableIsDemo sets the "is_demo" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableIsDemo(v *bool) *TenantUpdateOne {
	if v != nil {
		_u.SetIsDemo(*v)
	}
	return _u
}

// SetIsReseller sets the "is_reseller" field.
func (_u *TenantUpdateOne) SetIsReseller(v bool) *TenantUpdateOne {
	_u.mutation.SetIsReseller(v)
	return _u
}

// SetNillableIsReseller sets the "is_reseller" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableIsReseller(v *bool) *TenantUpdateOne {
	if v != nil {
		_u.SetIsReseller(*v)
	}
	return _u
}

// SetManagedByResellerTenantID sets the "managed_by_reseller_tenant_id" field.
func (_u *TenantUpdateOne) SetManagedByResellerTenantID(v uuid.UUID) *TenantUpdateOne {
	_u.mutation.SetManagedByResellerTenantID(v)
	return _u
}

// SetNillableManagedByResellerTenantID sets the "managed_by_reseller_tenant_id" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableManagedByResellerTenantID(v *uuid.UUID) *TenantUpdateOne {
	if v != nil {
		_u.SetManagedByResellerTenantID(*v)
	}
	return _u
}

// ClearManagedByResellerTenantID clears the value of the "managed_by_reseller_tenant_id" field.
func (_u *TenantUpdateOne) ClearManagedByResellerTenantID() *TenantUpdateOne {
	_u.mutation.ClearManagedByResellerTenantID()
	return _u
}

// SetContactEmail sets the "contact_email" field.
func (_u *TenantUpdateOne) SetContactEmail(v string) *TenantUpdateOne {
	_u.mutation.SetContactEmail(v)
	return _u
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableContactEmail(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetContactEmail(*v)
	}
	return _u
}

// ClearContactEmail clears the value of the "contact_email" field.
func (_u *TenantUpdateOne) ClearContactEmail() *TenantUpdateOne {
	_u.mutation.ClearContactEmail()
	return _u
}

// SetContactPhone sets the "contact_phone" field.
func (_u *TenantUpdateOne) SetContactPhone(v string) *TenantUpdateOne {
	_u.mutation.SetContactPhone(v)
	return _u
}

// SetNillableContactPhone sets the "contact_phone" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableContactPhone(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetContactPhone(*v)
	}
	return _u
}

// ClearContactPhone clears the value of the "contact_phone" field.
func (_u *TenantUpdateOne) ClearContactPhone() *TenantUpdateOne {
	_u.mutation.ClearContactPhone()
	return _u
}

// SetLogoURL sets the "logo_url" field.
func (_u *TenantUpdateOne) SetLogoURL(v string) *TenantUpdateOne {
	_u.mutation.SetLogoURL(v)
	return _u
}

// SetNillableLogoURL sets the "logo_url" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableLogoURL(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetLogoURL(*v)
	}
	return _u
}

// ClearLogoURL clears the value of the "logo_url" field.
func (_u *TenantUpdateOne) ClearLogoURL() *TenantUpdateOne {
	_u.mutation.ClearLogoURL()
	return _u
}

// SetWebsite sets the "website" field.
func (_u *TenantUpdateOne) SetWebsite(v string) *TenantUpdateOne {
	_u.mutation.SetWebsite(v)
	return _u
}

// SetNillableWebsite sets the "website" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableWebsite(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetWebsite(*v)
	}
	return _u
}

// ClearWebsite clears the value of the "website" field.
func (_u *TenantUpdateOne) ClearWebsite() *TenantUpdateOne {
	_u.mutation.ClearWebsite()
	return _u
}

// SetCountry sets the "country" field.
func (_u *TenantUpdateOne) SetCountry(v string) *TenantUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableCountry(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *TenantUpdateOne) ClearCountry() *TenantUpdateOne {
	_u.mutation.ClearCountry()
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *TenantUpdateOne) SetTimezone(v string) *TenantUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableTimezone(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// ClearTimezone clears the value of the "timezone" field.
func (_u *TenantUpdateOne) ClearTimezone() *TenantUpdateOne {
	_u.mutation.ClearTimezone()
	return _u
}

// SetBrandColors sets the "brand_colors" field.
func (_u *TenantUpdateOne) SetBrandColors(v map[string]interface{}) *TenantUpdateOne {
	_u.mutation.SetBrandColors(v)
	return _u
}

// ClearBrandColors clears the value of the "brand_colors" field.
func (_u *TenantUpdateOne) ClearBrandColors() *TenantUpdateOne {
	_u.mutation.ClearBrandColors()
	return _u
}

// SetOrgSize sets the "org_size" field.
func (_u *TenantUpdateOne) SetOrgSize(v string) *TenantUpdateOne {
	_u.mutation.SetOrgSize(v)
	return _u
}

// SetNillableOrgSize sets the "org_size" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableOrgSize(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetOrgSize(*v)
	}
	return _u
}

// ClearOrgSize clears the value of the "org_size" field.
func (_u *TenantUpdateOne) ClearOrgSize() *TenantUpdateOne {
	_u.mutation.ClearOrgSize()
	return _u
}

// SetUseCase sets the "use_case" field.
func (_u *TenantUpdateOne) SetUseCase(v string) *TenantUpdateOne {
	_u.mutation.SetUseCase(v)
	return _u
}

// SetNillableUseCase sets the "use_case" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableUseCase(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetUseCase(*v)
	}
	return _u
}

// ClearUseCase clears the value of the "use_case" field.
func (_u *TenantUpdateOne) ClearUseCase() *TenantUpdateOne {
	_u.mutation.ClearUseCase()
	return _u
}

// SetUseCases sets the "use_cases" field.
func (_u *TenantUpdateOne) SetUseCases(v []string) *TenantUpdateOne {
	_u.mutation.SetUseCases(v)
	return _u
}

// AppendUseCases appends value to the "use_cases" field.
func (_u *TenantUpdateOne) AppendUseCases(v []string) *TenantUpdateOne {
	_u.mutation.AppendUseCases(v)
	return _u
}

// ClearUseCases clears the value of the "use_cases" field.
func (_u *TenantUpdateOne) ClearUseCases() *TenantUpdateOne {
	_u.mutation.ClearUseCases()
	return _u
}

// SetTaxPin sets the "tax_pin" field.
func (_u *TenantUpdateOne) SetTaxPin(v string) *TenantUpdateOne {
	_u.mutation.SetTaxPin(v)
	return _u
}

// SetNillableTaxPin sets the "tax_pin" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableTaxPin(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetTaxPin(*v)
	}
	return _u
}

// ClearTaxPin clears the value of the "tax_pin" field.
func (_u *TenantUpdateOne) ClearTaxPin() *TenantUpdateOne {
	_u.mutation.ClearTaxPin()
	return _u
}

// SetVatRegistered sets the "vat_registered" field.
func (_u *TenantUpdateOne) SetVatRegistered(v bool) *TenantUpdateOne {
	_u.mutation.SetVatRegistered(v)
	return _u
}

// SetNillableVatRegistered sets the "vat_registered" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableVatRegistered(v *bool) *TenantUpdateOne {
	if v != nil {
		_u.SetVatRegistered(*v)
	}
	return _u
}

// SetVatRegisteredOn sets the "vat_registered_on" field.
func (_u *TenantUpdateOne) SetVatRegisteredOn(v time.Time) *TenantUpdateOne {
	_u.mutation.SetVatRegisteredOn(v)
	return _u
}

// SetNillableVatRegisteredOn sets the "vat_registered_on" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableVatRegisteredOn(v *time.Time) *TenantUpdateOne {
	if v != nil {
		_u.SetVatRegisteredOn(*v)
	}
	return _u
}

// ClearVatRegisteredOn clears the value of the "vat_registered_on" field.
func (_u *TenantUpdateOne) ClearVatRegisteredOn() *TenantUpdateOne {
	_u.mutation.ClearVatRegisteredOn()
	return _u
}

// SetSubscriptionPlan sets the "subscription_plan" field.
func (_u *TenantUpdateOne) SetSubscriptionPlan(v string) *TenantUpdateOne {
	_u.mutation.SetSubscriptionPlan(v)
	return _u
}

// SetNillableSubscriptionPlan sets the "subscription_plan" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableSubscriptionPlan(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetSubscriptionPlan(*v)
	}
	return _u
}

// ClearSubscriptionPlan clears the value of the "subscription_plan" field.
func (_u *TenantUpdateOne) ClearSubscriptionPlan() *TenantUpdateOne {
	_u.mutation.ClearSubscriptionPlan()
	return _u
}

// SetSubscriptionStatus sets the "subscription_status" field.
func (_u *TenantUpdateOne) SetSubscriptionStatus(v string) *TenantUpdateOne {
	_u.mutation.SetSubscriptionStatus(v)
	return _u
}

// SetNillableSubscriptionStatus sets the "subscription_status" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableSubscriptionStatus(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetSubscriptionStatus(*v)
	}
	return _u
}

// ClearSubscriptionStatus clears the value of the "subscription_status" field.
func (_u *TenantUpdateOne) ClearSubscriptionStatus() *TenantUpdateOne {
	_u.mutation.ClearSubscriptionStatus()
	return _u
}

// SetSubscriptionExpiresAt sets the "subscription_expires_at" field.
func (_u *TenantUpdateOne) SetSubscriptionExpiresAt(v time.Time) *TenantUpdateOne {
	_u.mutation.SetSubscriptionExpiresAt(v)
	return _u
}

// SetNillableSubscriptionExpiresAt sets the "subscription_expires_at" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableSubscriptionExpiresAt(v *time.Time) *TenantUpdateOne {
	if v != nil {
		_u.SetSubscriptionExpiresAt(*v)
	}
	return _u
}

// ClearSubscriptionExpiresAt clears the value of the "subscription_expires_at" field.
func (_u *TenantUpdateOne) ClearSubscriptionExpiresAt() *TenantUpdateOne {
	_u.mutation.ClearSubscriptionExpiresAt()
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *TenantUpdateOne) SetSubscriptionID(v string) *TenantUpdateOne {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableSubscriptionID(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (_u *TenantUpdateOne) ClearSubscriptionID() *TenantUpdateOne {
	_u.mutation.ClearSubscriptionID()
	return _u
}

// SetTierLimits sets the "tier_limits" field.
func (_u *TenantUpdateOne) SetTierLimits(v map[string]interface{}) *TenantUpdateOne {
	_u.mutation.SetTierLimits(v)
	return _u
}

// ClearTierLimits clears the value of the "tier_limits" field.
func (_u *TenantUpdateOne) ClearTierLimits() *TenantUpdateOne {
	_u.mutation.ClearTierLimits()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *TenantUpdateOne) SetMetadata(v map[string]interface{}) *TenantUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *TenantUpdateOne) ClearMetadata() *TenantUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantUpdateOne) SetUpdatedAt(v time.Time) *TenantUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddMembershipIDs adds the "memberships" edge to the TenantMembership entity by IDs.
func (_u *TenantUpdateOne) AddMembershipIDs(ids ...uuid.UUID) *TenantUpdateOne {
	_u.mutation.AddMembershipIDs(ids...)
	return _u
}

// AddMemberships adds the "memberships" edges to the TenantMembership entity.
func (_u *TenantUpdateOne) AddMemberships(v ...*TenantMembership) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipIDs(ids...)
}

// AddOutletIDs adds the "outlets" edge to the Outlet entity by IDs.
func (_u *TenantUpdateOne) AddOutletIDs(ids ...uuid.UUID) *TenantUpdateOne {
	_u.mutation.AddOutletIDs(ids...)
	return _u
}

// AddOutlets adds the "outlets" edges to the Outlet entity.
func (_u *TenantUpdateOne) AddOutlets(v ...*Outlet) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOutletIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdateOne) Mutation() *TenantMutation {
	return _u.mutation
}

// ClearMemberships clears all "memberships" edges to the TenantMembership entity.
func (_u *TenantUpdateOne) ClearMemberships() *TenantUpdateOne {
	_u.mutation.ClearMemberships()
	return _u
}

// RemoveMembershipIDs removes the "memberships" edge to TenantMembership entities by IDs.
func (_u *TenantUpdateOne) RemoveMembershipIDs(ids ...uuid.UUID) *TenantUpdateOne {
	_u.mutation.RemoveMembershipIDs(ids...)
	return _u
}

// RemoveMemberships removes "memberships" edges to TenantMembership entities.
func (_u *TenantUpdateOne) RemoveMemberships(v ...*TenantMembership) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipIDs(ids...)
}

// ClearOutlets clears all "outlets" edges to the Outlet entity.
func (_u *TenantUpdateOne) ClearOutlets() *TenantUpdateOne {
	_u.mutation.ClearOutlets()
	return _u
}

// RemoveOutletIDs removes the "outlets" edge to Outlet entities by IDs.
func (_u *TenantUpdateOne) RemoveOutletIDs(ids ...uuid.UUID) *TenantUpdateOne {
	_u.mutation.RemoveOutletIDs(ids...)
	return _u
}

// RemoveOutlets removes "outlets" edges to Outlet entities.
func (_u *TenantUpdateOne) RemoveOutlets(v ...*Outlet) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOutletIDs(ids...)
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdateOne) Where(ps ...predicate.Tenant) *TenantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantUpdateOne) Select(field string, fields ...string) *TenantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tenant entity.
func (_u *TenantUpdateOne) Save(ctx context.Context) (*Tenant, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdateOne) SaveX(ctx context.Context) *Tenant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := tenant.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Tenant.slug": %w`, err)}
		}
	}
	return nil
}

func (_u *TenantUpdateOne) sqlSave(ctx context.Context) (_node *Tenant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tenant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenant.FieldID)
		for _, f := range fields {
			if !tenant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(tenant.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenant.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubscriptionExempt(); ok {
		_spec.SetField(tenant.FieldSubscriptionExempt, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsDemo(); ok {
		_spec.SetField(tenant.FieldIsDemo, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsReseller(); ok {
		_spec.SetField(tenant.FieldIsReseller, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ManagedByResellerTenantID(); ok {
		_spec.SetField(tenant.FieldManagedByResellerTenantID, field.TypeUUID, value)
	}
	if _u.mutation.ManagedByResellerTenantIDCleared() {
		_spec.ClearField(tenant.FieldManagedByResellerTenantID, field.TypeUUID)
	}
	if value, ok := _u.mutation.ContactEmail(); ok {
		_spec.SetField(tenant.FieldContactEmail, field.TypeString, value)
	}
	if _u.mutation.ContactEmailCleared() {
		_spec.ClearField(tenant.FieldContactEmail, field.TypeString)
	}
	if value, ok := _u.mutation.ContactPhone(); ok {
		_spec.SetField(tenant.FieldContactPhone, field.TypeString, value)
	}
	if _u.mutation.ContactPhoneCleared() {
		_spec.ClearField(tenant.FieldContactPhone, field.TypeString)
	}
	if value, ok := _u.mutation.LogoURL(); ok {
		_spec.SetField(tenant.FieldLogoURL, field.TypeString, value)
	}
	if _u.mutation.LogoURLCleared() {
		_spec.ClearField(tenant.FieldLogoURL, field.TypeString)
	}
	if value, ok := _u.mutation.Website(); ok {
		_spec.SetField(tenant.FieldWebsite, field.TypeString, value)
	}
	if _u.mutation.WebsiteCleared() {
		_spec.ClearField(tenant.FieldWebsite, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(tenant.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(tenant.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(tenant.FieldTimezone, field.TypeString, value)
	}
	if _u.mutation.TimezoneCleared() {
		_spec.ClearField(tenant.FieldTimezone, field.TypeString)
	}
	if value, ok := _u.mutation.BrandColors(); ok {
		_spec.SetField(tenant.FieldBrandColors, field.TypeJSON, value)
	}
	if _u.mutation.BrandColorsCleared() {
		_spec.ClearField(tenant.FieldBrandColors, field.TypeJSON)
	}
	if value, ok := _u.mutation.OrgSize(); ok {
		_spec.SetField(tenant.FieldOrgSize, field.TypeString, value)
	}
	if _u.mutation.OrgSizeCleared() {
		_spec.ClearField(tenant.FieldOrgSize, field.TypeString)
	}
	if value, ok := _u.mutation.UseCase(); ok {
		_spec.SetField(tenant.FieldUseCase, field.TypeString, value)
	}
	if _u.mutation.UseCaseCleared() {
		_spec.ClearField(tenant.FieldUseCase, field.TypeString)
	}
	if value, ok := _u.mutation.UseCases(); ok {
		_spec.SetField(tenant.FieldUseCases, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUseCases(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenant.FieldUseCases, value)
		})
	}
	if _u.mutation.UseCasesCleared() {
		_spec.ClearField(tenant.FieldUseCases, field.TypeJSON)
	}
	if value, ok := _u.mutation.TaxPin(); ok {
		_spec.SetField(tenant.FieldTaxPin, field.TypeString, value)
	}
	if _u.mutation.TaxPinCleared() {
		_spec.ClearField(tenant.FieldTaxPin, field.TypeString)
	}
	if value, ok := _u.mutation.VatRegistered(); ok {
		_spec.SetField(tenant.FieldVatRegistered, field.TypeBool, value)
	}
	if value, ok := _u.mutation.VatRegisteredOn(); ok {
		_spec.SetField(tenant.FieldVatRegisteredOn, field.TypeTime, value)
	}
	if _u.mutation.VatRegisteredOnCleared() {
		_spec.ClearField(tenant.FieldVatRegisteredOn, field.TypeTime)
	}
	if value, ok := _u.mutation.SubscriptionPlan(); ok {
		_spec.SetField(tenant.FieldSubscriptionPlan, field.TypeString, value)
	}
	if _u.mutation.SubscriptionPlanCleared() {
		_spec.ClearField(tenant.FieldSubscriptionPlan, field.TypeString)
	}
	if value, ok := _u.mutation.SubscriptionStatus(); ok {
		_spec.SetField(tenant.FieldSubscriptionStatus, field.TypeString, value)
	}
	if _u.mutation.SubscriptionStatusCleared() {
		_spec.ClearField(tenant.FieldSubscriptionStatus, field.TypeString)
	}
	if value, ok := _u.mutation.SubscriptionExpiresAt(); ok {
		_spec.SetField(tenant.FieldSubscriptionExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.SubscriptionExpiresAtCleared() {
		_spec.ClearField(tenant.FieldSubscriptionExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(tenant.FieldSubscriptionID, field.TypeString, value)
	}
	if _u.mutation.SubscriptionIDCleared() {
		_spec.ClearField(tenant.FieldSubscriptionID, field.TypeString)
	}
	if value, ok := _u.mutation.TierLimits(); ok {
		_spec.SetField(tenant.FieldTierLimits, field.TypeJSON, value)
	}
	if _u.mutation.TierLimitsCleared() {
		_spec.ClearField(tenant.FieldTierLimits, field.TypeJSON)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(tenant.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(tenant.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipsTable,
			Columns: []string{tenant.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantmembership.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !_u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipsTable,
			Columns: []string{tenant.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantmembership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipsTable,
			Columns: []string{tenant.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantmembership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OutletsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.OutletsTable,
			Columns: []string{tenant.OutletsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(outlet.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOutletsIDs(); len(nodes) > 0 && !_u.mutation.OutletsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.OutletsTable,
			Columns: []string{tenant.OutletsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(outlet.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OutletsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.OutletsTable,
			Columns: []string{tenant.OutletsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(outlet.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Tenant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
