// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/auth-api/internal/ent/user"
	"github.com/bengobox/auth-api/internal/ent/webauthncredential"
	"github.com/google/uuid"
)

// WebAuthnCredential is the model entity for the WebAuthnCredential schema.
type WebAuthnCredential struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// CredentialID holds the value of the "credential_id" field.
	CredentialID []byte `json:"credential_id,omitempty"`
	// PublicKey holds the value of the "public_key" field.
	PublicKey []byte `json:"public_key,omitempty"`
	// Aaguid holds the value of the "aaguid" field.
	Aaguid string `json:"aaguid,omitempty"`
	// SignCount holds the value of the "sign_count" field.
	SignCount uint32 `json:"sign_count,omitempty"`
	// Transports holds the value of the "transports" field.
	Transports []string `json:"transports,omitempty"`
	// UserVerified holds the value of the "user_verified" field.
	UserVerified bool `json:"user_verified,omitempty"`
	// BackupEligible holds the value of the "backup_eligible" field.
	BackupEligible bool `json:"backup_eligible,omitempty"`
	// BackupState holds the value of the "backup_state" field.
	BackupState bool `json:"backup_state,omitempty"`
	// FriendlyName holds the value of the "friendly_name" field.
	FriendlyName string `json:"friendly_name,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// LastUsedAt holds the value of the "last_used_at" field.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WebAuthnCredentialQuery when eager-loading is set.
	Edges        WebAuthnCredentialEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WebAuthnCredentialEdges holds the relations/edges for other nodes in the graph.
type WebAuthnCredentialEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WebAuthnCredentialEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WebAuthnCredential) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case webauthncredential.FieldCredentialID, webauthncredential.FieldPublicKey, webauthncredential.FieldTransports:
			values[i] = new([]byte)
		case webauthncredential.FieldUserVerified, webauthncredential.FieldBackupEligible, webauthncredential.FieldBackupState:
			values[i] = new(sql.NullBool)
		case webauthncredential.FieldSignCount:
			values[i] = new(sql.NullInt64)
		case webauthncredential.FieldAaguid, webauthncredential.FieldFriendlyName:
			values[i] = new(sql.NullString)
		case webauthncredential.FieldCreatedAt, webauthncredential.FieldLastUsedAt:
			values[i] = new(sql.NullTime)
		case webauthncredential.FieldID, webauthncredential.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WebAuthnCredential fields.
func (_m *WebAuthnCredential) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case webauthncredential.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case webauthncredential.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case webauthncredential.FieldCredentialID:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field credential_id", values[i])
			} else if value != nil {
				_m.CredentialID = *value
			}
		case webauthncredential.FieldPublicKey:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field public_key", values[i])
			} else if value != nil {
				_m.PublicKey = *value
			}
		case webauthncredential.FieldAaguid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field aaguid", values[i])
			} else if value.Valid {
				_m.Aaguid = value.String
			}
		case webauthncredential.FieldSignCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sign_count", values[i])
			} else if value.Valid {
				_m.SignCount = uint32(value.Int64)
			}
		case webauthncredential.FieldTransports:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field transports", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Transports); err != nil {
					return fmt.Errorf("unmarshal field transports: %w", err)
				}
			}
		case webauthncredential.FieldUserVerified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field user_verified", values[i])
			} else if value.Valid {
				_m.UserVerified = value.Bool
			}
		case webauthncredential.FieldBackupEligible:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field backup_eligible", values[i])
			} else if value.Valid {
				_m.BackupEligible = value.Bool
			}
		case webauthncredential.FieldBackupState:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field backup_state", values[i])
			} else if value.Valid {
				_m.BackupState = value.Bool
			}
		case webauthncredential.FieldFriendlyName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field friendly_name", values[i])
			} else if value.Valid {
				_m.FriendlyName = value.String
			}
		case webauthncredential.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case webauthncredential.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				_m.LastUsedAt = new(time.Time)
				*_m.LastUsedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WebAuthnCredential.
// This includes values selected through modifiers, order, etc.
func (_m *WebAuthnCredential) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the WebAuthnCredential entity.
func (_m *WebAuthnCredential) QueryUser() *UserQuery {
	return NewWebAuthnCredentialClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this WebAuthnCredential.
// Note that you need to call WebAuthnCredential.Unwrap() before calling this method if this WebAuthnCredential
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WebAuthnCredential) Update() *WebAuthnCredentialUpdateOne {
	return NewWebAuthnCredentialClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WebAuthnCredential entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WebAuthnCredential) Unwrap() *WebAuthnCredential {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WebAuthnCredential is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WebAuthnCredential) String() string {
	var builder strings.Builder
	builder.WriteString("WebAuthnCredential(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("credential_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CredentialID))
	builder.WriteString(", ")
	builder.WriteString("public_key=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublicKey))
	builder.WriteString(", ")
	builder.WriteString("aaguid=")
	builder.WriteString(_m.Aaguid)
	builder.WriteString(", ")
	builder.WriteString("sign_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SignCount))
	builder.WriteString(", ")
	builder.WriteString("transports=")
	builder.WriteString(fmt.Sprintf("%v", _m.Transports))
	builder.WriteString(", ")
	builder.WriteString("user_verified=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserVerified))
	builder.WriteString(", ")
	builder.WriteString("backup_eligible=")
	builder.WriteString(fmt.Sprintf("%v", _m.BackupEligible))
	builder.WriteString(", ")
	builder.WriteString("backup_state=")
	builder.WriteString(fmt.Sprintf("%v", _m.BackupState))
	builder.WriteString(", ")
	builder.WriteString("friendly_name=")
	builder.WriteString(_m.FriendlyName)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastUsedAt; v != nil {
		builder.WriteString("last_used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// WebAuthnCredentials is a parsable slice of WebAuthnCredential.
type WebAuthnCredentials []*WebAuthnCredential
