// Code generated by ent, DO NOT EDIT.

package referrallink

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/auth-api/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldLTE(FieldID, id))
}

// ReferrerTenantID applies equality check predicate on the "referrer_tenant_id" field. It's identical to ReferrerTenantIDEQ.
func ReferrerTenantID(v uuid.UUID) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldEQ(FieldReferrerTenantID, v))
}

// ReferralCode applies equality check predicate on the "referral_code" field. It's identical to ReferralCodeEQ.
func ReferralCode(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldEQ(FieldReferralCode, v))
}

// ProgramID applies equality check predicate on the "program_id" field. It's identical to ProgramIDEQ.
func ProgramID(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldEQ(FieldProgramID, v))
}

// Clicks applies equality check predicate on the "clicks" field. It's identical to ClicksEQ.
func Clicks(v int) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldEQ(FieldClicks, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldEQ(FieldExpiresAt, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldEQ(FieldUpdatedAt, v))
}

// ReferrerTenantIDEQ applies the EQ predicate on the "referrer_tenant_id" field.
func ReferrerTenantIDEQ(v uuid.UUID) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldEQ(FieldReferrerTenantID, v))
}

// ReferrerTenantIDNEQ applies the NEQ predicate on the "referrer_tenant_id" field.
func ReferrerTenantIDNEQ(v uuid.UUID) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldNEQ(FieldReferrerTenantID, v))
}

// ReferrerTenantIDIn applies the In predicate on the "referrer_tenant_id" field.
func ReferrerTenantIDIn(vs ...uuid.UUID) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldIn(FieldReferrerTenantID, vs...))
}

// ReferrerTenantIDNotIn applies the NotIn predicate on the "referrer_tenant_id" field.
func ReferrerTenantIDNotIn(vs ...uuid.UUID) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldNotIn(FieldReferrerTenantID, vs...))
}

// ReferrerTenantIDGT applies the GT predicate on the "referrer_tenant_id" field.
func ReferrerTenantIDGT(v uuid.UUID) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldGT(FieldReferrerTenantID, v))
}

// ReferrerTenantIDGTE applies the GTE predicate on the "referrer_tenant_id" field.
func ReferrerTenantIDGTE(v uuid.UUID) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldGTE(FieldReferrerTenantID, v))
}

// ReferrerTenantIDLT applies the LT predicate on the "referrer_tenant_id" field.
func ReferrerTenantIDLT(v uuid.UUID) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldLT(FieldReferrerTenantID, v))
}

// ReferrerTenantIDLTE applies the LTE predicate on the "referrer_tenant_id" field.
func ReferrerTenantIDLTE(v uuid.UUID) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldLTE(FieldReferrerTenantID, v))
}

// ReferralCodeEQ applies the EQ predicate on the "referral_code" field.
func ReferralCodeEQ(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldEQ(FieldReferralCode, v))
}

// ReferralCodeNEQ applies the NEQ predicate on the "referral_code" field.
func ReferralCodeNEQ(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldNEQ(FieldReferralCode, v))
}

// ReferralCodeIn applies the In predicate on the "referral_code" field.
func ReferralCodeIn(vs ...string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldIn(FieldReferralCode, vs...))
}

// ReferralCodeNotIn applies the NotIn predicate on the "referral_code" field.
func ReferralCodeNotIn(vs ...string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldNotIn(FieldReferralCode, vs...))
}

// ReferralCodeGT applies the GT predicate on the "referral_code" field.
func ReferralCodeGT(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldGT(FieldReferralCode, v))
}

// ReferralCodeGTE applies the GTE predicate on the "referral_code" field.
func ReferralCodeGTE(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldGTE(FieldReferralCode, v))
}

// ReferralCodeLT applies the LT predicate on the "referral_code" field.
func ReferralCodeLT(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldLT(FieldReferralCode, v))
}

// ReferralCodeLTE applies the LTE predicate on the "referral_code" field.
func ReferralCodeLTE(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldLTE(FieldReferralCode, v))
}

// ReferralCodeContains applies the Contains predicate on the "referral_code" field.
func ReferralCodeContains(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldContains(FieldReferralCode, v))
}

// ReferralCodeHasPrefix applies the HasPrefix predicate on the "referral_code" field.
func ReferralCodeHasPrefix(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldHasPrefix(FieldReferralCode, v))
}

// ReferralCodeHasSuffix applies the HasSuffix predicate on the "referral_code" field.
func ReferralCodeHasSuffix(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldHasSuffix(FieldReferralCode, v))
}

// ReferralCodeEqualFold applies the EqualFold predicate on the "referral_code" field.
func ReferralCodeEqualFold(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldEqualFold(FieldReferralCode, v))
}

// ReferralCodeContainsFold applies the ContainsFold predicate on the "referral_code" field.
func ReferralCodeContainsFold(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldContainsFold(FieldReferralCode, v))
}

// ProgramIDEQ applies the EQ predicate on the "program_id" field.
func ProgramIDEQ(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldEQ(FieldProgramID, v))
}

// ProgramIDNEQ applies the NEQ predicate on the "program_id" field.
func ProgramIDNEQ(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldNEQ(FieldProgramID, v))
}

// ProgramIDIn applies the In predicate on the "program_id" field.
func ProgramIDIn(vs ...string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldIn(FieldProgramID, vs...))
}

// ProgramIDNotIn applies the NotIn predicate on the "program_id" field.
func ProgramIDNotIn(vs ...string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldNotIn(FieldProgramID, vs...))
}

// ProgramIDGT applies the GT predicate on the "program_id" field.
func ProgramIDGT(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldGT(FieldProgramID, v))
}

// ProgramIDGTE applies the GTE predicate on the "program_id" field.
func ProgramIDGTE(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldGTE(FieldProgramID, v))
}

// ProgramIDLT applies the LT predicate on the "program_id" field.
func ProgramIDLT(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldLT(FieldProgramID, v))
}

// ProgramIDLTE applies the LTE predicate on the "program_id" field.
func ProgramIDLTE(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldLTE(FieldProgramID, v))
}

// ProgramIDContains applies the Contains predicate on the "program_id" field.
func ProgramIDContains(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldContains(FieldProgramID, v))
}

// ProgramIDHasPrefix applies the HasPrefix predicate on the "program_id" field.
func ProgramIDHasPrefix(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldHasPrefix(FieldProgramID, v))
}

// ProgramIDHasSuffix applies the HasSuffix predicate on the "program_id" field.
func ProgramIDHasSuffix(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldHasSuffix(FieldProgramID, v))
}

// ProgramIDIsNil applies the IsNil predicate on the "program_id" field.
func ProgramIDIsNil() predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldIsNull(FieldProgramID))
}

// ProgramIDNotNil applies the NotNil predicate on the "program_id" field.
func ProgramIDNotNil() predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldNotNull(FieldProgramID))
}

// ProgramIDEqualFold applies the EqualFold predicate on the "program_id" field.
func ProgramIDEqualFold(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldEqualFold(FieldProgramID, v))
}

// ProgramIDContainsFold applies the ContainsFold predicate on the "program_id" field.
func ProgramIDContainsFold(v string) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldContainsFold(FieldProgramID, v))
}

// ClicksEQ applies the EQ predicate on the "clicks" field.
func ClicksEQ(v int) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldEQ(FieldClicks, v))
}

// ClicksNEQ applies the NEQ predicate on the "clicks" field.
func ClicksNEQ(v int) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldNEQ(FieldClicks, v))
}

// ClicksIn applies the In predicate on the "clicks" field.
func ClicksIn(vs ...int) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldIn(FieldClicks, vs...))
}

// ClicksNotIn applies the NotIn predicate on the "clicks" field.
func ClicksNotIn(vs ...int) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldNotIn(FieldClicks, vs...))
}

// ClicksGT applies the GT predicate on the "clicks" field.
func ClicksGT(v int) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldGT(FieldClicks, v))
}

// ClicksGTE applies the GTE predicate on the "clicks" field.
func ClicksGTE(v int) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldGTE(FieldClicks, v))
}

// ClicksLT applies the LT predicate on the "clicks" field.
func ClicksLT(v int) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldLT(FieldClicks, v))
}

// ClicksLTE applies the LTE predicate on the "clicks" field.
func ClicksLTE(v int) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldLTE(FieldClicks, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldNotNull(FieldExpiresAt))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldNEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ReferralLink {
	return predicate.ReferralLink(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReferralLink) predicate.ReferralLink {
	return predicate.ReferralLink(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReferralLink) predicate.ReferralLink {
	return predicate.ReferralLink(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReferralLink) predicate.ReferralLink {
	return predicate.ReferralLink(sql.NotPredicates(p))
}
