// Code generated by ent, DO NOT EDIT.

package app

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/auth-api/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.App {
	return predicate.App(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.App {
	return predicate.App(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldDescription, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldEQ(FieldTenantID, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldEQ(FieldCreatedBy, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldClientID, v))
}

// KeyHash applies equality check predicate on the "key_hash" field. It's identical to KeyHashEQ.
func KeyHash(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldKeyHash, v))
}

// KeyPrefix applies equality check predicate on the "key_prefix" field. It's identical to KeyPrefixEQ.
func KeyPrefix(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldKeyPrefix, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldExpiresAt, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedIP applies equality check predicate on the "last_used_ip" field. It's identical to LastUsedIPEQ.
func LastUsedIP(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldLastUsedIP, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldUpdatedAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedReason applies equality check predicate on the "revoked_reason" field. It's identical to RevokedReasonEQ.
func RevokedReason(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldRevokedReason, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldDescription, v))
}

// AppTypeEQ applies the EQ predicate on the "app_type" field.
func AppTypeEQ(v AppType) predicate.App {
	return predicate.App(sql.FieldEQ(FieldAppType, v))
}

// AppTypeNEQ applies the NEQ predicate on the "app_type" field.
func AppTypeNEQ(v AppType) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldAppType, v))
}

// AppTypeIn applies the In predicate on the "app_type" field.
func AppTypeIn(vs ...AppType) predicate.App {
	return predicate.App(sql.FieldIn(FieldAppType, vs...))
}

// AppTypeNotIn applies the NotIn predicate on the "app_type" field.
func AppTypeNotIn(vs ...AppType) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldAppType, vs...))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.App {
	return predicate.App(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldTenantID))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uuid.UUID) predicate.App {
	return predicate.App(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uuid.UUID) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uuid.UUID) predicate.App {
	return predicate.App(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldCreatedBy))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldClientID, v))
}

// KeyHashEQ applies the EQ predicate on the "key_hash" field.
func KeyHashEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldKeyHash, v))
}

// KeyHashNEQ applies the NEQ predicate on the "key_hash" field.
func KeyHashNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldKeyHash, v))
}

// KeyHashIn applies the In predicate on the "key_hash" field.
func KeyHashIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldKeyHash, vs...))
}

// KeyHashNotIn applies the NotIn predicate on the "key_hash" field.
func KeyHashNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldKeyHash, vs...))
}

// KeyHashGT applies the GT predicate on the "key_hash" field.
func KeyHashGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldKeyHash, v))
}

// KeyHashGTE applies the GTE predicate on the "key_hash" field.
func KeyHashGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldKeyHash, v))
}

// KeyHashLT applies the LT predicate on the "key_hash" field.
func KeyHashLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldKeyHash, v))
}

// KeyHashLTE applies the LTE predicate on the "key_hash" field.
func KeyHashLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldKeyHash, v))
}

// KeyHashContains applies the Contains predicate on the "key_hash" field.
func KeyHashContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldKeyHash, v))
}

// KeyHashHasPrefix applies the HasPrefix predicate on the "key_hash" field.
func KeyHashHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldKeyHash, v))
}

// KeyHashHasSuffix applies the HasSuffix predicate on the "key_hash" field.
func KeyHashHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldKeyHash, v))
}

// KeyHashEqualFold applies the EqualFold predicate on the "key_hash" field.
func KeyHashEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldKeyHash, v))
}

// KeyHashContainsFold applies the ContainsFold predicate on the "key_hash" field.
func KeyHashContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldKeyHash, v))
}

// KeyPrefixEQ applies the EQ predicate on the "key_prefix" field.
func KeyPrefixEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldKeyPrefix, v))
}

// KeyPrefixNEQ applies the NEQ predicate on the "key_prefix" field.
func KeyPrefixNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldKeyPrefix, v))
}

// KeyPrefixIn applies the In predicate on the "key_prefix" field.
func KeyPrefixIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldKeyPrefix, vs...))
}

// KeyPrefixNotIn applies the NotIn predicate on the "key_prefix" field.
func KeyPrefixNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldKeyPrefix, vs...))
}

// KeyPrefixGT applies the GT predicate on the "key_prefix" field.
func KeyPrefixGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldKeyPrefix, v))
}

// KeyPrefixGTE applies the GTE predicate on the "key_prefix" field.
func KeyPrefixGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldKeyPrefix, v))
}

// KeyPrefixLT applies the LT predicate on the "key_prefix" field.
func KeyPrefixLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldKeyPrefix, v))
}

// KeyPrefixLTE applies the LTE predicate on the "key_prefix" field.
func KeyPrefixLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldKeyPrefix, v))
}

// KeyPrefixContains applies the Contains predicate on the "key_prefix" field.
func KeyPrefixContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldKeyPrefix, v))
}

// KeyPrefixHasPrefix applies the HasPrefix predicate on the "key_prefix" field.
func KeyPrefixHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldKeyPrefix, v))
}

// KeyPrefixHasSuffix applies the HasSuffix predicate on the "key_prefix" field.
func KeyPrefixHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldKeyPrefix, v))
}

// KeyPrefixEqualFold applies the EqualFold predicate on the "key_prefix" field.
func KeyPrefixEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldKeyPrefix, v))
}

// KeyPrefixContainsFold applies the ContainsFold predicate on the "key_prefix" field.
func KeyPrefixContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldKeyPrefix, v))
}

// ScopesIsNil applies the IsNil predicate on the "scopes" field.
func ScopesIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldScopes))
}

// ScopesNotNil applies the NotNil predicate on the "scopes" field.
func ScopesNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldScopes))
}

// AllowedIpsIsNil applies the IsNil predicate on the "allowed_ips" field.
func AllowedIpsIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldAllowedIps))
}

// AllowedIpsNotNil applies the NotNil predicate on the "allowed_ips" field.
func AllowedIpsNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldAllowedIps))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.App {
	return predicate.App(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.App {
	return predicate.App(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldStatus, vs...))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.App {
	return predicate.App(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.App {
	return predicate.App(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldExpiresAt))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.App {
	return predicate.App(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.App {
	return predicate.App(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldLastUsedAt))
}

// LastUsedIPEQ applies the EQ predicate on the "last_used_ip" field.
func LastUsedIPEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldLastUsedIP, v))
}

// LastUsedIPNEQ applies the NEQ predicate on the "last_used_ip" field.
func LastUsedIPNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldLastUsedIP, v))
}

// LastUsedIPIn applies the In predicate on the "last_used_ip" field.
func LastUsedIPIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldLastUsedIP, vs...))
}

// LastUsedIPNotIn applies the NotIn predicate on the "last_used_ip" field.
func LastUsedIPNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldLastUsedIP, vs...))
}

// LastUsedIPGT applies the GT predicate on the "last_used_ip" field.
func LastUsedIPGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldLastUsedIP, v))
}

// LastUsedIPGTE applies the GTE predicate on the "last_used_ip" field.
func LastUsedIPGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldLastUsedIP, v))
}

// LastUsedIPLT applies the LT predicate on the "last_used_ip" field.
func LastUsedIPLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldLastUsedIP, v))
}

// LastUsedIPLTE applies the LTE predicate on the "last_used_ip" field.
func LastUsedIPLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldLastUsedIP, v))
}

// LastUsedIPContains applies the Contains predicate on the "last_used_ip" field.
func LastUsedIPContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldLastUsedIP, v))
}

// LastUsedIPHasPrefix applies the HasPrefix predicate on the "last_used_ip" field.
func LastUsedIPHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldLastUsedIP, v))
}

// LastUsedIPHasSuffix applies the HasSuffix predicate on the "last_used_ip" field.
func LastUsedIPHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldLastUsedIP, v))
}

// LastUsedIPIsNil applies the IsNil predicate on the "last_used_ip" field.
func LastUsedIPIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldLastUsedIP))
}

// LastUsedIPNotNil applies the NotNil predicate on the "last_used_ip" field.
func LastUsedIPNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldLastUsedIP))
}

// LastUsedIPEqualFold applies the EqualFold predicate on the "last_used_ip" field.
func LastUsedIPEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldLastUsedIP, v))
}

// LastUsedIPContainsFold applies the ContainsFold predicate on the "last_used_ip" field.
func LastUsedIPContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldLastUsedIP, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.App {
	return predicate.App(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.App {
	return predicate.App(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.App {
	return predicate.App(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.App {
	return predicate.App(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldLTE(FieldUpdatedAt, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.App {
	return predicate.App(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.App {
	return predicate.App(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldRevokedAt))
}

// RevokedReasonEQ applies the EQ predicate on the "revoked_reason" field.
func RevokedReasonEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldRevokedReason, v))
}

// RevokedReasonNEQ applies the NEQ predicate on the "revoked_reason" field.
func RevokedReasonNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldRevokedReason, v))
}

// RevokedReasonIn applies the In predicate on the "revoked_reason" field.
func RevokedReasonIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldRevokedReason, vs...))
}

// RevokedReasonNotIn applies the NotIn predicate on the "revoked_reason" field.
func RevokedReasonNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldRevokedReason, vs...))
}

// RevokedReasonGT applies the GT predicate on the "revoked_reason" field.
func RevokedReasonGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldRevokedReason, v))
}

// RevokedReasonGTE applies the GTE predicate on the "revoked_reason" field.
func RevokedReasonGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldRevokedReason, v))
}

// RevokedReasonLT applies the LT predicate on the "revoked_reason" field.
func RevokedReasonLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldRevokedReason, v))
}

// RevokedReasonLTE applies the LTE predicate on the "revoked_reason" field.
func RevokedReasonLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldRevokedReason, v))
}

// RevokedReasonContains applies the Contains predicate on the "revoked_reason" field.
func RevokedReasonContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldRevokedReason, v))
}

// RevokedReasonHasPrefix applies the HasPrefix predicate on the "revoked_reason" field.
func RevokedReasonHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldRevokedReason, v))
}

// RevokedReasonHasSuffix applies the HasSuffix predicate on the "revoked_reason" field.
func RevokedReasonHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldRevokedReason, v))
}

// RevokedReasonIsNil applies the IsNil predicate on the "revoked_reason" field.
func RevokedReasonIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldRevokedReason))
}

// RevokedReasonNotNil applies the NotNil predicate on the "revoked_reason" field.
func RevokedReasonNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldRevokedReason))
}

// RevokedReasonEqualFold applies the EqualFold predicate on the "revoked_reason" field.
func RevokedReasonEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldRevokedReason, v))
}

// RevokedReasonContainsFold applies the ContainsFold predicate on the "revoked_reason" field.
func RevokedReasonContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldRevokedReason, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.App) predicate.App {
	return predicate.App(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.App) predicate.App {
	return predicate.App(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.App) predicate.App {
	return predicate.App(sql.NotPredicates(p))
}
